### ISSUE TITLE
If I create my wordpress site with Project Nami, is it stuck that way?

### ISSUE THREAD

**Issue by shaned9x** [ProjectNami/projectnami#102]
I apologize if this is the wrong place to ask this question. If I create a robust website with Project Nami and azure, what are the issues I would encounter? Are there any? Is it even possible?

Thanks in advance!

**Comment by pippercameron** [comment]
Hey @shaned9x! What do you mean by a "robust website"? PN sites on Azure can handle huge traffic loads when configured correctly, but I'm not sure if that's what you're asking or not. :)

**Comment by patrickebates** [comment]
Exporting your PN site and importing into WordPress will work.  As for your other questions, the only item you will likely run into issues with are plugins which create additional database tables.  There are too many variations of CREATE TABLE statements for us to handle them all at this time.  Besides, creating tables is technically a violation of WP coding standards.

**Comment by shaned9x** [comment]
Awesome! Sounds like I wont have any issues if I need to move my site.
Thank you!
