### ISSUE TITLE
Error in Deploy to Azure

### ISSUE THREAD

**Issue by peitung** [ProjectNami/projectnami#103]
I am trying to deploy to Azure using https://deploy.azure.com/?repository=https://github.com/ProjectNami/projectnami/tree/latest#/form/deploy

The process hangs at the step: Configuring SQL Server Firewall Rules

It appears that the sql server, database, and site are all created. When I access the site, it says the site is created, but nothing has been published.

There is an error at the step:

OPERATION NAME Update web sites config
STATUS Failed
EVENT TIMESTAMP Wed Jun 15 2016 19:08:08 GMT-0400 (EDT)
UTC TIMESTAMP Wed, 15 Jun 2016 23:08:08 GMT

EVENT SUBMISSION TIMESTAMP Wed Jun 15 2016 19:08:21 GMT-0400 (EDT)
OPERATION ID 7695e712-86ce-430f-9943-23b185fa3839
SUBSTATUS BadGateway
CORRELATION ID 027265d6-803f-457b-bf5c-b24d615dfe9a
HTTP REQUEST 
clientRequestId:d59fdce4 method:PUT
LEVEL Error

RESOURCE PROVIDER Azure Web Sites
CATEGORY Administrative
PROPERTIES 
statusCode:BadGateway serviceRequestId: statusMessage:{"error":{"code":"InternalServerError","message":""}}

**Comment by patrickebates** [comment]
Unfortunately this just happens sometimes.  But we would like to collect some data to provide Microsoft to assist them looking into it (the failures are within Azure).

What datacenter are you attempting to deploy to?
Are you using a directory other than your Default? (Known issue if you aren't using the default)

Another option is to create your Web App and SQL DB yourself and deploy Project Nami using tools within the Azure portal.  You can find the settings for the Continuous Deployment option at the bottom of this page  http://projectnami.org/video-updating-project-nami/

**Comment by peitung** [comment]
The datacenter is South Central US. I also tried West US and East US. All failed. The directory was always set to Default.

I tried several times, each time, using new resource group, and starting from scratch (deleting all resources).

**Comment by peitung** [comment]
Setting up a external repo as a deployment source worked. I was able sync and have the Wordpress installation complete.
