### ISSUE TITLE
Email nor SMTP working

### ISSUE THREAD

**Issue by DannyGlover** [ProjectNami/projectnami#104]
Hello there. First of all, thank you for this awesome project.

I have a big problem where Wordpress can't send mail, nor do any of the available SMTP plugins work (the SMTP plugin included, nor any of the other highly rated wordpress SMTP plugins).

For the built in mail: "The email could not be sent. Possible reason: your host may have disabled the mail() function."

For SMTP, I entered my gmail credentials and tried with both forms of encryption (and no encryption) and smtp_connect() always fails.

Here is a gist of php info: https://gist.github.com/DannyGlover/17750256f0758834cf519f4e82243c68
Is it possible to get mail working with wordpress via it's built in mail method, or SMTP with project nami?

Google did not turn up any helpful results for this, unfortunately. 

Thank you

**Comment by pippercameron** [comment]
I saw similar behavior recently, as well. I think there's a bug. :) Thanks for the report! We'll look into it and see what's up.

**Comment by DannyGlover** [comment]
@pippercameron Thank you very much!

**Comment by JamesW-AU** [comment]
Hi all. I'm having trouble with this as well. Was anyone able to figure out a solution?

**Comment by patrickebates** [comment]
Are you using a gmail account as well?

**Comment by JamesW-AU** [comment]
No, we've got Project Nami hosted locally sending to an internal SMTP server. We've configured it to send without auth, and the SMTP server is configured to accept mail from the server Nami is on.

**Comment by patrickebates** [comment]
Are you using a plugin to handle SMTP, and if so which one?
