### ISSUE TITLE
$wpdb->replace  

### ISSUE THREAD

**Issue by erikest** [ProjectNami/projectnami#105]
Got another query issue here.

Woocommerce uses $wpdb->replace in its includes/class-wc-session-handler.php save_data() function.  Checking their readme, they did this "Tweak" in version 2.5.3 on 1/3/16, so it's fairly new.

This is resulting in an unsupported REPLACE INTO query like:

`REPLACE INTO [wp_woocommerce_sessions] ([session_key], [session_value], [session_expiry]) VALUES (...)`

digging around, looks like _insert_replace_helper needs to be refactored to check for existence first, then do an update or insert.

I'm assuming this isn't the only plugin in the world that uses this wp api and since it is using an actual wp api and not an inline query, I'm assuming this is something you guys want to have handled in your port and not at the translations level.

Looks like this isn't a super straightforward problem to solve though, especially since the replace api doesn't separate the key/id field out so you can do a proper "update where".

I'm seeing the general solution to be something like (not a php guy, so bare with me here):

`function _insert_replace_helper( $table, $data, $format = null, $type = 'INSERT' ) {
		$this->insert_id = 0;

		if ( ! in_array( strtoupper( $type ), array( 'REPLACE', 'INSERT' ) ) ) {
			return false;
		}

		$data2 = $this->process_fields( $table, $data, $format );
		if ( false === $data ) {
			return false;
		}
	
	if ($type === 'REPLACE') {
        //Get the primary key for the table, this assumes just a single primary key col, so not too robust.
		$keyColQuery = 'SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
						WHERE TABLE_NAME LIKE \'$table\' AND CONSTRAINT_NAME LIKE \'PK%\'';
		this->query($keyColQuery);
		$keyName = this->lastResult[0]->COLUMN_NAME;		
		
		//Use the incoming data as the conditions for the select query
		$conditions = array();
		foreach ( $data2 as $field => $value ) {
			$conditions[] = "[$field] = " . $value['format'];
		}
		$conditions = implode( ' AND ', $conditions );
		
		//get the primary key value, if the records exists
		$select = 'select $keyName from $table $conditions';
		this->query($select);
		
		if (this->last_result === null) {
		   //INSERT CASE, HANDLED BELOW
		} else {
			//found a record, so get the key value then
			//do UPDATE with original values + where condition				
			$keyValue = this->last_result[0]->$keyName; 
			$where = array($keyName, $keyValue);
			return update($table, $data, $where, $format);
	   }
	}
	//INSERT
	$formats = $values = array();
	foreach ( $data2 as $value ) {
		$formats[] = $value['format'];
		$values[]  = $value['value'];
	}

	$fields  = '[' . implode( '], [', array_keys( $data ) ) . ']';
	$formats = implode( ', ', $formats );

	$sql = "$type INTO [$table] ($fields) VALUES ($formats)";

	$this->check_current_query = false;
	return $this->query( $this->prepare( $sql, $values ) );
}`

It's not perfect because it doesn't handle complex keys, but something like that should get the job done.  I don't have a test server set up at the moment, so maybe one of you guys can peek at this and see if it passes muster.  A little more code and we could grab all the key cols, ordered correctly, and use that in the where, but I'm out of time for today.

Thoughts?

**Comment by erikest** [comment]
Looking at my post, I realize I left out the column specs, so I edited the original, but here's a complete one:

`REPLACE INTO [wp_woocommerce_sessions] ([session_key], [session_value], [session_expiry]) VALUES ('390', 'a:18:{s:4:"cart";s:6:"a:0:{}";s:15:"applied_coupons";s:6:"a:0:{}";s:23:"coupon_discount_amounts";s:6:"a:0:{}";s:27:"coupon_discount_tax_amounts";s:6:"a:0:{}";s:21:"removed_cart_contents";s:6:"a:0:{}";s:19:"cart_contents_total";i:0;s:5:"total";i:0;s:8:"subtotal";i:0;s:15:"subtotal_ex_tax";i:0;s:9:"tax_total";i:0;s:5:"taxes";s:6:"a:0:{}";s:14:"shipping_taxes";s:6:"a:0:{}";s:13:"discount_cart";i:0;s:17:"discount_cart_tax";i:0;s:14:"shipping_total";i:0;s:18:"shipping_tax_total";i:0;s:9:"fee_total";i:0;s:4:"fees";s:6:"a:0:{}";}', 1466614807)`

And thank you for turning my attention there, because I also discovered some other Symposium related quey problems that I'll need to add to translate...

**Comment by erikest** [comment]
I'm setting up my dev/staging environments today, so I can test my proposed method of handling upserts.  If you see any issues with the concept, please let me know :)

**Comment by KY4U** [comment]
Another possible solution would be a slight variation to the translate_if_not_exists_insert_merge() function in the translations.php file.  The idea behind it would be to translate REPLACE INTO with MERGE.  I can knock that out for you if you find issues with your concept.

**Comment by erikest** [comment]
Okay, that function looks like something that was added since the last time I updated my repo.

Ya MERGE would work, in fact it would work just fine as a refactor of $wpdb->replace, instead of my multi step approach.  I could rewrite what I'm doing to just execute a merge query, which I guess would be a little safer in general, especially if I wrap it in a transaction.  Which leaves me wondering what is the general pattern for projectnami?   Is the intention to rework the api functions so that they generate compliant sql or is it to catch non-compliant sql and just translate everything using string operations in translations.php?  It seems like we would want $wpdb->replace to be refactored to never generate REPLACE INTO statements, since that would be a little faster and moves $wpdb to being more mssql native.  Is the problem merging changes from WP's main branch back into ProjectNami?  Is it better to be in translations.php to be more general, so even those bad plugins which are skirting the apis will have the query caught and translated?  I see arguments for both.  Maybe both places is the correct answer: give the api the correct way of handling an upsert _and_ catch REPLACE INTO in translations.php for the naughty plugins...

**Comment by patrickebates** [comment]
When the issue is in WP Core, then fix it to generate proper SQL Server syntax.  For plugins and themes, we deal with them using the translations.  The goal is to have everything native to WP working native with SQL Server.

So yes, this needs to be handled directly in '$wpdb->replace'.  Apparently we hadn't encountered anything using this function in this manner yet.

**Comment by erikest** [comment]
Okay cool.  I'll refactor my code then to use @KY4U's suggestion of MERGE, since this mapping seems to be a better fit: REPLACE INTO -> MERGE.
