### ISSUE TITLE
Theme upload failing around 98%

### ISSUE THREAD

**Issue by marketvision-john** [ProjectNami/projectnami#106]
When uploading Themeforest Salient 7.0 WP fails on upload right around 98% and then displays an blank popup with only "Are you sure you want to do this?"  and no button to confirm. also displays a link that shows "Please try again" which brings you back to Themes

Salient Theme:
http://themeforest.net/item/salient-responsive-multipurpose-theme/4363266

Any ideas would be much appreciated !

btw...great work

**Comment by patrickebates** [comment]
Are you running on Azure Web App?  If so, how long does the upload take?  Azure Web Apps kills HTTP connections after about 120 to 180 seconds.  You may need to connect to the site via FTP or similar (WebMatrix for example) and upload that way.

**Comment by marketvision-john** [comment]
Thanks for the quick reply...takes less than a minute.

**Comment by marketvision-john** [comment]
about 9 seconds

**Comment by patrickebates** [comment]
Anything in the php_error log that might indicate a problem?

**Comment by marketvision-john** [comment]
Hello again,  We were able to solve this by uploading the theme manually via ftp.  We did not see any errors in the log that would help.  Thank you for responding so promptly.  Very impressive !
