### ISSUE TITLE
"Warning: mysql_num_fields(): supplied resource is not a valid MySQL result resource in D:\home\site\wwwroot\wp-includes\wp-db.php on line 3021"

### ISSUE THREAD

**Issue by planetburns** [ProjectNami/projectnami#108]
We have the following issue which is preventing us from going live. Any help or suggestions please?

Thanks

James Burns

**Comment by Angelixion** [comment]
#71 https://github.com/ProjectNami/projectnami/issues/71#issuecomment-220542308

**Comment by patrickebates** [comment]
Any idea what plugin or theme function might be calling this?  I'd like to understand what is going on before we blindly try to update `load_col_info()`

**Comment by planetburns** [comment]
We are using a theme called 'Newspaper'.


We went through all the plug-ins one by one, and W3 Total Cache was causing the issue. We've turned it off and have asked them for any know issues.


The site, with the W3 Total Cache plugin, works fine with a MySQL backend, but that's not what we want to use [😉]


This is the site... https://jnwp.azurewebsites.net/


Thanks


James


________________________________

**Comment by patrickebates** [comment]
Thanks, I'll download a fresh copy of W3TC and see what's going on.  I know others have used it successfully, so I wonder if this is a recent change or a function that no one tried to use yet with PN.

In the meantime, if full-page caching is your goal with W3TC, you might want to have a look at our Blob Cache.
http://projectnami.org/blob-cache/

**Comment by planetburns** [comment]
Thanks


Appreciate your help.


Brian - look at this... http://projectnami.org/blob-cache/


________________________________

**Comment by Angelixion** [comment]
For me is the same plugin W3TC

**Comment by patrickebates** [comment]
Looks like the closest thing to the underlying calls is `sqlsrv_field_metadata` but I doubt it returns anything as expected.  Still haven't been able to nail down exactly how this is being used in W3TC either.

Also, here's a prime example of Blob Cache at work
http://easyhealthoptions.com

**Comment by patrickebates** [comment]
While I'm waiting to hear back about some questions I have regarding the SqlSrv driver and how it relates to this issue, I'd like to learn a bit more about what might be triggering the error and the code that is calling it.

Is there a specific feature of W3TC which might be producing this error?  By any chance were either/both of you attempting to cache DB result sets?

**Comment by patrickebates** [comment]
Pushed commits to Master today that I believe will solve this issue.  Please let me know how it goes.

**Comment by guidooliveira** [comment]
i'm still getting this warning even with the latest sync in the master branch:

Warning: mysql_num_fields(): supplied resource is not a valid MySQL result resource in D:\home\site\wwwroot\wp-includes\wp-db.php on line 3035 Warning: mysql_num_fields(): supplied resource is not a valid MySQL result resource in D:\home\site\wwwroot\wp-includes\wp-db.php on line 3035
