### ISSUE TITLE
Any Japanese and Chinese characters all showing "???" right after click "Publish" button

### ISSUE THREAD

**Issue by Ronnie-K** [ProjectNami/projectnami#11]
English and numbers are totally fine. And, if localize WordPress by install a language pack, those Chinese characters came from the language pack, all displayed normally.

But, when try to post a new article, fill the title & content filed with any random Chinese characters or Kanji or Katakana or hiragana. Then click post, don't need even leave the page, things filled before all turning question marks. (Using Wikipedia left side bar language switcher can easily find those foreign characters.)

I would really like to offer more details, and do some further testing.

But first, do you have this issue too? Maybe it's better if we first try to see if it's I did something wrong myself here, or it's the project need to do some corresponding revises.

Thanks.

(Sorry clicked "Fork" button then deleted the fork, I just wanna see all the forked versions of Project Nami.)

**Comment by patrickebates** [comment]
I think we may have an answer.  In Issue #17 you will see that I tested trying to save Greek characters and was finally successful by setting the collation in the database to a code page which supported Greek.

The answer should be to select an appropriate code page for the collation type at the time you provision your database.

**Comment by patrickebates** [comment]
Any additional feedback after the recommendation to set the collation?  An option to set this has been added to the Deploy To Azure script.

If there is no additional comment in a few days, I will close this issue.
