### ISSUE TITLE
Change wp-admin url

### ISSUE THREAD

**Issue by tuczap** [ProjectNami/projectnami#110]
Hi,
I know there are plugins that change wp-admin url of your wordpress site (www.domain.com/wp-admin to eg www.domain.com/mycustom) but they don't work with Wordpress on Project Nami simply because they all base on .htaccess and it is missing in Project Nami. Does anyone know of other ways to change default wp-admin url to something custom?

**Comment by patrickebates** [comment]
What you describe would be a problem for a pure WP install running in IIS as well.  Are there any plugins for this which work with Windows / IIS ?
