### ISSUE TITLE
How to change SQLAzure database from a site

### ISSUE THREAD

**Issue by yporrasv** [ProjectNami/projectnami#111]
Hi there,
I deployed a Wordpress with NAMI and I am using a demo SQL Azure database. I am trying to connect wordpress to another SQL Azure database so I changed wp-config.php but this is not enough. Could you tell me what I need to change to access another database?

**Comment by patrickebates** [comment]
I suspect you used the Deploy To Azure script.  In order for everything to work correctly, we had to store the DB settings in two locations -- wp-config.php and the App Settings of the Web App in the Azure portal.

**Comment by yporrasv** [comment]
Thanks Patrick for your help. The information on the App Settings was not updated as you suggested. The thing is that I changed that information in the App Settings as well (from the Azure Portal) but it is still connecting to the old database. Am I supposed to stop the service and restart it?

**Comment by patrickebates** [comment]
Change it in both App Settings and wp-config.php and that should be all.  Restarting the site won't hurt though.
