### ISSUE TITLE
Upgrade to latest version

### ISSUE THREAD

**Issue by 4c74356b41** [ProjectNami/projectnami#112]
Hello, could you please create a document covering basic steps to update Project Nami to latest version without losing any of the content and\or customizations? Thanks

**Comment by patrickebates** [comment]
Only reason we haven't done so is that the rules that apply to WordPress (except for the built-in updater, for now) also apply to Project Nami.

For example, you can download the ZIP file of the latest build, unpack it, and simply copy it over your existing deployment.  This is essentially what the WP updater does behind the scenes.  Only if you modified one of the included default themes would you experience any loss.

If you are running on Azure Web Apps, you can use the built-in Continuous Deployment tools to update your site.  If you used our Deploy to Azure button, then from the Azure portal for your Web App you will find a Sync button in the Continuous Deployment settings.  If you deployed manually, you can still configure Continuous Deployment for this purpose.

More details about the Continuous Deployment options can be found in this tutorial video.
http://projectnami.org/video-updating-project-nami/

**Comment by 4c74356b41** [comment]
Thanks, I think I've deployed with "Deploy to Azure" but it was long time ago, so I'm not sure. I will backup my DB and test this. Thank you!

I think you should include what you just outlined here, because I was kinda afraid to take any action with next to zero information. Thanks!
