### ISSUE TITLE
woocommerce_api_keys - Table does not exist

### ISSUE THREAD

**Issue by chanaka1** [ProjectNami/projectnami#113]
After i install the plugin woocommerce and check the status i see that woocommerce_api_keys table is not created. 

This is created in the normal WordPress site using Mysql 
![image](https://cloud.githubusercontent.com/assets/1998968/16943774/188ea068-4dbb-11e6-81ad-7bc9eee1cf13.png)

**Comment by patrickebates** [comment]
Do you have any data from translate.log related to this query?  This file can be found in the same location at php_error.log

**Comment by patrickebates** [comment]
As a quick fix, you can try executing this SQL statement in your database.

CREATE TABLE wp_woocommerce_api_keys (
  key_id int NOT NULL identity(1,1),
  user_id int NOT NULL,
  description nvarchar(max) NULL,
  permissions nvarchar(10) NOT NULL,
  consumer_key nvarchar(64) NOT NULL,
  consumer_secret nvarchar(43) NOT NULL,
  nonces nvarchar(max) NULL,
  truncated_key nvarchar(7) NOT NULL,
  last_access datetime2 NULL default null,
  constraint wp_woocommerce_api_keys_PK PRIMARY KEY (key_id)
)
GO
CREATE INDEX wp_woocommerce_api_keys_IDX1 on wp_woocommerce_api_keys (consumer_key)
GO
CREATE INDEX wp_woocommerce_api_keys_IDX2 on wp_woocommerce_api_keys (consumer_secret)
GO

**Comment by chanaka1** [comment]
Hi patrickebates, 
i count find a translate.log but here is the php_error.log
[php_errors.txt](https://github.com/ProjectNami/projectnami/files/372174/php_errors.txt)

**Comment by patrickebates** [comment]
Looks like the adjustments to the CREATE TABLE statement for woocommerce_api_keys failed completely, but the other tables worked.  I will try to investigate.  In the meantime, I suspect the query above will let you move forward a bit.

**Comment by chanaka1** [comment]
hopefully .. Thanks. let me know the process.
