### ISSUE TITLE
BlobCache plugin integration with azure CDN

### ISSUE THREAD

**Issue by guidooliveira** [ProjectNami/projectnami#116]
Might be off the area, but i'd love to see the nami cache plugin be integrated with the Azure CDN as i use W3 Total Cache for this purpose. I'd be lovely to see some minification features and image compression.

**Comment by patrickebates** [comment]
Right now, the Blob Cache platform is intended more as a very intelligent replacement for the Enhanced Disk page cache option in W3TC, as that doesn't work with IIS anyway.  We've knocked around the idea of doing more, but the other plugins out there seem to already do a good job with those features.

**Comment by guidooliveira** [comment]
i couldn't manage to get the blob plugin on my site, but i'd really love to try it out, due to it's performance

**Comment by patrickebates** [comment]
Not sure I understand.  You had issues trying to get the plugin and the IIS module working on your site?

**Comment by guidooliveira** [comment]
i'm running my site on azure in a S1 app instance and the DB in a S0 instance. The site stops responding after a enable the plugin for some reason,  i might have to create a deployment slot to test out the behaviour. Can you provide me a link with more complete intructions on how to fully configure the solution?

**Comment by patrickebates** [comment]
The instructions within the ZIP package on our site are pretty complete, but I'm happy to walk you through the setup.
https://projectnami.blob.core.windows.net/cache/project-nami-blob-cache-3.0.1.zip

To begin, we need to get the IIS Module operating without the plugin activated within the site.  First, you need to create three entries in the App Settings of your Web App using values from a Storage account in the same data center.

	ProjectNamiBlobCache.StorageAccount		<your storage account name>
	ProjectNamiBlobCache.StorageKey			<your storage account Primary Access Key>
	ProjectNamiBlobCache.StorageContainer	<your cache container in your storage account>

Next, using an FTP client, WebMatrix, or similar, you need to upload the `bin` folder contained in the ZIP to the wwwroot folder of your site.  This should give you at least four folders at that level: bin, wp-admin, wp-content, and wp-includes.

Finally, you need to add the Modules section to the web.config of your site.  This section goes inside of system.webServer.  I'm attaching a sample web.config with the Modules section present.

Once all of these are in place, your site should still be operating, but nothing being written to the cache yet.

[Web.config.txt](https://github.com/ProjectNami/projectnami/files/379320/Web.config.txt)

**Comment by guidooliveira** [comment]
i'll try it out now, thank you

**Comment by guidooliveira** [comment]
this should work without the webjobs right? or they improve even more the performance?

**Comment by patrickebates** [comment]
One WebJob keeps costs down by cleaning up expired objects from the cache (BlobCacheCleanup) while the other one improves performance by preloading the cache (BlobCacheLoader).

**Comment by guidooliveira** [comment]
my website is currently down, but i'm debbuging it, here's my Web.config current configurations
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <modules>
            <add name="ProjectNamiBlobCache" type="ProjectNamiBlobCache.CacheFrontEnd" />
        </modules>
        <staticContent>
            <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00"/>
            <mimeMap fileExtension=".svg" mimeType="image/svg+xml"/>
            <mimeMap fileExtension=".eot" mimeType="application/vnd.ms-fontobject"/>
            <mimeMap fileExtension=".woff" mimeType="application/x-woff"/>
            <mimeMap fileExtension=".woff" mimeType="application/x-font-woff"/>
            <mimeMap fileExtension=".woff2" mimeType="application/x-font-woff"/>
        </staticContent>
        <urlCompression doStaticCompression="true" doDynamicCompression="true"/>
        <httpCompression directory="%SystemDrive%\inetpub\temp\IIS Temporary Compressed Files">
            <scheme name="gzip" dll="%Windir%\system32\inetsrv\gzip.dll"/>
            <dynamicTypes>
                <add mimeType="text/*" enabled="true"/>
                <add mimeType="message/*" enabled="true"/>
                <add mimeType="application/javascript" enabled="true"/>
                <add mimeType="application/x-javascript" enabled="true"/>
                <add mimeType="*/*" enabled="false"/>
            </dynamicTypes>
            <staticTypes>
                <add mimeType="text/*" enabled="true"/>
                <add mimeType="message/*" enabled="true"/>
                <add mimeType="application/javascript" enabled="true"/>
                <add mimeType="application/x-javascript" enabled="true"/>
                <add mimeType="*/*" enabled="false"/>
            </staticTypes>
        </httpCompression>
        <rewrite>
            <rules>
                <rules>
                    <rule name="WordPress Rule 1" stopProcessing="true">
                        <match url="^index\.php$" ignoreCase="false" />
                        <action type="None" />
                    </rule>
                    <rule name="WordPress Rule 2" stopProcessing="true">
                        <match url="^([_0-9a-zA-Z-]+/)?files/(.+)" ignoreCase="false" />
                        <action type="Rewrite" url="wp-includes/ms-files.php?file={R:2}" appendQueryString="false" />
                    </rule>
                    <rule name="WordPress Rule 3" stopProcessing="true">
                        <match url="^([_0-9a-zA-Z-]+/)?wp-admin$" ignoreCase="false" />
                        <action type="Redirect" url="{R:1}wp-admin/" redirectType="Permanent" />
                    </rule>
                    <rule name="WordPress Rule 4" stopProcessing="true">
                        <match url="^" ignoreCase="false" />
                        <conditions logicalGrouping="MatchAny">
                            <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" />
                            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" />
                        </conditions>
                        <action type="None" />
                    </rule>
                    <rule name="WordPress Rule 5" stopProcessing="true">
                        <match url="(^[_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*)" ignoreCase="false" />
                        <action type="Rewrite" url="{R:2}" />
                    </rule>
                    <rule name="WordPress Rule 6" stopProcessing="true">
                        <match url="^([_0-9a-zA-Z-]+/)?(.*\.php)$" ignoreCase="false" />
                        <action type="Rewrite" url="{R:2}" />
                    </rule>
                    <rule name="WordPress Rule 7" stopProcessing="true">
                        <match url="." ignoreCase="false" />
                        <action type="Rewrite" url="index.php" />
                    </rule>
                    <rule name="Redirect to https">
                        <match url="(.*)"/>
                        <conditions>
                            <add input="{HTTPS}" pattern="Off"/>
                            <add input="{REQUEST_METHOD}" pattern="^get$|^head$"/>
                        </conditions>
                        <action type="Redirect" url="https://{HTTP_HOST}/{R:1}"/>
                    </rule>
                </rules>
            </rewrite>
            <validation validateIntegratedModeConfiguration="false"/>
            <modules>
                <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler"/>
            </modules>
        </system.webServer>
        <system.web>
            <httpModules>
                <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web"/>
            </httpModules>
        </system.web>
    </configuration>`

**Comment by patrickebates** [comment]
I see your problem.  You already have a Modules section at the bottom of the file.  You can't declare it twice.  You need to move the Blob Cache line into that other section.

**Comment by patrickebates** [comment]
` <modules>
 <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler"/>
 </modules>
`

**Comment by guidooliveira** [comment]
like this?

`
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <modules>
            <add name="ProjectNamiBlobCache" type="ProjectNamiBlobCache.CacheFrontEnd" />
            <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler"/>
        </modules>
        <staticContent>
            <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00"/>
            <mimeMap fileExtension=".svg" mimeType="image/svg+xml"/>
            <mimeMap fileExtension=".eot" mimeType="application/vnd.ms-fontobject"/>
            <mimeMap fileExtension=".woff" mimeType="application/x-woff"/>
            <mimeMap fileExtension=".woff" mimeType="application/x-font-woff"/>
            <mimeMap fileExtension=".woff2" mimeType="application/x-font-woff"/>
        </staticContent>
        <urlCompression doStaticCompression="true" doDynamicCompression="true"/>
        <httpCompression directory="%SystemDrive%\inetpub\temp\IIS Temporary Compressed Files">
            <scheme name="gzip" dll="%Windir%\system32\inetsrv\gzip.dll"/>
            <dynamicTypes>
                <add mimeType="text/*" enabled="true"/>
                <add mimeType="message/*" enabled="true"/>
                <add mimeType="application/javascript" enabled="true"/>
                <add mimeType="application/x-javascript" enabled="true"/>
                <add mimeType="*/*" enabled="false"/>
            </dynamicTypes>
            <staticTypes>
                <add mimeType="text/*" enabled="true"/>
                <add mimeType="message/*" enabled="true"/>
                <add mimeType="application/javascript" enabled="true"/>
                <add mimeType="application/x-javascript" enabled="true"/>
                <add mimeType="*/*" enabled="false"/>
            </staticTypes>
        </httpCompression>
        <rewrite>
            <rules>
                <rules>
                    <rule name="WordPress Rule 1" stopProcessing="true">
                        <match url="^index\.php$" ignoreCase="false" />
                        <action type="None" />
                    </rule>
                    <rule name="WordPress Rule 2" stopProcessing="true">
                        <match url="^([_0-9a-zA-Z-]+/)?files/(.+)" ignoreCase="false" />
                        <action type="Rewrite" url="wp-includes/ms-files.php?file={R:2}" appendQueryString="false" />
                    </rule>
                    <rule name="WordPress Rule 3" stopProcessing="true">
                        <match url="^([_0-9a-zA-Z-]+/)?wp-admin$" ignoreCase="false" />
                        <action type="Redirect" url="{R:1}wp-admin/" redirectType="Permanent" />
                    </rule>
                    <rule name="WordPress Rule 4" stopProcessing="true">
                        <match url="^" ignoreCase="false" />
                        <conditions logicalGrouping="MatchAny">
                            <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" />
                            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" />
                        </conditions>
                        <action type="None" />
                    </rule>
                    <rule name="WordPress Rule 5" stopProcessing="true">
                        <match url="(^[_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*)" ignoreCase="false" />
                        <action type="Rewrite" url="{R:2}" />
                    </rule>
                    <rule name="WordPress Rule 6" stopProcessing="true">
                        <match url="^([_0-9a-zA-Z-]+/)?(.*\.php)$" ignoreCase="false" />
                        <action type="Rewrite" url="{R:2}" />
                    </rule>
                    <rule name="WordPress Rule 7" stopProcessing="true">
                        <match url="." ignoreCase="false" />
                        <action type="Rewrite" url="index.php" />
                    </rule>
                    <rule name="Redirect to https">
                        <match url="(.*)"/>
                        <conditions>
                            <add input="{HTTPS}" pattern="Off"/>
                            <add input="{REQUEST_METHOD}" pattern="^get$|^head$"/>
                        </conditions>
                        <action type="Redirect" url="https://{HTTP_HOST}/{R:1}"/>
                    </rule>
                </rules>
            </rewrite>
            <validation validateIntegratedModeConfiguration="false"/>
        </system.webServer>
        <system.web>
            <httpModules>
                <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web"/>
            </httpModules>
        </system.web>
    </configuration>
`

**Comment by patrickebates** [comment]
Yes, that should work as well.

**Comment by guidooliveira** [comment]
for some reason, kudu says the tags don't match...

**Comment by patrickebates** [comment]
What if you simply remove the Blob Cache line?  Does the site return to operating normally?

**Comment by patrickebates** [comment]
I found an error with the last full copy of the file you included above.  the `rules` tag is opened twice.

` </httpCompression>
 <rewrite>
 <rules>
 <rules>
`

**Comment by guidooliveira** [comment]
i changed that and now i'm getting 

The page cannot be displayed because an internal server error has occurred.

URL: https://guidooliveira.com/

**Comment by patrickebates** [comment]
I suspect you had an existing bin folder with the module for app insights?  Did you add the three files from the Blob Cache bin folder alongside it?

**Comment by guidooliveira** [comment]
the Application Insights one is in the folder:
D:\home\site\wwwroot\App_Data\packages

in D:\home\site\wwwroot\bin, there are only 3 DLLs for the plugin, which were in the zip

**Comment by patrickebates** [comment]
if you remove the blob cache line, does the site return?

**Comment by patrickebates** [comment]
What version of the .Net framework is enabled for your Web App?

**Comment by guidooliveira** [comment]
.net version is 4.6
php: 5.6
Java: off
python: off
Platform: 64-bit
Web sockets: off
Always On: on
Managed Pipeline: Integrated
ARR Affinity: On

**Comment by patrickebates** [comment]
That should be fine.  Just needed to confirm that .Net 4.6 was set.

Anything in eventlog.xml that might help explain the 500 errors?

**Comment by guidooliveira** [comment]
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

Detailed Error Information:
Module	   IIS Web Core
Notification	   Unknown
Handler	   Not yet determined
Error Code	   0x8007000d
Config Error	   
Config File	   \\?\D:\home\site\wwwroot\web.config
Requested URL	   http://guidooliveira:80/favicon.ico
Physical Path	   
Logon Method	   Not yet determined
Logon User	   Not yet determined

**Comment by patrickebates** [comment]
Only idea I have is a possible conflict between Blob Cache and App Insights.  I'll have to test with that to see what might be going on.

**Comment by guidooliveira** [comment]
i removed all the App insights binaries and keep looking at the errors, i'll let you know if something new comes up

**Comment by patrickebates** [comment]
the errors go away as soon as you remove the line for Blob Cache, correct?

**Comment by guidooliveira** [comment]
just got an wierd error, on page load, i'm getting error 500 to load the favicon.ico file..

the error persists even after removing the blob cache, maybe because i've also removed the w3 total cache plugin.

**Comment by patrickebates** [comment]
I guess try removing the bin folder

**Comment by patrickebates** [comment]
and I can't imagine how W3TC could be impacting the site at this level

**Comment by guidooliveira** [comment]
i'm currently trying to restore the backup and i'll try to work with the errors in a different stage

**Comment by guidooliveira** [comment]
ok, backup is restored and the website is back online, i'll  try to understand wtf happened because i really want to try out this plugin :)

**Comment by guidooliveira** [comment]
Hi patrick, sorry it took so long i was in the hospital. So i've created a testing deployment slot for testing and i did the following steps:

uninstalled unnecessary plugins
uninstalled W3 Total Cache and removed all it's files
Enabled the Blob Cache Plugin

So far the website is still working,

As soon as i change the web.config file to load the modules the php-cgi.exe processes won't load.

no errors are displayed, all of the necessary settings are correctly configured in the Application Settings

not sure why by even comenting out the module settings in the web.config the website doesn't load because the process php-gci.exe does not load.

**Comment by patrickebates** [comment]
When using the Integrated Pipeline, everything at the ASP.Net level has to start up first before the connection is handed off to PHP.  Is App Insights still installed?  Starting to wonder if both modules share dependencies and this is a sign of some sort of conflict.

Might be worth having a look at EventLog.xml in the LogFiles folder of the site.  I use an FTP client to access those files, though you might get to it through Kudu as well.

**Comment by guidooliveira** [comment]
App Insights isn't installed anymore, here's the even't log:

[eventlog.zip](https://github.com/ProjectNami/projectnami/files/400640/eventlog.zip)


php_error.txt isn't there because php wasn't initiated.

**Comment by patrickebates** [comment]
Don't see anything except for this
`ErrorMessage=Could not find file 'E:\'.`

**Comment by guidooliveira** [comment]
yea, anywhere...don't know why the php executable won't start

**Comment by patrickebates** [comment]
If anything in web.config is failing to load, PHP will never start.  Only time I have seen this before is when the bin folder was either misplaced or missing some of the dependencies for Blob Cache, but we eliminated that as an issue two weeks ago.

**Comment by guidooliveira** [comment]
here's the web.config on the stage:

[web.config.zip](https://github.com/ProjectNami/projectnami/files/400675/web.config.zip)

regarding dependencies, i've seen only 3 files in the bin folder is that correct?

**Comment by patrickebates** [comment]
Oh, are you indicating that you can't get PHP to start even with Blob Cache disabled?  I suspect that's because you have the second Modules section at the bottom which is attempting to load App Insights, which I think you mentioned was no longer installed.

**Comment by patrickebates** [comment]
And yes, there are three files in the Bin folder for Blob Cache

**Comment by guidooliveira** [comment]
it's not i've removed the binaries

**Comment by patrickebates** [comment]
You could try the attached web.config, provided that you still have the Bin folder present
[web.zip](https://github.com/ProjectNami/projectnami/files/400687/web.zip)

**Comment by guidooliveira** [comment]
i've tried it but without success

**Comment by patrickebates** [comment]
I'm almost out of ideas, so let's get back to basics.  Here's a stripped down web.config that might give us some insight.
[web.zip](https://github.com/ProjectNami/projectnami/files/400693/web.zip)

**Comment by guidooliveira** [comment]
in verbose i see this message in the Detailed errors:

Config Source:
 
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

**Comment by patrickebates** [comment]
Might need to eliminate that blank line at the top of the file

**Comment by guidooliveira** [comment]
that was it! can't believe THAT was the issue!

https://guidooliveira-test.azurewebsites.net/ 

now i'll configure the webjobs and test the plugin

thank you patrick!

**Comment by guidooliveira** [comment]
now crawling :)

**Comment by patrickebates** [comment]
I'd like to hear your thoughts on performance first, if you wouldn't mind.  Should probably also discuss cache durations as well.

For example, on projectnami.org we have Cache Expiration set for 15300 seconds (4.25 hours) and the Cache Loader web job runs every two hours.  In the event that you edit a page or post while it is in the cache, the plugin proactively purges that page so it will be rebuilt on the next access attempt.

Also, as you have probably already found out, you can't receive any page cache hits if you are logged into the site.  Best to use a different browser or Private/Incognito window.

**Comment by guidooliveira** [comment]
it wasn't with the defaults, but i changed the Cache Expiration as you've mentioned and seems to be a lot faster than w3 Total Cache, even though i'm getting some invalid jquery errors, i understand this has absolutely nothing to do with the puglin.
What to you suggest i do to make it faster? This is a blog that i post like 4 times a month.

**Comment by patrickebates** [comment]
You could look at setting the cache expiration to something like 24.5 hours and have the cache loader run once a day.  You can also continue to use W3TC just without any of the full page caching features.

Blob Cache is intended to make a site run faster for the public.  The only impact it has on the owner or the users is from freeing up resources so the site runs smoother.

**Comment by guidooliveira** [comment]
So if i use W3 Total Cache only for CDN, it should serve the cache through the CDN is that correct?

**Comment by patrickebates** [comment]
No, I don't think so.  I may have misunderstood some of your goals.

Blob Cache currently serves cached page output at the server itself; it doesn't write it to a CDN for serving there.  If you have a plugin which writes things like Media to a CDN, those will continue to be served from there.  But we don't offer any integration with Cloudfront or similar.

But perhaps you can help me understand something.  When using a CDN in that manner, are you still able to access a public page on the site while logged in and have access to your Admin bar and related tools?  I understand being able to access /wp-admin as that folder wouldn't be cached.  This is one of the main reasons Blob Cache functions the way it does, to allow logged in users to still access the site as they would expect.

**Comment by guidooliveira** [comment]
When using W3 Total Cache with Azure CDN, essentially you upload your wp-content folder to a storage account, the CDN Service then "fetches" the content from the storage account, W3 Total Cache also rewrites the calls so that you get a nice looking URL. The CDN then serves the content from the endpoint with the lowest latency.

/wp-admin is served directly from the web app and works as usual
