### ISSUE TITLE
Warning:mysql_num_fields(): Won't go away

### ISSUE THREAD

**Issue by guidooliveira** [ProjectNami/projectnami#117]
Warning:mysql_num_fields(): supplied resource is not a valid MySQL result resource in D:\home\site\wwwroot\wp-includes\wp-db.php on line 3035 Warning: mysql_num_fields(): supplied resource is not a valid MySQL result resource in D:\home\site\wwwroot\wp-includes\wp-db.php on line 3035

using php 5.6, .net framework 4.6 enabled and using x64 bit version

related issues: #108 #71

**Comment by patrickebates** [comment]
This was updated in Master branch, but we connect those who use Deploy To Azure to our Latest branch as a way of shielding them from hotfixes until they are fully tested.  Have you downloaded the updated file from Master to test with your installation?

**Comment by guidooliveira** [comment]
I've deployed it from Master branch

**Comment by patrickebates** [comment]
Then I'm really confused, as my copy of the Master branch does not contain any references to MySQL_num_fields

How did you deploy from the Master branch?  If you used the Deploy To Azure button found in the readme there, you are receiving the Latest branch.  If you did a manual deploy of the Master branch using the Continuous Deployment option in the Azure portal, then you should be seeing the updated file.

**Comment by guidooliveira** [comment]
I guess something wierd was going on with azure, i've sent a sync request and this issue has aparently been resolved, which makes me really satisfied :+1:  

thank you!
