### ISSUE TITLE
Wootheme our-team plugin - Query NOT translated due to non-defined error code

### ISSUE THREAD

**Issue by dpsjallen** [ProjectNami/projectnami#120]
Hi we have a site that uses the wootheme our-team plugin - https://docs.woocommerce.com/documentation/plugins/our-team/

They have a GitHub repository of the code here - https://github.com/woothemes/our-team/

When we execute the page with the shortcode on it we get the following error:

2016-08-03 19:49:10 Error Code: 169 -- Query NOT translated due to non-defined error code.
```
SELECT DISTINCT wp_posts.* , wp_posts.menu_order FROM wp_posts  INNER JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) WHERE 1=1  AND ( 
  wp_term_relationships.term_taxonomy_id IN (4)
) AND wp_posts.post_type = 'team-member' AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.menu_order, wp_posts.menu_order DESC OFFSET  0 ROWS FETCH NEXT 120 ROWS ONLY

Thanks,
Josh

**Comment by patrickebates** [comment]
The problem is menu_order listed twice in the ORDER BY clause.  Wondering if that is the fault of the plugin itself (and something that MySQL will tolerate) or something unexpected in the WP APIs.

**Comment by patrickebates** [comment]
What happens if you select a different `ORDER BY` option?  Same thing, but with the other field listed twice this time?

**Comment by dpsjallen** [comment]
Patrick,

Thanks for looking at something so menial.  This query works in SQL Management studio, when I remove the first reference to wp_posts.menu_order after the ORDER BY

```
SELECT DISTINCT wp_posts.* , wp_posts.menu_order FROM wp_posts  INNER JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) WHERE 1=1  AND ( 
  wp_term_relationships.term_taxonomy_id IN (4)
) AND wp_posts.post_type = 'team-member' AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.menu_order DESC OFFSET  0 ROWS FETCH NEXT 120 ROWS ONLY 
```

Now I just have to find where it is in the plugin.

**Comment by patrickebates** [comment]
I'm wondering if the issue is in `shortcode_atts` which is a Core function.  Is there a way to generate this other than using the plugin, and if so does it work properly?

There are several places in the plugin where a default `ORDER BY` is set for `menu_order` but I think that somewhere the array checks are appending values rather than overriding them.

What if you simply don't pass in the `ORDER BY` from the shortcode?  Does the default take over and only insert it once into the query?

**Comment by dpsjallen** [comment]
So that is interesting.  The shortcode from the plugin on my stand alone test page is just:
`[woothemes_our_team limit="120" size="150" per_row="4" category="4"]`

When I add the orderby="none" parameter it displays with no problem

`[woothemes_our_team limit="120" size="150" per_row="4" category="4" orderby="none"]`

The larger fix was disabling the Post Types Order plugin installed on this site which looks like it even causes issues with a normal Wordpress install - https://wordpress.org/support/topic/wp_query-is-ignoring-orderby-and-order

After I disabled plugin the original shortcode renderer with no issue.

Thanks.
Josh

**Comment by patrickebates** [comment]
Post ordering was reworked not too long ago in WP Core, so it might be that the other plugin hasn't been properly updated.
