### ISSUE TITLE
Issues converting from mysql to mssql

### ISSUE THREAD

**Issue by khannar62** [ProjectNami/projectnami#121]
Hi,
I use Gravity Forms to save entries, I believe it wont work with nami as they do different coding algorithms that nami doesnt support.

My Question is what form tool would you recommend, I need to be able to do php coding in the back end to modify these forms as well

**Comment by patrickebates** [comment]
Do you have an example of what you think won't work?  Might be something the translation layer could handle.

**Comment by khannar62** [comment]
Gravity Forms has an API called GFAPI and it pulls data from tables I believe, and it doesnt return any records when looking through the entries. It is also not letting me update it, the error is 

Update Failed: Current database user does not have necessary permissions to create tables. Gravity Forms requires that the database user has CREATE and ALTER permissions. If you need assistance in changing database user permissions, contact your hosting provider.

After talking with Microsoft, i figured out this is because of the MySql -> MsSql

I found the same issue from this article

http://support.projectnami.org/viewtopic.php?t=82

**Comment by patrickebates** [comment]
Oh, it's a premium plugin too.  That explains why we never took a strong look at it.

Yes, as that old post of mine reads, we don't yet have a way to handle the multiple syntax options of CREATE TABLE statements using MySQL syntax.  We can handle the ones that match the syntax used within vanilla WordPress, but that's it for the moment.  I have some ideas, but that's one of about six new initiatives for PN that we're juggling right now.

**Comment by khannar62** [comment]
Ok Awesome, I would love to find out when this feature is available. I much rather prefer SQL than MySQL

**Comment by khannar62** [comment]
Also is there another form generator you would recommend other than gravity forms

**Comment by aledoy** [comment]
Contact Us plug-in works (by EON MEdia Group, v1.6), but I need a log within the admin page to see users that have posted entries on the form. Are there other alternatives?

**Comment by dulfe** [comment]
I just found out about this great project and the first thing I tested was Gravity Forms.... it failed :(

But since I wanted to use it, I started looking at some of the errors and this code seems to fix it for now:

```php
function custom_pre_translate_query($query)
{
    include_once( ABSPATH . 'wp-admin/includes/plugin.php' );

    // ** gravityforms **
    // SELECT TOP (LIMIT) requires a ORDER BY in MSSQL but not in MySQL, this block tries to find
    // a SELECT LIMIT without ORDER and then adds one with all the selected fields.
    // NOT PERFECT, IT WILL NOT MATCH 'distinct' or multiple queries, but it works with GF
    if (is_plugin_active('gravityforms/gravityforms.php')) {
        if (preg_match('/SELECT\s(.*)\s+FROM\s.*\sLIMIT\s(\d*)(?:,\s?(\d*))?/', $query, $matches)) {
            if (stripos($query, 'ORDER') === false) {
                // If the selected fields do not have *, then use them, otherwise we cannot translate it
                if (stripos($matches[1], '*') === 0) {
                    $query = str_replace('LIMIT', "ORDER BY {$matches[1]} LIMIT", $query);
                }
            }
        }
    }

    return $query;
}

function custom_query($query)
{
    include_once( ABSPATH . 'wp-admin/includes/plugin.php' );

    // Replacing IFNULL with ISNULL, Is there any difference between them in MySQL and MSSQL?
    if (stripos($query, 'IFNULL') > 0) {
        $query = str_ireplace('IFNULL', 'ISNULL', $query);
    }

    // ** gravityforms **
    // We check for these queris here because when they fail, the error code is not
    // expected by PN and we will not get another chance to fix them.
    if (is_plugin_active('gravityforms/gravityforms.php')) {
        // Gravity Forms: Fix fake row number
        if (stripos($query, 'SELECT @rownum:=0') !== false) {
            $query = '';
        }

        // Gravity Forms: Fix fake row number
        if (stripos($query, '@rownum:=@rownum + 1 as sort') > 0 &&
            stripos($query, '(l.id+0)') > 0
        ) {

            $query = str_ireplace(
                '@rownum:=@rownum + 1 as sort',
                'ROW_NUMBER() over (order by page.id desc) as sort', $query);

            $query = str_ireplace(
                '(l.id+0)',
                'l.id', $query);

        }
    }

    return $query;
}


add_filter('pre_translate_query', 'custom_pre_translate_query');
add_filter('query', 'custom_query');
```

I added that to my `functions.php` file because I did not want to change Project Nami/WordPress.... now It lets me create entries and see them.

I also found an issue with GF trying to save some cache data using RAW JSON, it failed indicating there was a quote not been closed.... I found out that enabling any `object cache plugin` fixes the issue because GF no longer tries to "emulate" caching in the DB but uses the given plugin (in my case I used WinCache)

Hope it helps,
Daniel.

**Comment by evilzenscientist** [comment]
I just tried with Gravity Forms - and pulled back from test because of mail issues.

As an aside - I was also getting a Gravity Forms database tables error.

**Comment by patrickebates** [comment]
The code from Daniel above should help you get past those errors.  We will use this in an upcoming build to add better support for Gravity Forms to the translation layer.

@dulfe  Do you have the error code that was being thrown by SQL Server?

**Comment by dulfe** [comment]
@patrickebates I deactivated both filters and I got this (in `wp-admin/Forms/Entries`)

```
WordPress database error: [[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near ':'. Code - 102]
SELECT @rownum:=0
WordPress database error: [[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Must declare the scalar variable "@rownum". Code - 137]
SELECT filtered.sort, l.*, d.field_number, d.value FROM wp_rg_lead l INNER JOIN wp_rg_lead_detail d ON d.lead_id = l.id INNER JOIN ( SELECT @rownum:=@rownum + 1 as sort, id FROM ( SELECT distinct l.id FROM wp_rg_lead l INNER JOIN wp_rg_lead_detail d ON d.lead_id = l.id WHERE (l.form_id=1 AND l.status = 'active') ORDER BY (l.id+0) DESC LIMIT 0,20 ) page ) filtered ON filtered.id = l.id ORDER BY filtered.sort
```

**Error 137** is not been handled in `wp-db.php` method `query`, then I manually added that code there and moved everything to `custom_pre_translate_query` and it worked... but I am not familiar enough with **Pn** to know the consequences :)

Daniel.

**Comment by dulfe** [comment]
@evilzenscientist I uninstalled and reinstalled GF and I did not get any errors *creating* a table but I did *dropping* a table and some others.

```
[12-Oct-2016 11:33:15 UTC] WordPress database error [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot drop the table 'Awp_rg_form', because it does not exist or you do not have permission. Code - 3701 for query DROP TABLE Awp_rg_form 
```

This file has the translate and php logs right after activation: 
[pn-gf-activationlogs.zip](https://github.com/ProjectNami/projectnami/files/524253/pn-gf-activationlogs.zip)

But I just ignore them and GF seems to work fine anyways, I was able to create forms (admin), insert them in pages (admin), fill entries (public) and review them (admin).

FYI, I had a **wincache object cache plugin enabled**, without it I got a bunch of errors like this:

```
[[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:6:{s:7:"headers";O:42:"Requests_Utility_CaseInsensitiveDictionary":1:{s:7:"'. Code - 105]
```

Daniel.

**Comment by patrickebates** [comment]
@dulfe Please see #140 regarding the SQL error that stops once you enabled wincache.  We could use more info from you, as your example is different from what we've seen ourselves.

**Comment by evilzenscientist** [comment]
@dulfe Gravity Forms is widely used - perhaps needs to be added to the test case list. Update is "deactivate, uninstall, reinstall" - so if that is nagging on a table drop - even if it's a cosmetic error there will be support tickets logged on both sides.

I'll test again by looking at some kind of object cache.
