### ISSUE TITLE
Deploy to Azure read-only database

### ISSUE THREAD

**Issue by 4c74356b41** [ProjectNami/projectnami#122]
There seems to be no way of doing this? Besides my experiments with just copying Project nami to another host and pointing it to a replica db seem to fail all the time, i asume wordpress needs to write something to db, it cant use read only copy?

**Comment by patrickebates** [comment]
I suspect what you're seeing are writes to wp_options for transient data.  Given that WP itself as well as many plugins write transient data on a regular basis, I suspect it can't be used with a read only DB.

I did a quick search on the topic and don't see anything about running on a read-only DB anywhere.

**Comment by 4c74356b41** [comment]
well, that sux, feature request ;)
