### ISSUE TITLE
Using SQL Server In-Memory Tables

### ISSUE THREAD

**Issue by RehanSaeed** [ProjectNami/projectnami#123]
It looks like [in-memory tables](https://www.simple-talk.com/sql/database-administration/questions-azure-sql-database-shy-ask/) would be a _massive_ win for performance if you are willing to pay for premium. Is this something that can be easily implemented?

**Comment by patrickebates** [comment]
I honestly have no idea at this point.  But if I had to guess, I would suspect that the use of nvarchar(max) for several columns may cause issues.  I looked into some other new features (perhaps it was columnstore indexes) and saw similar issues with the schema.

**Comment by RehanSaeed** [comment]
I hadn't realized there were so many restrictions. I'd love to benchmark it and see how much faster it is. Presumably the DB is the biggest bottleneck in WordPress and this would probably make that problem go away. Something to watch out for in the future.

https://msdn.microsoft.com/en-us/library/dn133181.aspx
https://msdn.microsoft.com/en-us/library/dn205318.aspx

**Comment by patrickebates** [comment]
OK, the 2nd link refers to the max data of the entire row being almost 8K, so any row in wp_posts of even medium size would be forced off-row.  Still, it may be worth testing once we get through some other things we have lined up first.

As for bottlenecks, have you tried PHP 7 yet?  The SQL drivers for it are not yet native on Web Apps (heard that might change by end of month) but in testing we've seen as much as a 66% reduction in processing time per page.

**Comment by RehanSaeed** [comment]
Wow 66% is huge! I've always fealt WordPress to be a little sluggish, I only use WordPress for my blog and wanted something faster, so I was looking at Ghost instead but am waiting for improvements now.

I've noticed some speedups while upgrading PHP and Project Nami recently, percieved or real, I'm not sure. I read on the project Nami blog that PHP 7 will come to Azure soon, I'm eagerly waiting for more news on the blog.

**Comment by RehanSaeed** [comment]
I've just noticed PHP 7 show up in the Azure portal. Is it safe to switch to it?

**Comment by patrickebates** [comment]
We're running it in production on ProjectNami.org but I haven't seen confirmation that the driver rollout that began last week is complete yet.  Your only option would be to enable it and see if your site continues to work.  If you get an error about SqlSrv missing, switch back to 5.6.
