### ISSUE TITLE
Azure Release Process

### ISSUE THREAD

**Issue by colin-resdiary** [ProjectNami/projectnami#124]
Hi,

We are currently trying to setup Wordpress within an existing ASP.NET MVC Cloud Service in Azure. I came across Project Nami and think it looks like a great fit so we can utilise SQL Azure but I've come across an issue that I'm not sure how to solve. Our release process is to deploy a new version of our website to Staging and then swap over Staging and Production slots however this will lose any content that is stored on the filesystem for Wordpress i.e. Themes, Uploaded content, etc.. I've seen the Windows Azure Storage for Wordpress plugin but this only seems to handle Uploaded Content and not Themes. Is this correct or is there another way to handle Themes that I'm missing?

Appreciate any help
Colin

**Comment by patrickebates** [comment]
You're correct about the themes.  What about adding the PN folders to your project/solution?

**Comment by colin-resdiary** [comment]
Yeah we can (and will) do that. The real problem is that our Marketing team will be dealing with the look and feel of the site and will no doubt change the theme every 5 minutes and we want to maintain that between deployments. But the more I think about it, I reckon we can have a background job that uploads the themes to a shared location and part of our build process downloads them and includes them in our artefacts.

Thanks for the help

**Comment by patrickebates** [comment]
Is it critical that you have both within the same Web App?  Have you considered two Web Apps within the same hosting plan?  Perhaps host this one at blog.domain.com?

**Comment by colin-resdiary** [comment]
Thats what we currently have but our Marketing team want to combine the two so they all come under the same domain. Joy.

**Comment by colin-resdiary** [comment]
I don't suppose there are any instructions on manually installing that I can follow?

**Comment by patrickebates** [comment]
Manual install is essentially identical to vanilla WordPress, so we didn't bother with a write-up.  Just download our latest release (1.3.4 as of this note; don't download Master as it's currently merging with WP 4.6) and unpack into the location, which I guess would be something like a Blog subfolder.  Have a site I work with which has ASP.Net Web Forms app in the root with PN in a blog folder.  You will also need the standard web.config for WP in the subfolder.
