### ISSUE TITLE
No such file or directory class-wp-upgrader-skin.php 

### ISSUE THREAD

**Issue by liliankasem** [ProjectNami/projectnami#125]
I just updated to the latest version of this github repo (using continuous deployment on azure). I'm getting this error when trying to delete or add new themes or plugins, any ideas?

I was able to add new plugins/themes in the older version.

`Warning: require_once(D:\home\site\wwwroot/wp-admin/includes/class-wp-upgrader-skin.php): failed to open stream: No such file or directory in D:\home\site\wwwroot\wp-admin\includes\class-wp-upgrader-skins.php on line 11 Fatal error: require_once(): Failed opening required 'D:\home\site\wwwroot/wp-admin/includes/class-wp-upgrader-skin.php' (include_path='.;C:\php\pear') in D:\home\site\wwwroot\wp-admin\includes\class-wp-upgrader-skins.php on line 11`

**Comment by patrickebates** [comment]
Are you hooked into the Master or Latest branch?  We recommend that Web Apps connect to Latest.

**Comment by liliankasem** [comment]
Ah I knew I was forgetting something, switched to the 'latest' branch and it works fine - thanks!
