### ISSUE TITLE
Rewrite Rules in Web.config

### ISSUE THREAD

**Issue by aramayowa** [ProjectNami/projectnami#126]
Howdy,

Thank you for all your work on Project Nami, it's fantastic.

I just got setup in Azure and i tried to add a rewrite rule to the web.config to force https. Once i added it the blog stopped showing up entirely though and i got this error in the logs

> SELECT TOP 1 option_value FROM wp_options WHERE option_name = 'rewrite_rules'
2016-08-29 04:59:49 Error Code: 208 -- Query NOT translated due to non-defined error code.
IF NOT EXISTS (SELECT * FROM [wp_options] WHERE [option_name] = 'rewrite_rules') INSERT INTO [wp_options] ([option_name], [option_value], [autoload]) VALUES ('rewrite_rules', '', 'yes') else UPDATE [wp_options] set [option_value] = '', [autoload] = 'yes' where [option_name] = 'rewrite_rules'
[29-Aug-2016 04:59:49 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'wp_options'. Code - 208 for query IF NOT EXISTS (SELECT * FROM [wp_options] WHERE [option_name] = 'rewrite_rules') INSERT INTO [wp_options] ([option_name], [option_value], [autoload]) VALUES ('rewrite_rules', '', 'yes') else UPDATE [wp_options] set [option_value] = '', [autoload] = 'yes' where [option_name] = 'rewrite_rules' made by wp_install, flush_rewrite_rules, WP_Rewrite->flush_rules, update_option, add_option

This is the rewrite rule i was trying to add.

`<rule name="Remove www" stopProcessing="true"> 
        <match url="(.*)" ignoreCase="true" /> 
        <conditions logicalGrouping="MatchAll"> 
          <add input="{HTTP_HOST}" pattern="^www\.(.+)$" /> 
        </conditions> 
        <action type="Redirect" url="https://{C:1}/{R:0}" appendQueryString="true" redirectType="Permanent" /> 
      </rule>`
 
So...what am i doing wrong? Is this not a recommended way to force https? I get the feeling this is a noob thing, so apologies.

Thanks again.

**Comment by patrickebates** [comment]
Here's two different rules I was able to obtain from two different sites running in production.  One rule is to force HTTPS and the other to remove www.  I note that there are small differences between this www rule and the one you posted.  Attaching as file as I had issues inserting them as code.
[RewriteRules.txt](https://github.com/ProjectNami/projectnami/files/443769/RewriteRules.txt)

**Comment by aramayowa** [comment]
Thanks a ton for such a quick response.

I replaced my single rule with yours but i got the same blank screen on the blog (see all rules in web.config below). Strangely enough i don't have any new errors in the php_errors.log

`<rule name="WordPress: https://mysitename/blog" patternSyntax="Wildcard">
          <match url="*"/>
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true"/>
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true"/>
          </conditions>
          <action type="Rewrite" url="index.php"/>
        </rule>
        <rule name="Force HTTPS" enabled="true">
          <match url="(.*)" ignoreCase="false" />
          <conditions>
            <add input="{HTTPS}" pattern="off" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" appendQueryString="true" redirectType="Permanent" />
        </rule>
        <rule name="Remove WWW" stopProcessing="true">
          <match url=".*" ignoreCase="true" />
          <conditions logicalGrouping="MatchAll">
            <add input="{HTTP_HOST}" pattern="^www\.(.*)$" />
          </conditions>
          <action type="Redirect" url="http://{C:1}/{R:0}"
              appendQueryString="true" redirectType="Permanent" />
        </rule>        `

One other thing i should have mentioned (apologies) is that i'm running projectnami in a virtual directory of an mvc web app (they are sibling folders in wwwroot).

Thanks!

**Comment by patrickebates** [comment]
I think you need to put the two new rules before the WordPress rule.  You may also need to change the name of that rule to simply WordPress or something else simple like that.  The colons and slashes may be causing issues.

**Comment by aramayowa** [comment]
Thank you.

I'm seeing some odd behavior.

So i made the changes, and i still got the blank screen. I commented out the two new rules in the web config (plus restarted the website) and now everything seems to be working (both forced https and removing www). I know i have those rules working in the mvc webapp but they didn't apply to the blog before (didn't think they would since the web configs are in sibling directories).

In any case, things seems to be working now with the two new rules commented out. Thank you for your all your help.
