### ISSUE TITLE
BackWPUp: warning: mysql_ping(): supplied resource is not a valid MySQL-Link resource

### ISSUE THREAD

**Issue by Gedl77** [ProjectNami/projectnami#127]
get this warning after upgrade to PN 1.4.0. Backup still works.

**Comment by patrickebates** [comment]
Did you recently upgrade the plugin or the PHP environment as well?  The function containing MySQL_ping isn't called by anything in PN Core.

**Comment by Gedl77** [comment]
Hy Patrick, yes, I recently updated the plugin. Ist only a warning, the backup still works
