### ISSUE TITLE
Fatal error: Class 'WP_Ajax_Upgrader_Skin' not found

### ISSUE THREAD

**Issue by KY4U** [ProjectNami/projectnami#128]
I last synced on 08/30/16.  I just noticed that I'm receiving fatal errors when attempting to update plugins using the Update Now link from the plugins page.  Error is:

Update Failed: Fatal error: Class 'WP_Ajax_Upgrader_Skin' not found in D:\home\site\wwwroot\nami\wp-admin\includes\ajax-actions.php

**Comment by patrickebates** [comment]
The merge with 4.6 was completed at about 03:00 UTC on 9/1/16.  Please sync and let us know if the issue persists.

**Comment by KY4U** [comment]
My mistake.  I have too many installations going and I was looking at the wrong one.

I apologize for any confusion.,
