### ISSUE TITLE
wp smush error with project nami

### ISSUE THREAD

**Issue by GilbertLiddell** [ProjectNami/projectnami#129]
Hi,

I'm trying to use a wordpress image optimisation plugin called wp mush and getting the following error after activating the plugin.

Any help would be appreciated.
Here's the error

supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1445
WordPress database error: [[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'. Code - 102]
SELECT post_id, meta_value FROM wp_postmeta WHERE meta_key='wp-smpro-smush-data' OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY
WordPress database error: [[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'. Code - 102]
SELECT meta_value FROM wp_postmeta WHERE meta_key='wp-smush-resize_savings' OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY
WordPress database error: [[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'. Code - 102]
SELECT meta_value FROM wp_postmeta WHERE meta_key='wp-smush-pngjpg_savings' OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY

**Comment by GilbertLiddell** [comment]
Any help would be appreciated

**Comment by patrickebates** [comment]
SQL Server's OFFSET FETCH requires an ORDER BY, which there isn't one here.  We'll take a look at options.

**Comment by GilbertLiddell** [comment]
We've decided to uninstall wp smush.
