### ISSUE TITLE
Intalling latest verions getting need table prefix

### ISSUE THREAD

**Issue by scrummie02** [ProjectNami/projectnami#131]
I have one in there, but it doesn't see it.  I keep getting table prefix required.

**Comment by scrummie02** [comment]
I get this error
ERROR: "Table Prefix" must not be empty.

**Comment by scrummie02** [comment]
I edited the config.php and connected but it won't take a username.  It keeps saying put in a valid user name even though I do.

**Comment by patrickebates** [comment]
Can you walk me through your install steps?  I just performed a fresh install using Deploy to Azure and did not experience any issues.

**Comment by scrummie02** [comment]
Sure,

Uzipped name to a folder.  Gave IUSR write permissions to directory (which are taken away after that – except for wp-content) I already have a database created in MSSQL.  

Accessing the website and running though the regular wordpress type setup where it gets my information.  When asking for DB info, it says I need a table prefix.

 

I just edited the wp-config to get around that, but now when asking for my site info, it says I need a valid name.  Is there a setting in the DB or something else I need to set?

**Comment by scrummie02** [comment]
My collation is SQL Latin

**Comment by patrickebates** [comment]
You're leaving the write permissions in place until you complete the initial setup, yes?  The initial setup will create the wp-config.php file.

**Comment by scrummie02** [comment]
Yes sir

Get Outlook for iOS




On Sun, Sep 11, 2016 at 8:48 PM -0400, "Patrick Bates" <notifications@github.com> wrote:












You're leaving the write permissions in place until you complete the initial setup, yes?  The initial setup will create the wp-config.php file.

**Comment by scrummie02** [comment]
I ended up copying it and naming it wp-config.  So from wp-config-sample to wp-config and put in my database info.

**Comment by scrummie02** [comment]
before I was getting I need a table prefix, even though one is in there.

**Comment by patrickebates** [comment]
It sounds like a permissions problem with wp-config.php, though I can't be certain.  Anything in the php_error_log that might point to the issue?

**Comment by scrummie02** [comment]
IUSR has modify to the whole directory.  As does the app pool identity. Nothing in the logs

**Comment by patrickebates** [comment]
Not sure what to say, but it sounds like WP couldn't read from wp-config.php

Not sure you would want to repeat the install from scratch, but I suspect you will find that after the file was created IUSR was missing read and/or execute rights on the file.

**Comment by scrummie02** [comment]
I haven’t gotten anywhere yet, so I can retry it.  I’ll extract it again to that directory and give it a shot

**Comment by scrummie02** [comment]
Same error.

Extracted project name to the newest folder, gave IUSR write permissions, used PHP5.6, start setup.

I pick the language, input database info and I get:

ERROR: "Table Prefix" must not be empty.

**Comment by patrickebates** [comment]
What are the permissions on wp-config.php for IUSR and for the app pool identity?

**Comment by scrummie02** [comment]
Both have modify.

**Comment by scrummie02** [comment]
even if I put in erroneous information, the result is the same.  It seems like that field isn't getting passed in the sessions or something.

**Comment by scrummie02** [comment]
I'm using php 5.6.24

**Comment by scrummie02** [comment]
SQLSRV support is also enabled.  I have pdo_sqlsrv and the sqlsrv .dll's enabled.

**Comment by patrickebates** [comment]
But what other rights than modify?  It's possible to have Modify rights to a file, but not be able to Read or Execute.

**Comment by scrummie02** [comment]
I has from modify down...ie...modify, read, write, execute...

**Comment by patrickebates** [comment]
Afraid I don't know what else to tell you, except to compare the permissions between wp-config.php and wp-config-sample.php as something must be different if you can copy the second one to create a useable file.

**Comment by scrummie02** [comment]
Even when I go through the process where the wp-config isn't there and the setup creates it, I get that prefix error.  Is there a setting for SQL that needs to be selected?  Collation setting or something liket hat?

**Comment by patrickebates** [comment]
No, that's handled only at the DB level.

It works properly after you copy the wp-config-sample and make the edits yourself, right?

**Comment by scrummie02** [comment]
It works until I fill in the info for username/site name..etc  It won't accept a username.  Even it's something simple like "admin".

**Comment by patrickebates** [comment]
So if you don't successfully complete the setup routine, no user gets created.  Which I think is your problem about being unable to login.

I still think you have a permission problem.  What if you start fresh but grant Everyone access to Read and Execute in the root of the site?

**Comment by scrummie02** [comment]
same error:
ERROR: "Table Prefix" must not be empty.

This is when I do the default wordpress installation.  I select language, input infor (db bame, passowrd, table prefix)...and this error comes up

**Comment by patrickebates** [comment]
So wp-config.php exists and appears to have the values written properly?

What about permissions for Network Service?

Beyond that, I don't know what else we can do for you.  There is obviously a local configuration issue which we are not going to be able to assist you with much further.

**Comment by patrickebates** [comment]
Oh, I do see one thing that might be helpful.  The error you mention is actually attempting to retrieve the table prefix from the POST object.  So we're not to the point of using wp-config.php yet.  It's as though the values didn't survive the submit.

**Comment by scrummie02** [comment]
that's it
is there a workaround?

**Comment by patrickebates** [comment]
Never heard of this before, so no idea. How did you configure the PHP environment on the server?  Did you use the Web Platform Installer from Microsoft?

**Comment by scrummie02** [comment]
Yes.  Used WPI.  And I installed the PHP tool so you can select the version via the IIS GUI

Get Outlook for iOS




On Mon, Sep 12, 2016 at 4:01 PM -0400, "Patrick Bates" <notifications@github.com> wrote:












Never heard of this before, so no idea. How did you configure the PHP environment on the server?  Did you use the Web Platform Installer from Microsoft?

**Comment by patrickebates** [comment]
Did you install URL Rewrite 2.0 as part of the WPI packages?  I know it's required for permalinks to function properly.  Not sure if it would apply here. It now seems that IIS may not be passing all of the data to PHP, or that IIS doesn't have it either.

**Comment by scrummie02** [comment]
Yes.  I had generic Wordpress on here before 

Get Outlook for iOS




On Mon, Sep 12, 2016 at 4:05 PM -0400, "Patrick Bates" <notifications@github.com> wrote:












Did you install URL Rewrite 2.0 as part of the WPI packages?  I know it's required for permalinks to function properly.  Not sure if it would apply here. It now seems that IIS may not be passing all of the data to PHP, or that IIS doesn't have it either.

**Comment by patrickebates** [comment]
There's a few things I could find via Google
https://www.google.com/?gws_rd=ssl#q=iis+php+%24_post+empty

They center around modules that may be interfering with the POST data, the possibility that the POST verb has been disabled, etc.

**Comment by scrummie02** [comment]
Ah.  I have url scan installed as a security measure.  I'll temporarily disable to see if that's the issue. 

Get Outlook for iOS




On Mon, Sep 12, 2016 at 4:19 PM -0400, "Patrick Bates" <notifications@github.com> wrote:












There's a few things I could find via Google

https://www.google.com/?gws_rd=ssl#q=iis+php+%24_post+empty



They center around modules that may be interfering with the POST data, the possibility that the POST verb has been disabled, etc.

**Comment by scrummie02** [comment]
I disabled URLSCAN and also granted everyone access, still no luck

**Comment by scrummie02** [comment]
Mod security on IIS was the culprit.  We need to change some rules around.  After disabling the module it worked.
