### ISSUE TITLE
Deploy To Azure - Subscription dropdown not showing multiple subscriptions

### ISSUE THREAD

**Issue by RonakThakkar** [ProjectNami/projectnami#134]
Hi,

I have an account that has multiple subscriptions.

When I click "Deploy To Azure", in first step there is a dropdown to select Azure subscription where project nami will be created. But it only shows one subscription (may be that's default). But I wish to see all the subscriptions and select the one where I wish to create the project.

regards,
ronak thakkar

**Comment by pippercameron** [comment]
Is is actually a subscription or another directory your account is linked to (there's also a "Directory" drop down)?
