### ISSUE TITLE
SMTP issues

### ISSUE THREAD

**Issue by evilzenscientist** [ProjectNami/projectnami#138]
I configured the SMTP plugin against Office 365 - and a few issues:
- sending mails seems very slow
- sending from Gravity Forms plugin does not send all of the mails

I'm coming from postfix on SLES 11 on Azure - that's my baseline. Sending mail is almost instantaneous; I've not got issues with Gravity Forms or any other app that hooks into the native mail stack.

Is there anything by way of logging I can collect for this?

**Comment by pippercameron** [comment]
A few things about the emails:

* How large are they? (also, do they have attachments?)
* How often are you sending them? (could be a rate limiting issue)

Lots of folks use the SMTP plugin (which is just a simple class to configure the the built in mailer in WordPress) and it's generally as fast as your email service provider is.

You could definitely add some debugging to `wp_mail()` to catch failures in action.

**Comment by evilzenscientist** [comment]
Tiny - less than 10k, maybe 1 mail per hour max. The backend mail service didn't change - it's TSL authentication to Office365.

I'll see what I can do for logging.

**Comment by evilzenscientist** [comment]
OK - finally found time to do more debug on this.

Mail is failing to send when addressed to multiple recipients.

user1@domain.com,user2@domain.com

Single recipient is fine.

I'll go look at the SMTP plugin and see if that is causing something to drop.

**Comment by evilzenscientist** [comment]
Ok - looks like the SMTP Configuration plugin isn't doing the right thing. I'll look at that code in a moment.

I switched out to the Mail Bank plugin for testing - and that's working fine.

Performance - the Linux based plugins just drop into the postfix queue and return; the SMTP plugin waits, connects and sends - causing a website pause.
