### ISSUE TITLE
Unclosed quotation mark

### ISSUE THREAD

**Issue by erikest** [ProjectNami/projectnami#141]
After updating to the latest, I was getting a strange error for an unfinished string, but the sql it gave me in the log was valid when I ran it manually.  I've noticed in wp_db that the translation method is only called after the sql errors out  based on a set of error codes stacked in a switch statement.  The error, 105, wasn't in that list, but adding it in seems to do the trick.

**Comment by patrickebates** [comment]
We're whitelisting the error codes that we know a translation can assist with in order to prevent wasting resources on situations where it simply can't help.  I'm adding 105 to the lists now.  Thanks for the report.

**Comment by patrickebates** [comment]
This error code update is included in 1.4.3
