### ISSUE TITLE
Error establishing a database connection (during initial creation)

### ISSUE THREAD

**Issue by jdmichel** [ProjectNami/projectnami#142]
I used Deploy to Azure, but the first login for initial setup fails. 

I verified that I can login from a new visual studio database project (once I added a firewall rule), but I can't see any hints about what actually failed when wordpress failed to login to the database with the same user and password.

Since I don't have anything else logical to try I'm going to try changing the password to a less secure one. (I was using a random generated password.)

**Comment by jdmichel** [comment]
Resetting the database password to one only containing letters and numbers allowed me to get past the first login screen, but almost immediately it must try to login again, and now I get the same error window, but this time without the option to retry.

**Comment by patrickebates** [comment]
Check the App Settings in the Azure portal for the site. During the Deploy to Azure script, a copy of the credentials are written there to assist you later with using some of our Web Jobs in the future (such as our index rebuilder).  The site itself will also prefer those credentials over the ones entered.

**Comment by jdmichel** [comment]
That was the problem. Thanks so much for your prompt response.

**Comment by jdmichel** [comment]
Btw, the problematic password was \6;GMlv4:.vh$[N}
