### ISSUE TITLE
Category issue with vanilla WooCommerce

### ISSUE THREAD

**Issue by GrimaceOfDespair** [ProjectNami/projectnami#144]
The following query is generated on a clean nami install with a vanilla WooCommerce, which results in an error on the category overview page:

http://www.example.net/wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product

```sql
SELECT DISTINCT t.*, tt.*
FROM wp_terms AS t
  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
  LEFT JOIN wp_termmeta AS tm ON (t.term_id = tm.term_id AND tm.meta_key = 'order')
WHERE tt.taxonomy IN ('product_cat')
ORDER BY t, tt, tm ASC, t.name ASC
```

Note that the `ORDER BY` is invalid in the context of T-SQL

**Comment by patrickebates** [comment]
By any chance do you have the translation log with the original query as well?  Will help us greatly to see how it started out.
