### ISSUE TITLE
Relevanssi & Gravity forms query error

### ISSUE THREAD

**Issue by mrtijn** [ProjectNami/projectnami#146]
Hi,

I'm getting a sql error when i try to use the plugins [relevanssi](https://wordpress.org/plugins/relevanssi/) & [gravity forms](http://www.gravityforms.com/)
This happens when i try to index my site with relevanssi. Or when i try to access the submissions in Gravity forms.

Is this something that can be fixed? Or will i need to look for an alternative?

The relevanssi error is:
`[08-Nov-2016 15:14:41 UTC] WordPress databasefout [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'INTO'. Code - 156 bij query INSERT IGNORE INTO wp_relevanssi (doc, term, term_reverse, content, title, comment, tag, link, author, category, excerpt, taxonomy, customfield, type, taxonomy_detail, customfield_detail, mysqlcolumn)`

The gravity forms error is:

```
[16-Sep-2016 14:45:40 UTC] WordPress databasefout [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near ':'. Code - 102 bij query SELECT @rownum:=0 gemaakt door do_action('formulieren1_page_gf_entries'), call_user_func_array, GFForms::all_leads_page, GFEntryList::all_entries_page, GFEntryList::leads_page, GF_Entry_List_Table->prepare_items, GFAPI::get_entries, GFFormsModel::search_leads
[16-Sep-2016 14:45:40 UTC] WordPress databasefout [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Must declare the scalar variable "@rownum". Code - 137 bij query SELECT filtered.sort, l.*, d.field_number, d.value
            FROM wp_rg_lead l
            INNER JOIN wp_rg_lead_detail d ON d.lead_id = l.id
            INNER JOIN
            (
                SELECT @rownum:=@rownum + 1 as sort, id
                FROM
                (
                    SELECT distinct l.id
                    FROM wp_rg_lead l
                    INNER JOIN wp_rg_lead_detail d ON d.lead_id = l.id
                    
                    WHERE (l.form_id=10 AND l.status = 'active')
                    ORDER BY (l.id+0) DESC
                    LIMIT 0,20
                ) page
            ) filtered ON filtered.id = l.id
```

Thanks in advance!

**Comment by patrickebates** [comment]
Looks like these will require specific translation updates.  The first one, INSERT IGNORE isn't supported by SQL Server so it needs to change to an IF NOT EXISTS statement.  

The second one is someone trying to create row numbers in MySQL when it doesn't have a built-in function for that.  It's actually much easier to do that in SQL Server because such a function does exist.

**Comment by DeanoFino** [comment]
I ran into this same error myself when trying to export gravity form entries to csv. It looks like the solution from @dulfe in #121 works slightly modified to fix the same error with export:

```
if (stripos($query, '@rownum:=@rownum + 1 as sort') > 0) {

            $query = str_ireplace(
                '@rownum:=@rownum + 1 as sort',
                'ROW_NUMBER() over (order by page.id desc) as sort', $query);

        }
```
