### ISSUE TITLE
CSP Azure Tenant Deployment Error

### ISSUE THREAD

**Issue by dsplab75** [ProjectNami/projectnami#148]
I had deployed at open azure tenant to nami template with no errors.
but when i deploy to  nami template to CSP azure tenant, errors is occurred as follows.

OPERATION NAME Update web sites config
STATUS Failed
EVENT TIMESTAMP Tue Nov 15 2016 21:14:25 GMT+0900 (대한민국 표준시)
UTC TIMESTAMP Tue, 15 Nov 2016 12:14:25 GMT
CALLER admin@sbcktest01.onmicrosoft.com
AUTHORIZATION 
action:Microsoft.Web/Sites/config/write role: scope:/subscriptions/62782104-515a-4659-a854-41c3335f68bd/resourcegroups/projectnamicc40/providers/Microsoft.Web/Sites/projectnamicc40/config/web
RESOURCE URI /subscriptions/62782104-515a-4659-a854-41c3335f68bd/resourcegroups/projectnamicc40/providers/Microsoft.Web/Sites/projectnamicc40/config/web
SUBSCRIPTION ID 62782104-515a-4659-a854-41c3335f68bd
EVENT SUBMISSION TIMESTAMP Tue Nov 15 2016 21:14:39 GMT+0900 (대한민국 표준시)
OPERATION ID f8897919-b4f9-494b-b162-609166a09120
CORRELATION ID c52d6ce7-c19c-41e5-9a98-9b342f767124
LEVEL Error
RESOURCE GROUP projectnamicc40
RESOURCE PROVIDER Azure Web Sites
CATEGORY Administrative
PROPERTIES 
statusCode:Unauthorized statusMessage:{"error":{"code":"BadRequest","message":""}}

I had checked azure activity log, and checked json file like attached file
![error2](https://cloud.githubusercontent.com/assets/10557352/20306034/d40b788e-ab7b-11e6-8342-e7c4f872beb7.jpg)

![error](https://cloud.githubusercontent.com/assets/10557352/20305945/63fa3350-ab7b-11e6-9a50-855fb8a65e3c.jpg)

I think that CSP azure tenant and Open azure tenant is different.
How can i resolve that problem?

**Comment by patrickebates** [comment]
We'll see if we can dig deeper into this.  In the meantime, your best option may be a manual deployment.

Create a new Web App in the portal, and under Continuous Deployment select Other.  The values you need are as follows:
Type - Git
Location - https://github.com/ProjectNami/projectnami
Branch - latest

You will also need a SQL Database.  You will provide your server name and credentials after starting the installation process by visiting your new Web App in your browser.

**Comment by Rocla** [comment]
I found a partial solution, the api version for the lines 4013 and 4046. I changed to `2014-06-01`. https://github.com/ProjectNami/projectnami/blob/master/azuredeploy.json#L4013
https://github.com/ProjectNami/projectnami/blob/master/azuredeploy.json#L4046

With this "fix" the deployment is ending with a success. However, I have to put manually the database information into the wp webapp.

**Comment by patrickebates** [comment]
Is there anything which might be unusual about your subscriptions? So far we have been unable to duplicate this issue ourselves.

**Comment by Rocla** [comment]
I have the `Visual Studio Enterprise: BizSpark` I don't know if it's unusual.

**Comment by patrickebates** [comment]
Are you deploying to the default directory?  We've had reports of an issue when deploying to a different directory before, but it appeared to be related to issues with Azure Deploy and not the script.

**Comment by Rocla** [comment]
Default directory, default resource group you mean? No, I am deploying on a completely new directory at each try. However, updating a resource group works for me with this fix.

**Comment by patrickebates** [comment]
Wait, are you using the Deploy To Azure button on our site and/or the JSON file included here on GitHub, or are you using the one within the Azure Gallery?

**Comment by Rocla** [comment]
For me, *Deploy To Azure* and *Azure Gallery* are not working out of the box. I am deploying via the unix azure cli with the JSON file.

**Comment by Rocla** [comment]
I could fix the issue on my side with this. It's now behaving as it should. (on my side again)
