### ISSUE TITLE
Nami direct deploy to Azure , SQLserver configuration for exiting SQLserver and new DB

### ISSUE THREAD

**Issue by ppGrande** [ProjectNami/projectnami#149]
Sure I can try and test, but this would be an indication of a poorly written deployment automation script.

**QUESTION:** Is it possible to select an existing SQL server, and to be the DB newly created ?

I read in http://projectnami.org/download/
"New web site, SQL server, and database will be created. "
but no indication what happens if as server name I indicate an existing server

I come to https://deploy.azure.com/?repository=https://github.com/ProjectNami/projectnami/tree/latest#/form/setup
and tested writing an existing SQL server, and no indication on error

I think it should be given the option to create a new SQLserver, or use existing, 
And to select the name of the database that will be newly created 
(not sure if existing DB should be allow to be used)

I gong to build a "farm" of WPs (just four, for four friends) and I would not like to have four SQL servers lying around as I can (should) do all in once

Otherwise:
**CONGRATULATIONS FOR THE INITIATIVE !!!**
(I am so glad to be able to lose of sight MySQL)

**Comment by patrickebates** [comment]
Yes, the option to select existing SQL Server would be good.  But I believe the options available within Deploy To Azure are the limiting factor.  At the time this was set up, the new portal was still in Preview.  Perhaps there is a way to allow this ARM template to be consumed by the new portal directly and allow for options such as this.

**Comment by ppGrande** [comment]
it seem so ...

this is from the azuredeploy.json in git

```
 "resources": [
        {
          "name": "[parameters('**siteName**')]",
          "type": "databases",
          "location": "[parameters('siteLocation')]",
          "apiVersion": "2014-04-01-preview",
          "dependsOn": [
            "[concat('Microsoft.Sql/servers/', parameters('**sqlServerName**'))]"
          ],
          "properties": {
            "edition": "Basic",
            "collation": "[parameters('sqlCollation')]",
            "maxSizeBytes": "2147483648",
            "requestedServiceObjectiveId": "dd6d99bb-f193-4ec1-86f2-43d3bccbc49c"
}
```


and this is from
[https://elliotthamai.wordpress.com/2014/11/15/using-custom-arm-templates-with-the-deploy-to-azure-button/](url)

```
sqlServerLocation – Returns possible SQL Server locations
sqlServerName – Does validation on the name syntax
sqlAdministratorLogin – Fills in the value by using the user’s name
```

other example under
[https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-sql-database/azuredeploy.json](url)
where databaseName goes as variable


seems not complex, (never writen a azuredeploy.json) but seems very intuitive


Allowing to write manually also the DB name will be great !!
Our resources lies as 
  - WEA_blablalba  for WEbApplication
  - SQLdb_blablabla  for (you guess right!) SQL DataBases
