### ISSUE TITLE
Layer slider issue

### ISSUE THREAD

**Issue by aurelioa** [ProjectNami/projectnami#151]
Hi 
I'm using a wordpress site developed with Project Nami Version 1.4.1 ( WP Version 4.6.1 ), since i got the last update from the plugin LayerSlider Wp 6 i can't save any change in any the slider i create and even in the slidre already created i make a change, i click to the save button and after saving, nothing change.
I wrote to the LayerSlider Team and they did not find any issue about.
Is it possible project nami team can fix this problem?
Thank you
Aurelio

**Comment by patrickebates** [comment]
Any chance you might have a php_error.log or translate.log for the queries that are failing?

**Comment by aurelioa** [comment]
Where should i check it out?

**Comment by aurelioa** [comment]
Hi 
i found the files you were talking about. Shall i send you? If yes how can i send you? 
php_errors size is 10,6 MB and translate size is more than 51 MB.

**Comment by patrickebates** [comment]
You should be able to attach them here. But if you can isolate the lines related to this issue, that would be helpful.

**Comment by aurelioa** [comment]
[php_errors.txt](https://github.com/ProjectNami/projectnami/files/617070/php_errors.txt)

**Comment by aurelioa** [comment]
2016-10-06 08:10:11 Error Code: 102 -- Begin Query translation attempt:
CREATE TABLE wp_layerslider (
			  id int(10) NOT NULL AUTO_INCREMENT,
			  author int(10) NOT NULL DEFAULT 0,
			  name varchar(100) NOT NULL,
			  slug varchar(100) NOT NULL,
			  data mediumtext NOT NULL,
			  date_c int(10) NOT NULL,
			  date_m int(11) NOT NULL,
			  flag_hidden tinyint(1) NOT NULL DEFAULT 0,
			  flag_deleted tinyint(1) NOT NULL DEFAULT 0,
			  PRIMARY KEY  (id)
			) DEFAULT CHARACTER SET utf8
2016-10-06 08:10:11 -- Translation result:
CREATE TABLE wp_layerslider (
			  id int NOT NULL IDENTITY(1,1),
			  author int NOT NULL DEFAULT 0,
			  name NVARCHAR(100) NOT NULL,
			  slug NVARCHAR(100) NOT NULL,
			  data NVARCHAR(MAX) NOT NULL,
			  date_c int NOT NULL,
			  date_m int NOT NULL,
			  flag_hidden tinyint NOT NULL DEFAULT 0,
			  flag_deleted tinyint NOT NULL DEFAULT 0,
			  CONSTRAINT [wp_layerslider_id] PRIMARY KEY CLUSTERED (id) WITH (IGNORE_DUP_KEY = OFF)
);


2016-10-06 08:10:18 Error Code: 156 -- Begin Query translation attempt:
SELECT SQL_CALC_FOUND_ROWS * FROM wp_layerslider WHERE flag_hidden = '0' AND flag_deleted = '0' 
									ORDER BY date_c DESC LIMIT 0, 20
2016-10-06 08:10:18 Error Code: 102 -- Begin Query translation attempt:
select * from wp_revslider_sliders where alias = 'main_slider'  AND `type` != 'template'
2016-10-06 08:10:18 -- Translation result:
SELECT * FROM wp_layerslider WHERE flag_hidden = '0' AND flag_deleted = '0'
