### ISSUE TITLE
Issue with connecting WordPress to Azure SQL

### ISSUE THREAD

**Issue by darkhawk023** [ProjectNami/projectnami#152]
We have WordPress installed on an Azure VM, and we have copyied the ProjectNami files to IIS.  We are trying to connect to an existing SQL Server in Azure SQL.

When putting in the detail and attempt to install/connect, we receive the following errors:

Warning: file_put_contents(C:/inetpub/wwwroot/wordpress/wp-includes/fields_map.parsed_types.php): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\fields_map.php on line 202

Warning: include(C:\inetpub\wwwroot\error_page.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\wordpress\wp-includes\fields_map.php on line 209

Warning: include(): Failed opening 'C:\inetpub\wwwroot\error_page.php' for inclusion (include_path='.;C:\php\pear') in C:\inetpub\wwwroot\wordpress\wp-includes\fields_map.php on line 209

Any ideas on how to resolve?

**Comment by patrickebates** [comment]
The file fields_map.php is used to store some data related to MySQL translations for plugins.  Try creating an empty file with that name in the wp-includes folder and giving the IUSR account write permissions to it.

**Comment by darkhawk023** [comment]
Doing so gives me a new error:


Fatal error: Class 'Fields_map' not found in C:\inetpub\wwwroot\wordpress\wp-includes\translations.php on line 255

Timothy Roussel, MCSA
CONSULTANT, CORE INFRASTRUCTURE
225.216.1500 OFFICE [cid:image006.png@01D24B11.D510A210]  504.329.8274 MOBILE
[cid:image002.jpg@01D24B11.D50D1FA0]<http://www.sparkhound.com/>
[cid:image003.jpg@01D24B11.D50D1FA0]<http://www.twitter.com/sparkhound>[cid:image004.jpg@01D24B11.D50D1FA0]<https://www.linkedin.com/company/sparkhound>[cid:image005.jpg@01D24B11.D50D1FA0]<http://www.facebook.com/sparkhoundllc>

**Comment by patrickebates** [comment]
Whoops, realized I left part of the file name out.  You need the fields_map.php file from the ZIP package as-is.  The file you need to create is fields_map.parsed_types.php

Put the following into that file, and give it write permissions for IUSR...

`<?php return array (
  '' => 
  array (
  ),
)
 ?>`

**Comment by darkhawk023** [comment]
Definitely progress!

I’m now getting these errors:

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 2288

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 2288

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 2288

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: Cannot modify header information - headers already sent by (output started at C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php:1756) in C:\inetpub\wwwroot\wordpress\wp-admin\install.php on line 59
Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756
lang="en-US" xml:lang="en-US">
Warning: error_log(ERRORLOGFILE): failed to open stream: Permission denied in C:\inetpub\wwwroot\wordpress\wp-includes\wp-db.php on line 1756

Timothy Roussel, MCSA
CONSULTANT, CORE INFRASTRUCTURE
225.216.1500 OFFICE [cid:image006.png@01D24B16.DE188BC0]  504.329.8274 MOBILE
[cid:image002.jpg@01D24B16.DE141EF0]<http://www.sparkhound.com/>
[cid:image003.jpg@01D24B16.DE141EF0]<http://www.twitter.com/sparkhound>[cid:image004.jpg@01D24B16.DE141EF0]<https://www.linkedin.com/company/sparkhound>[cid:image005.jpg@01D24B16.DE141EF0]<http://www.facebook.com/sparkhoundllc>

**Comment by darkhawk023** [comment]
I ignored the errors, it appears to be working.


Timothy Roussel, MCSA
CONSULTANT, CORE INFRASTRUCTURE
225.216.1500 OFFICE [cid:image006.png@01D24B18.1D553F30]  504.329.8274 MOBILE
[cid:image002.jpg@01D24B18.1D5231F0]<http://www.sparkhound.com/>
[cid:image003.jpg@01D24B18.1D5231F0]<http://www.twitter.com/sparkhound>[cid:image004.jpg@01D24B18.1D5231F0]<https://www.linkedin.com/company/sparkhound>[cid:image005.jpg@01D24B18.1D5231F0]<http://www.facebook.com/sparkhoundllc>

**Comment by patrickebates** [comment]
Strange, I thought we had updated all of the references to ERRORLOGFILE already.  Pushed a commit for that.  Download the Master branch and replace your /wp-includes/wp-db.php with the one in that ZIP.

**Comment by darkhawk023** [comment]
Forgive my ignorance.  Is the Master branch the download from the ProjectNami download page (1.4.3 zip file)?

Timothy Roussel, MCSA
CONSULTANT, CORE INFRASTRUCTURE
225.216.1500 OFFICE [cid:image006.png@01D24B18.75E64810]  504.329.8274 MOBILE
[cid:image002.jpg@01D24B18.75E33AD0]<http://www.sparkhound.com/>
[cid:image003.jpg@01D24B18.75E33AD0]<http://www.twitter.com/sparkhound>[cid:image004.jpg@01D24B18.75E33AD0]<https://www.linkedin.com/company/sparkhound>[cid:image005.jpg@01D24B18.75E33AD0]<http://www.facebook.com/sparkhoundllc>

**Comment by patrickebates** [comment]
That's a link to our latest released version 1.4.3.  The Master branch here on GitHub contains our up-to-the-minute changes.
https://github.com/ProjectNami/projectnami/archive/master.zip

**Comment by darkhawk023** [comment]
I also just went ahead and still put the information in, despite the errors and it’s working fine so far.

I see what you mean by the master branch now on GitHub.

Timothy Roussel, MCSA
CONSULTANT, CORE INFRASTRUCTURE
225.216.1500 OFFICE [cid:image006.png@01D24B18.ECA39ED0]  504.329.8274 MOBILE
[cid:image002.jpg@01D24B18.ECA09190]<http://www.sparkhound.com/>
[cid:image003.jpg@01D24B18.ECA09190]<http://www.twitter.com/sparkhound>[cid:image004.jpg@01D24B18.ECA09190]<https://www.linkedin.com/company/sparkhound>[cid:image005.jpg@01D24B18.ECA09190]<http://www.facebook.com/sparkhoundllc>
