### ISSUE TITLE
ErrorLog entries

### ISSUE THREAD

**Issue by ThomasDerenthal** [ProjectNami/projectnami#153]
I am getting this "Error Code: 208 -- Query NOT translated due to non-defined error code" and then the SQL statement that caused it. There are several of these for every time I call the home page.

I am using the latest version of NAMI and am using a SQL Azure database.

**Comment by patrickebates** [comment]
208 appears to be an invalid object name.  Is this being generated by a custom theme or one of those included with PN?

**Comment by ThomasDerenthal** [comment]
I have a developer building me a site with the Jupiter WP theme.

**Comment by patrickebates** [comment]
Sounds like the theme is referencing a custom database table or other object that was not created successfully.  I recommend looking at the PHP error log (and our translation log in the same location, if enabled) to see what failed first.
