### ISSUE TITLE
Troubleshooting The Events Calendar plugin, Incorrect syntax near ':' Code - 102

### ISSUE THREAD

**Issue by mrjonliu** [ProjectNami/projectnami#154]
I'm new to Project Nami and I've been trying to troubleshoot why the very popular The Events Calendar plugin is throwing errors on the month view.  Using the debug bar plugin I can see the following error.  What's the best approach to fixing this when I don't have access to the Project Nami install or the server?  Am I limited to trying to customize the plugin code to fix the error?  Any suggestions on where to start or how to proceed?

[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near ‘:’. Code – 102

SELECT DISTINCT wp_posts.* 
FROM wp_posts 
INNER JOIN wp_postmeta 
ON ( wp_posts.ID = wp_postmeta.post_id ) 
LEFT JOIN wp_postmeta as tribe_event_end_date 
ON ( wp_posts.ID = tribe_event_end_date.post_id AND tribe_event_end_date.meta_key = ‘_EventEndDate’ ) 
WHERE 1=1 
AND wp_posts.ID IN (234165) 
AND ( wp_postmeta.meta_key = ‘_EventStartDate’) 
AND wp_posts.post_type = ‘tribe_events’ 
AND (wp_posts.post_status = ‘publish’ 
OR wp_posts.post_status = ‘tribe-ea-success’ 
OR wp_posts.post_status = ‘tribe-ea-failed’ 
OR wp_posts.post_status = ‘tribe-ea-schedule’ 
OR wp_posts.post_status = ‘tribe-ea-pending’ 
OR wp_posts.post_status = ‘tribe-ea-draft’ 
OR wp_posts.post_status = ‘private’) 
AND ((wp_postmeta.meta_value >= ‘2016-12-30 00:00:00’ AND wp_postmeta.meta_value <= ‘2016-12-30 23:59:59’) 
OR (tribe_event_end_date.meta_value >= ‘2016-12-30 00:00:00’ AND wp_postmeta.meta_value <= ‘2016-12-30 23:59:59’ ) 
OR (wp_postmeta.meta_value < ‘2016-12-30 00:00:00’ AND tribe_event_end_date.meta_value >= ‘2016-12-30 23:59:59’ )) 
ORDER BY CASE( wp_posts.ID ) 
WHEN 234165 THEN 0:1482451200:234165 END 
OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY

**Comment by patrickebates** [comment]
The problem appears to be the ORDER BY CASE statement and its options.  We've worked on support for this plugin before, and I don't recall any similar issue.  Could there be an option you are using which is triggering that clause, and if so what happens if you change that?

**Comment by mrjonliu** [comment]
Thanks for pinpointing the error!  I'm scouring the settings for the plugin and wordpress but I'm not seeing anything specific to that, so I started digging through the plugin code looking for that specific query.  I don't know enough about wordpress to confirm, but I think that references the sort order of the posts and it's using the ID as default?

I found this possible reference in the plugin code:

// If looking just for fields then let's replace the .ID with *
if ( $query->query_vars['fields'] == 'ids' ) {
	$sql = preg_replace( "/(^SELECT\\s+DISTINCT\\s{$wpdb->posts}.)(ID)/",
		"$1*, {$wpdb->postmeta}.meta_value as 'EventStartDate'",
		$sql );
}

**Comment by mrjonliu** [comment]
I'm seeing one other error at the same time as this, but it's related to a column name and comments, which aren't enabled for my project so I've been ignoring it, but perhaps it could be related.

SELECT comment_approved, COUNT( * ) AS num_comments FROM wp_comments WHERE comment_type != "tribe-ea-error" GROUP BY comment_approved
[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'tribe-ea-error'. Code - 207

**Comment by mrjonliu** [comment]
Can anyone out there with Project Nami confirm that The Events Calendar 4.3.3 runs correctly?  I'm running a vanilla theme and no settings changed on the plugin and still getting the errors.  I don't know if the installation of project nami has been tweaked somehow, but I'm at wits end on how to further troubleshoot and fix this problem.

**Comment by mrjonliu** [comment]
Thanks again @patrickebates 

I had the site admin spin up a sandbox on Project Nami with default twentyfourteen theme and The Events Calendar Plugin and i'm still getting the same error.  I can see the code in Project Nami source files related to the plugin where it was translated before, but I'm wondering if they changed something recently that caused this issue.  The plugin works fine on my normal Wordpress installation, but throws this error on vanilla Project Nami install:

SELECT DISTINCT wp_posts.* FROM wp_posts INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) LEFT JOIN wp_postmeta as tribe_event_end_date ON ( wp_posts.ID = tribe_event_end_date.post_id AND tribe_event_end_date.meta_key = '_EventEndDate' ) WHERE 1=1 AND wp_posts.ID IN (4046) AND ( 
wp_postmeta.meta_key = '_EventStartDate'
) AND wp_posts.post_type = 'tribe_events' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'tribe-ea-success' OR wp_posts.post_status = 'tribe-ea-failed' OR wp_posts.post_status = 'tribe-ea-schedule' OR wp_posts.post_status = 'tribe-ea-pending' OR wp_posts.post_status = 'tribe-ea-draft' OR wp_posts.post_status = 'private') AND ((wp_postmeta.meta_value >= '2016-12-22 00:00:00' AND wp_postmeta.meta_value <= '2016-12-22 23:59:59') OR (tribe_event_end_date.meta_value >= '2016-12-22 00:00:00' AND wp_postmeta.meta_value <= '2016-12-22 23:59:59' ) OR (wp_postmeta.meta_value < '2016-12-22 00:00:00' AND tribe_event_end_date.meta_value >= '2016-12-22 23:59:59' )) ORDER BY CASE( wp_posts.ID ) WHEN 4046 THEN 0:1482393600:4046 END OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY

**Comment by mwilliams42** [comment]
Did you have any luck with this? 
I'm having the same problems as you.

**Comment by mwilliams42** [comment]
Hi @mrjonliu and @patrickebates 
I found a way to fix the events calendar.

In the wp-includes folder there is a file called "translations.php"
in that file there is a section that already makes changes to sql queries for the-events-calendar.
it is commented 
`/**`
`      * The Events Calendar`
`*/`
`if ( is_plugin_active( 'the-events-calendar/the-events-calendar.php' ) ) {`

I added the following lines of code inside the main events-calendar if statement below the existing translations.

`if (stristr($query, 'SELECT comment_approved, COUNT( * ) AS num_comments FROM {$this->prefix}comments WHERE comment_type != "tribe-ea-error" GROUP BY comment_approved') !== FALSE) {`
`				$query = str_ireplace(`
`					'"', `
`					"'", $query);`
`			}`
`			if (stristr($query, 'ORDER BY CASE') !== FALSE) {`
`				$query = str_ireplace(`
`					'ORDER BY CASE', `
`					"--", $query);`
`			}`

Now month view loads correctly.

FYI @EgoAleSum

**Comment by mrjonliu** [comment]
THANK YOU @mwilliams42!!!  We just updated our translations.php file and the month view is working, excellent fix, thanks for sharing!

**Comment by patrickebates** [comment]
Thought we had already included this in PN by default, but guess we missed it.  It will be present starting with our next release.
