### ISSUE TITLE
Upgrading to Latest Release of Project Nami

### ISSUE THREAD

**Issue by darkhawk023** [ProjectNami/projectnami#155]
Using an on-prem install of WordPress connecting to SQL Azure, what is the best way to upgrade to latest release of PN?  I installed with a build from GitHub, and then I upgraded to the latest release from PN downloads (Copied the files into the wordpress IIS directory).   I notice all the themes were overwritten and was wondering if other content may get overwritten.

What is the best process for upgrading in this scenario?

**Comment by patrickebates** [comment]
The only themes which should be overwritten are the defaults included with WP and therefore PN as well.  You should not be modifying those themes, but rather creating child themes from them.  Themes that you create yourself or are not included in the distribution should not be touched.

**Comment by darkhawk023** [comment]
So all the files will be okay to overwrite in the IIS directory?

**Comment by patrickebates** [comment]
Provided you haven't made any modifications to the included files, yes.  This is how even the built-in Updater in WP works. The ZIP is unpacked over the existing install. Your media uploads and custom themes will not be touched.
