### ISSUE TITLE
Project Nami & FormidablePro

### ISSUE THREAD

**Issue by talisman3** [ProjectNami/projectnami#157]
Hi
I am using FormidablePro plugin for WordPress on Project Nami MSSQL. When updating the FormidablePro plugin from within WordPress I get the following error: Update Failed: Could not create directory. formidable/classes/views/frm-fields/back-end
Any idea how to resolve this?[ I found something on FormidablePro](https://formidablepro.com/help-desk/an-error-occurred-while-updating-formidable-could-not-create-directory-formidableproclassesviewscombo-fieldsaddresses/) where they explain that it may be the path that is too long?

Also.. what are the github configuration details for Project Nami on Azure. I would like to keep the application up to date with most recent updates.

Thanks

**Comment by patrickebates** [comment]
I doubt the path is too long.  It might simply be some sort of permission problem with your environment.  Perhaps try creating the directory manually?

You can find the GitHub settings you are looking for at the bottom of this post
http://projectnami.org/video-updating-project-nami/
