### ISSUE TITLE
Media Library not working

### ISSUE THREAD

**Issue by jdmichel** [ProjectNami/projectnami#158]
When we upload mp4 videos or even 7zip files to the media library they appear to upload, but any attempt to access the URL fails with a "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." message. 

PNG or ZIP files work correctly. 

Is there some security setting in Wordpress/NAMI that prevents access to media based on file extension or something?

**Comment by patrickebates** [comment]
IIS requires that it know the file extension and associated mime type of the files it will serve.  See the following...
https://blogs.iis.net/bills/how-to-add-mime-types-with-iis7-web-config

**Comment by jdmichel** [comment]
Thanks. I'm now trying to find a way to edit a web.config for an azure website. There's no obvious way to even tell that it's running IIS. 
I can get a command prompt hosted in the browser and use unix commands, but that seems like a very 1975 way to approach the problem. On second thought there don't appear to be any text editors installed so I'm not sure what to do.

**Comment by patrickebates** [comment]
Some options

Webmatrix
https://www.microsoft.com/web/webmatrix/wmx3features.aspx

Visual Studio Code
https://code.visualstudio.com/

**Comment by jdmichel** [comment]
I was able to edit it with the new App Service Editor included on the new Azure App Service / Development Tools.
Thanks again.
