### ISSUE TITLE
Latest version of WordPress

### ISSUE THREAD

**Issue by talisman3** [ProjectNami/projectnami#159]
Hi
I'm using Project Nami on Azure. When I log onto my WordPress site I am notified on the Plugins page that: "WordPress 4.7 is available! lease update now." 

Do I manually update WordPress or do I wait for the update to come through via the deployment available on github?

Thanks

**Comment by patrickebates** [comment]
Wait for us to make a new build available.  If you manually apply WP 4.7 over an existing PN install, you will loose everything that makes it work with SQL Server.

We're in progress with merging 4.7 into PN to produce version 1.5.0.  It normally takes us a couple of weeks to perform a major update merge such as this.  But between the holidays and changes in this build to some classes we had to heavily modify for SQL Server, we might run a bit longer this time.

Our primary goal is to get it right the first time, especially given the number of sites which rely on our codebase.
