### ISSUE TITLE
Save & Publish Button

### ISSUE THREAD

**Issue by aelahmar** [ProjectNami/projectnami#161]
Hi There,
I using latest version of project Nami (Version 1.5.0), after installing my theme and start modifying when I hit the button (Save & publish) it want save !!!

![capture](https://cloud.githubusercontent.com/assets/10611004/21344616/bd9ac008-c6ad-11e6-8e5a-ca48da5d0fa1.PNG)

**Comment by aelahmar** [comment]
Any Help!

**Comment by patrickebates** [comment]
We received a similar report through other channels yesterday.  We're working on it, but with no error messages being generated it's taking more time than we would like.

**Comment by patrickebates** [comment]
1.5.1 was just released with the fix
