### ISSUE TITLE
Comment section not showing on blog posts

### ISSUE THREAD

**Issue by WouterDeKort** [ProjectNami/projectnami#162]
I've just updated my blog to the latest version and I now get the following error:

Fatal error: Cannot redeclare class WP_Role in D:\home\site\wwwroot\wp-includes\class-wp-role.php on line 15

You can see this at  http://wouterdekort.com/2016/12/20/microsoft-is-not-your-enemy/

What can I do to fix this?

**Comment by patrickebates** [comment]
I'm not seeing any error message at the link you provided.  I have also checked the codebase and have not seen a second instance of class WP_Role anywhere.

Sounds like you might have a file that didn't update properly.  How are you updating your installation?
