### ISSUE TITLE
Nami on SQL2008

### ISSUE THREAD

**Issue by ablanco442** [ProjectNami/projectnami#164]
Hi,

I understand that Nami does not run on MSSQL 2008 since the PHP 5.6 driver requires MSSQL2012, however right now my customer cannot change the environment. Is there any workaround for this? Any driver or modification we can do to run it on 2008?

Thanks in advance!

**Comment by patrickebates** [comment]
Unfortunately, no.  New commands were introduced in SQL 2012 which are required for PN to work correctly.

Note that you are not required to use a specific edition, though.  Depending on the size of the site and the expected traffic volume, the free Express edition may meet your needs.

**Comment by ablanco442** [comment]
Do you know which is the latest version of PN supporting 2008?

**Comment by patrickebates** [comment]
There has never been a version which supported 2008.  We couldn't make this work until SQL 2012.
