### ISSUE TITLE
MSSQL to MYSQL

### ISSUE THREAD

**Issue by cemmildon** [ProjectNami/projectnami#166]
Hi, I want to place on Mysql because some plugins are doesn't support MsSql. How can I do? How can I use wordpress on Mysql with any lost file ?

**Comment by patrickebates** [comment]
Use the Export and Import options with WordPress to migrate your site.

**Comment by cemmildon** [comment]
Why? I can't understand. And 4.7 is available now ?

**Comment by patrickebates** [comment]
Yes, support for 4.7 is now available.

If you are asking if you can run Project Nami on MySQL, the answer is no.  You want to use basic WordPress.  If you need to move data from a PN site to WP, use the Export and Import options.
