### ISSUE TITLE
Version 1.5.0 ( WP Version 4.7 ) - Plugin activation failed due to Fatal Error

### ISSUE THREAD

**Issue by mrjonliu** [ProjectNami/projectnami#170]
On our testing sandbox running PN 1.5.0 and WP 4.7 I received the following fatal error when trying to activate The Events Calendar 4.4.0.1

_"Plugin could not be activated because it triggered a fatal error."_

**I was able to get this error from our sys admin:**
_Update Failed: Fatal error: Call to undefined method Tribe__Events__Featured_Events__Query_Helper::add() in E:\wp-sqlsrv\staging\sandbox\wp-content\plugins\the-events-calendar\common\src\Tribe\Main.php on line 237_

**And this is the code I see there:**
_tribe( 'tribe.asset.data' )->add( 'tribe_l10n_datatables', array(..._

Any suggestions?

**Comment by patrickebates** [comment]
It's going to be some sort of issue with MySQL specific syntax.  In order to have some insight into exactly what is happening, we need to see the translation log.  You can enable this by adding an AppSetting to web.config or in IIS.

Setting
ProjectNamiLogTranslate
Value
1

This will produce a log of all SQL translation attempts in the same location as your php_error.log

**Comment by mrjonliu** [comment]
Well... my server contact gave this a shot, but it took down the entire web server and he cannot access it to undo.  Think we're gonna have to figure out some issues there first and then get back to the log troubleshooting, unless you've got access to a sandbox and can trying installing the plugin and viewing the logs, or if you have any other suggestions for next steps to troubleshoot.

**Comment by patrickebates** [comment]
What environment was this running on?  Our deployment scripts for Azure Web Apps set this feature on by default, so I'm curious what might be so different about your setup that could cause such a failure.

**Comment by mwilliams42** [comment]
The Debug Bar plugin helped my find the problems I was having in that plugin.
