### ISSUE TITLE
Media Library Search Returning No Items Found.

### ISSUE THREAD

**Issue by DeanoFino** [ProjectNami/projectnami#174]
I love Project Nami, and for the most part it works amazing. I have recently noticed (v 1.5.2 - have not yet checked previous versions), that the media library search is not returning any media items, even with exact titles entered into search. Everything else in the media library seems to work just fine...Any thoughts?

**Comment by patrickebates** [comment]
Yes, we committed a fix for this to Master within the last day or two.  Preparing to release a new version shortly.  In the meantime, you can look at the commit history if you want to apply the fix immediately.

**Comment by DeanoFino** [comment]
Oh sweet. Thanks for the quick update! I think I can wait for your new version, just wasn't sure if it was a problem or not/you guys were aware. Thank you for all your hard work on this project. It has opened up quite a few doors that were closed before :).

**Comment by DeanoFino** [comment]
Actually, I was too curious. Found your commit and fix. Works awesome.

**Comment by patrickebates** [comment]
This was released in version 1.5.3
