### ISSUE TITLE
Support for Schema

### ISSUE THREAD

**Issue by guillaumechervet** [ProjectNami/projectnami#175]
Hi,

Is it possible to select an SQL server Schema different from "dbo."?
for exemple "test."
I would like to use another one.

Regards,

Guillaume.

**Comment by patrickebates** [comment]
The schema is not specified in the setup routines.  What about assigning "test" as the default schema for a new DB user, and then using that login for installation?

**Comment by guillaumechervet** [comment]
Thank you for your answer !
