### ISSUE TITLE
Big Problem Translations.Php

### ISSUE THREAD

**Issue by cemmildon** [ProjectNami/projectnami#176]
I searched many plugins for polls. And I downloaded wp Polls plugin. Something wrong. Then I removed plugin. Now I have a big errors. This problems on everywhere. My visitors can see it. Please help quickly.

`Warning: preg_replace(): Compilation failed: missing ) at offset 482 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 483 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 483 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 481 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 482 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 482 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 482 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 483 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 483 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 488 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 489 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 489 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 483 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 484 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

Warning: preg_replace(): Compilation failed: missing ) at offset 484 in D:\home\site\wwwroot\wp-includes\translations.php on line 1454`

**Comment by patrickebates** [comment]
Looks like you are on Azure Web Apps.  Have you tried re-deploying the files?  In the Azure portal, first select your Web App.  Then Deployment Options.  Click on the current deployment.  At the top click Redeploy.

**Comment by cemmildon** [comment]
Yes I tried. My problem didn't solve. And I created a new app from Azure. I replace all my files

**Comment by klompenrunner** [comment]
This the same issue as #169, I did more digging, teh fix is documented in #169.

**Comment by patrickebates** [comment]
Leave a comment
