### ISSUE TITLE
db wrong Encoding?

### ISSUE THREAD

**Issue by Neznaykas** [ProjectNami/projectnami#177]
Hi. I just install, ProjectNami

And it's work fine but, when i look in my darabase tables

`SELECT * FROM wordpress.dbo.wp_posts`

I see 
![image](https://cloud.githubusercontent.com/assets/8024172/22187852/03938a52-e159-11e6-8524-859cebc211e9.png)

Р§РµСЂРЅРѕРІРёРє

I set database collation name

Cyrillic_General_CI_AS
and try
SQL_Latin1_General_CP1_CI_AS

but without result, how i can fix this...this wrong encoding in database?

**Comment by patrickebates** [comment]
Is this a local install, or on Azure Web Apps?

**Comment by Neznaykas** [comment]
local install

**Comment by patrickebates** [comment]
For this to work, you will need to start the install over.

You need to add the following command into your PHP environment before starting the install of Project Nami.

`putenv("ProjectNami.UTF8=1")`

Please let us know if this resolves the issue of reading the data directly in the tables.

**Comment by Neznaykas** [comment]
Thank you. Now all work good.

**Comment by patrickebates** [comment]
Thanks for the feedback.  We added that hidden option a couple of builds back, but can't make it a hard setting as it would break older installs.

Now we will work on making it the default for new installations, and provide a way to disable it for reinstalls/migrations.
