### ISSUE TITLE
unable to send email

### ISSUE THREAD

**Issue by epieters** [ProjectNami/projectnami#178]
I'm unable to send emails from my project nami based installation on azure.
I'm using Contact 7 in combination with WP Email SMTP
The test in WP Email SMTP works fine (email is send and recieved)
I've enabled the WP Email SMTP toggle button to always use SMTP.
Neither native wp emails (i.e. Lost Password) nor emails from Contact 7 are sent.

Can you suggest a form module or other approach that is able to send emails?

**Comment by epieters** [comment]
Sounds like I need to switch to another option (most likely self-hosting on an azure VM) and move away from project nami.

**Comment by patrickebates** [comment]
Have you tried using the free SendGrid account available with Azure and the SendGrid plugin?  I think on many levels you will find that necessary regardless of using a VM or Web Apps, and regardless of using PN or vanilla WordPress.  The outgoing IPs used on Azure are set up properly for sending email by default, and some blacklists out there have flagged the entire IP ranges used by Azure.

**Comment by epieters** [comment]
The free sendgrid account + sendgrid plugin work OK.
Thx.
