### ISSUE TITLE
get_posts fails when orderby not specified

### ISSUE THREAD

**Issue by williamw3** [ProjectNami/projectnami#18]
I ran into a problem with a theme that hooks into posts_orderby and doesn't return a value in all cases. This causes get_posts to fail with a SQL error because OFFSET FETCH isn't valid without an ORDER BY clause.

In this case I think it's a bug in the theme to not be returning the original value for $orderby, but I assume the same thing would happen if get_posts is called with the orderby parameter set to 'none'.

Seems like in these cases get_posts needs to either not do paging or use the default ordering by post_date.

**Comment by patrickebates** [comment]
Updated two locations in Query which could set $orderby to blank.  Could you please test the new /wp-includes/query.php from the Master branch with your theme and let us know the outcome?

**Comment by williamw3** [comment]
Yep, that solves it. Thanks for the quick response.
