### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by uwbadgerdev** [ProjectNami/projectnami#185]
Hi,

Where can I find the SQL scripts (and any other scripts) necessary to manually install Project NAMI? I am hitting a permissions error (most likely because of the Azure setup my user is in - can't change that) that is preventing "Deploy to Azure" from working. I can manually create and setup everything PN needs so if I had the necessary install scripts it would be really helpful.

Thanks!

**Comment by patrickebates** [comment]
So you don't need standalone SQL scripts; everything is baked into the WP installation routine.

Assuming you are planning to use Azure Web Apps, all you need is an instance and an Azure SQL DB.  Here's details on doing it in the old portal.  Just adjust for the new portal.

http://projectnami.org/deploying-project-nami-to-windows-azure-web-sites/
