### ISSUE TITLE
WP EasyCart Tabe Install

### ISSUE THREAD

**Issue by noahwebster** [ProjectNami/projectnami#186]
It seems when trying to setup this plugin, the following tables will not run/install properly: ec_address, ec_affiliate_rule, ec_affiliate_rule_to_affiliate, ec_affiliate_rule_to_product

Has anyone encountered a workaround for this?

**Comment by patrickebates** [comment]
Been several months since I last looked at EasyCart, but there are numerous MySQL-specific calls within the plugin which have no replacement in SQL Server.  The plugin won't work with PN.
