### ISSUE TITLE
post is not stored properly which contains non-ascii characters 

### ISSUE THREAD

**Issue by finejustice** [ProjectNami/projectnami#187]
Hi. I'm testing project nami in azure.

when I try to publish a post which contains non-ascii chars(in other words some asian chars) is not stored properly and have wrong chars instead of original chars.
e.g. 가나다라(input) -> e��a�?a�?e??e�?a�?a�� (data in db)

also, it have a problem of displaying it.
I opend the database with Visual Studio and edited it manually. 
but wordpress still does not show correct strings.
e.g. 가나다라(db) -> ???????? (wordpress)

I suspect these problem comes from encoding differences between web pages and database.
typical wordpress page is encoded in UTF-8 and stores text in db with same encoding, while MS-SQL nvarchar stores chars in UTF-16.

**Comment by patrickebates** [comment]
When PN was first created, we ran into problems with the SQL driver when setting UTF-8, so we went without it.  PN works fine this way, unless you need to access the data directly in the DB.  You can manually change encode processing in your app to treat is as UTF-8, but it's a bit cumbersome.

We have a workaround for this, but you will need to start over with a fresh site.  This will become the default setting in Project Nami soon.  We're testing the best way to implement it without breaking older installations.

With a fresh install into an Azure Web App, and before you start the WordPress installation, you need to add the following App Setting in the Azure Portal.

Name
ProjectNami.UTF8
Value
1

This will enable the UTF-8 support in the SQL driver, which appears to be working as expected.

**Comment by finejustice** [comment]
thanks. 
it works like a charm.
