### ISSUE TITLE
Database upgrade also required for Nami 1.5.4 (Wordpress 4.7.2) ???

### ISSUE THREAD

**Issue by realAngryAnalytics** [ProjectNami/projectnami#189]
I unfortunately was not getting the sync option in Azure to upgrade to latest Nami... so i chose to replace files in my wwwroot and then overwrote the wp-config.php with the old one. Maybe that was a mistake?

I am being told i need to upgrade the database to login to admin portal. I am assuming if i click the update button it will simply break. the wp_admin/upgrade.php script is only showing references to MySQL...

so what do i do? any help is greatly appreciated... thanks. I already have an azure sql db as the backend

**Comment by patrickebates** [comment]
Did you download PN 1.5.4 from this GitHub repo and use those files to update your site?  If so, then any DB update should be correct.

**Comment by realAngryAnalytics** [comment]
yes, that appeared to work. I was just making sure before i clicked... thank you. and thank you for maintaining such an awesome product!

**Comment by summer600** [comment]
Did the upgrade from a gallery install just an hour ago. Added the repo which did a build and upgraded my site from 1.1.1 tot 1.5.4. I too had the database upgrade question but felt secure since I backup the database and the entire site before trying to upgrade :-| A very smooth upgrade indeed.

**Comment by patrickebates** [comment]
Was that a fairly old Gallery install of version 1.1.1?  We finally got the Gallery updated with a much newer build just before Ignire 2016.

**Comment by summer600** [comment]
Yes it was. I installed it in Juli 2016. But it has been running without any problems since then. Just updated to try the deployment options.
