### ISSUE TITLE
WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'WHEN'

### ISSUE THREAD

**Issue by DeanoFino** [ProjectNami/projectnami#194]
ProjectNami Version 1.5.5

The following error occurs when translating a MySQL insert statement...

`[09-Mar-2017 04:12:46 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'WHEN'. Code - 156 for query MERGE INTO  wp_advads_impressions  WITH (HOLDLOCK) AS target USING (SELECT 2397 as ad_id,1703100806 as timestamp,1 as count) AS source (ad_id, timestamp, count) ON (source.ad_id=target.ad_id AND source.timestamp=target.timestamp AND source.count=target.count) WHEN MATCHED THEN UPDATE SET  WHEN NOT MATCHED THEN INSERT (ad_id, timestamp, count) VALUES(2397, 1703100806, 1); made by do_action('wp_ajax_advanced-ads-tracking-track'), WP_Hook->do_action, WP_Hook->apply_filters, Advanced_Ads_Tracking_Ajax->track, Advanced_Ads_Tracking_Util->track_impression, Advanced_Ads_Tracking_Util->persist`

Is it possibly the run on between `WHEN MATCHED THEN UPDATE SET  WHEN NOT MATCHED THEN INSERT`?

Instead of `WHEN MATCHED THEN UPDATE SET`...

Then

`WHEN NOT MATCHED THEN INSERT`...

See http://stackoverflow.com/questions/32917743/how-to-use-merges-when-not-matched-to-insert-a-new-record-in-same-table

**Comment by patrickebates** [comment]
It looks like the commands for the SET statement are missing.  And looking at the statement in full, I don't understand why there is an attempt to SET anything on match.

Any idea what this plugin might be attempting to do with the UPDATE SET?

**Comment by patrickebates** [comment]
Disregard that question.  It looks like this MERGE statement is being constructed within wpdb.  I think the problem is that there is nothing to update as all of the fields are in the lookup.

I'll look at the query and see what steps we can take.

**Comment by patrickebates** [comment]
Any chance you have the translation.log for this query attempt?  Would help me to narrow down exactly which function created the issue.  Thanks.

**Comment by DeanoFino** [comment]
Thanks for the quick response!

Yeah, it's an ad tracking plugin that is trying to do an insert or update on a click or impression table.

I was looking for the translation.log, but couldn't find it. It is on a local IIS web server not Azure (I saw the pp Setting of ProjectNamiLogTranslate with a value of 1 for Azure). Do you have any insight on if there would be one or where it would be located? 

I could probably run down the MySQL query from examining the plugin itself otherwise, or try moving the site into an azure instance if the local IIS doesn't have a translation.log...

**Comment by DeanoFino** [comment]
Ok I found a translate.log in that same Windows Temp folder as the PHP error log but nothing inside of it references that plugin query...

**Comment by patrickebates** [comment]
That's what I needed to know.  It's not in the translations but a bug in core.  Having nothing to be updated is not expected behavior.  I'll think about a fix.

**Comment by DeanoFino** [comment]
ok thanks Patrick!

**Comment by patrickebates** [comment]
Please see the following commit which I believe will fix this issue.  Any chance you could test?

https://github.com/ProjectNami/projectnami/commit/1a08ba96bf72cf7751c45796f5c85556a75f1e41

**Comment by DeanoFino** [comment]
Definitely! Will test today! Thanks Patrick, you da man!

**Comment by DeanoFino** [comment]
It's a no go for my particular issue at least. The PHP errors still show up. Even though there is nothing in the translation.log, it seems like the issues might be related to wp-includes\translations.php.

At least the error changes when I alter these statements in translations.php lines: 2023 - 2057.

`		$on = ' ON (' . $on . ')';
		$newsql .= $on . ' WHEN MATCHED THEN UPDATE SET ';
	
		
		/* Create UPDATE part of command. */
		$update = '';
		for ($i=0; $i<$updatefieldssize; $i++) {
			if ($update == '') {
				/* Does the value contain the actual fieldname?  If so, use the insert value. */
				if (trim($updatefieldvalues[1][$i]) == trim($updatefieldvalues[2][$i])) {
						for ($j=0; $j<$fieldnamessize; $j++) {
							if (trim($insertfields[$j]) == trim($updatefieldvalues[1][$i]))

								$update  .= trim($updatefieldvalues[1][$i]) . "=" . trim($insertvalues[$j]);
			
						}
				} else
					$update  .= trim($updatefieldvalues[1][$i]) . "=" . trim($updatefieldvalues[2][$i]);
			} else {
				/* Does the value contain the actual fieldname?  If so, use the insert value. */
				if (trim($updatefieldvalues[1][$i]) == trim($updatefieldvalues[2][$i])) {
						for ($j=0; $j<$fieldnamessize; $j++) {
							if (trim($insertfields[$j]) == trim($updatefieldvalues[1][$i]))
								$update  .= "," . trim($updatefieldvalues[1][$i]) . "=" . trim($insertvalues[$j]);
			
						}
				} else
					$update  .= "," . trim($updatefieldvalues[1][$i]) . "=" . trim($updatefieldvalues[2][$i]);
				
			}
			
		}
		$newsql .= $update . ' WHEN NOT MATCHED THEN INSERT (' . $insertgroups[2] . ') VALUES(' . $insertgroups[3] . ');';
		return $newsql;
	}`

**Comment by DeanoFino** [comment]
No go for my issue at least. Still get the PHP errors and no data inserted into the tables. 

Even though no translate.log entries, I think it might be related to wp-incles\translations.php.

At least the error changes when I alter the message on translations.php lines 2024 and 2055.

`2024:    $newsql .= $on . ' WHEN MATCHED THEN UPDATE SET ';`
`2055:    $newsql .= $update . ' WHEN NOT MATCHED THEN INSERT (' . $insertgroups[2] . ') VALUES(' . $insertgroups[3] . ');';`

**Comment by patrickebates** [comment]
Another commit for this, this time to the spot in translations.php which you pointed out.

https://github.com/ProjectNami/projectnami/commit/ddecc19980de1b6166c0820c63b6ce0b41a1dcf6

**Comment by DeanoFino** [comment]
Awesome, so that fixed the PHP errors, and the data is able to insert into the table the first time. Just now the updates to the records (count of ad clicks and impressions) aren't coming through. 

Think it might have something to do with the 'ON DUPLICATE KEY UPDATE' query of the plugin...

`$query = "INSERT INTO `$table` (`ad_id`,`timestamp`,`count`) VALUES ($id, $timestamp, $impressions) ON DUPLICATE KEY UPDATE `count` = `count` + $impressions";`

I'll play with the query in the plugin and see if I can modify it to work. Thanks again for all your help.

**Comment by patrickebates** [comment]
The problem appears to be that the translator isn't able to parse the parameters of the UPDATE statement. Now that I source query to work from, I'll see if I can learn why it is failing.

**Comment by DeanoFino** [comment]
OK cool thanks again Patrick. 

It looks like there are two column candidate keys that together act as a primary key in SQL Server (timestamp and ad_id). This could be the root of the problem as to why the UPDATE statement is failing...Not sure if this is an edge case or not that PN may or may not want to support?

It appears I can bypass the UPDATE failing problem by adding an auto increment int column as primary key in SQL Server, and remove the UPDATE statement in the query, forcing all INSERTS.
