### ISSUE TITLE
Install to Subfolder of Existing Azure Website

### ISSUE THREAD

**Issue by petrospk** [ProjectNami/projectnami#195]
Your "Deploy to Azure," feature works brilliantly.  However, do you offer any documentation on how to install ProjectNami within a sub-folder of an existing Azure Website?

**Comment by patrickebates** [comment]
The times I've needed to do this (for example, in a /blog/ folder), I just upload the files via FTP.  When we release updates, I download the ZIP, decompress locally, and update via FTP.

**Comment by petrospk** [comment]
Tried this and followed your video tutorial to configure Azure services.  Worked perfectly.  Thank you much!
