### ISSUE TITLE
Translation.php errors with certain plugins

### ISSUE THREAD

**Issue by zoopercat** [ProjectNami/projectnami#197]
I'm not a developer, so forgive me if I use terms wrong, or if I don't have enough information. Feel free to request more details.

My site is at www.askthefoodgeek.com. I am using the genesis theme, however I have tested this on the official wordpress twentysixteen theme and disabled all addons, just to rule that out.

I am trying to install Thrive Leads. It installs but then any visual editors that are supposed to load to let me make a form, load a blank page. The page is literally blank (inspecting the html shows no code at all). This happens with other addons, like 'contact me' forms. Anything that opens a visual editor seems to be causing a problem.

I have project nami updated (I just checked again on 3/18). My theme is updated, and I am using version 1.95.13 of Thrive leads.  Here's a link to the product, and I'm happy to give you my key if you need to test it (it's not in use right now). https://thrivethemes.com/leads/

I get errors like this:
Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1261 Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1454 Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1261 Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1454 Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1261 Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1454

**Comment by patrickebates** [comment]
I suspect this is a plugin which creates its own tables in the database.  Those are the biggest problem for PN because there are so many different ways to write a CREATE TABLE statement for MySQL that are not compatible with SQL Server.

If you could direct us to a download of the plugin files, we can check for this issue.

**Comment by zoopercat** [comment]
Here is a link to the file in my dropbox:
https://dl.dropboxusercontent.com/u/58652057/thrive-leads-1.95.13.zip

And here's the key (there isn't a free version, not sure if you needed to
activate it in a test or not). AF750-57079-0F520-8AB52-2AEAD

Also, thanks :) :)

**Comment by patrickebates** [comment]
Stripped out your link and key as this is a public forum.

I'll try to take a look at the plugin soon.

**Comment by zoopercat** [comment]
Ooops, thanks. I thought replying to the email would make it private - shows you how much I use github. TY.
