### ISSUE TITLE
Add SQL translation for MySQL's GROUP_CONCAT

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami#20]
I ran into this with a plugin recently. We should look into the feasibility of adding translation support for this.

**Comment by yorek** [comment]
Another option could be to simple use the GROUP_CONCAT SQLCLR extension available here: https://groupconcat.codeplex.com/

**Comment by patrickebates** [comment]
Now that Azure SQL V12 supports CLR, that may be the better option.  Let's set up a prototype and see how this works.  Perhaps we can begin solving other functions via CLR is this is successful.

**Comment by yorek** [comment]
Do you need some help?

**Comment by pippercameron** [comment]
Would you like to run some tests on the CLR UDA you linked to above and share the results here, @yorek? :)

**Comment by yorek** [comment]
Sure :) I'll run the tests and let you know the outcomes

**Comment by yorek** [comment]
Test done, it work like a charm :) From the installation scripts only the USE statement and the section to enable SQLCLR has to be removed and that's it. It works :)

**Comment by yorek** [comment]
I tested the latest available version of GROUP_CONCAT: 
GROUP_CONCAT SQL Server CLR 1.00.23696

**Comment by yorek** [comment]
I've checked PN source code and I haven't found any mention to GROUP_CONCAT execpt into the wp-db.php files, where it just check for its support or not. Where it should be used also?

**Comment by pippercameron** [comment]
Thanks a bunch for testing this! I think the next step is to write up an installation script for this and incorporate it into PN Core.

**Comment by yorek** [comment]
If there isn't much hurry I can do that during summer time

**Comment by yorek** [comment]
Hi, I'm ready to help. As said before, I haven't found any mention to GROUP_CONCAT (except in the wp-db.php to verify if it supported or not) in the source files. Where it's supposed to be used? Only in plugins? Or I'm missing something?

**Comment by yorek** [comment]
If it's a plugin issue only, can you tell me which plugin you used in order to generate the error? Thanks!

**Comment by patrickebates** [comment]
CLR has been banned from Azure SQL DB due to a security concern.  We'll have to revisit this at some point in the future.

**Comment by pippercameron** [comment]
Closing this out for now. Thanks, guys.
