### ISSUE TITLE
Issues with CloudFlare plugin

### ISSUE THREAD

**Issue by evilzenscientist** [ProjectNami/projectnami#200]
Does anyone have CloudFlare plugin running on PN?

I'm back to looking at broken plugins - and for some reason this seems to either be Azure/IIS related or PN.

Cloudflare plugin throws a 406 error - with an invalid URL to read the config.js

The plugin creates this:

        opts.url = absoluteUrlBase + opts.url + '?ver=' + versionNumber;

and that gets mungled somewhere so that absoluteUrlBase+opts.url is a much shorter version of the actual azure url.

I suspect this is part of the cleanup logic in the plugin - and it comes from here:

In wp_options table my siteurl and home are https://shortname.azurewebsites.net but I've overridden them in wp-config.php for the correct site name.

Question is - is this from PN or from Azure/IIS itself?

**Comment by patrickebates** [comment]
So my first question.  Why are you overriding those values in wp-config rather than simply editing them in General Settings?

**Comment by evilzenscientist** [comment]
Staging, SQL and habit.

- - Martin
________________________________

**Comment by patrickebates** [comment]
Can you offer examples of the mangled and expect URLs?  Is it different in the DNS portion, or the path?

**Comment by evilzenscientist** [comment]
Dns.

base URL is foo.azurewebsites.net and that gets stripped to FOO:80

- - Martin
________________________________

**Comment by evilzenscientist** [comment]
I moved back to SLES on Azure IaaS - sorry @patrickebates 

I've still got multiple sites on PN - but this one just needed to work. I'll keep chipping away at the translations. Maybe there is a community building here that would consider working on a plugin list "known good", "works with some issues" and "borked"

**Comment by patrickebates** [comment]
Understood.  I already have a love/hate relationship with CloudFlare and unrelated projects anyway.

Let me flip the question around a bit.  What are your goals with using CloudFlare in the first place?

**Comment by evilzenscientist** [comment]
tbh the biggest reason to move back to IaaS was 'another plugin that needed coaxing'.

Cloudflare was the straw that broke the back.

Use case for CF is as other projects - push the front door to someone else's CDN.

- - Martin
________________________________

**Comment by patrickebates** [comment]
By any chance did you test our Blob Cache platform?
