### ISSUE TITLE
Cannot run on Redhat Apache2.4

### ISSUE THREAD

**Issue by arnoldpalar** [ProjectNami/projectnami#201]
Hi,

I try to setup projectnami on Redhat Apache2.4. After setting up the SQLServer PHP driver and DB credentials on wp-config. It kept on loading when I try to access it

**Comment by patrickebates** [comment]
I've only tested this myself on Ubuntu with Apache, but it just worked.  Is there a reason you manually added credentials to wp-config rather than proceeding through setup?

**Comment by arnoldpalar** [comment]
Hi @patrickebates ,

I missed some steps I think, I set it up on Redhat Apache2.4 installed on Windows. By "proceeding through setup? did you mean after pointing Apache web root to projectnami root folder, I just simply access it and the setup will start to proceed including the DB setup?

Thanks for replying and sorry if this was a stupid question :)

**Comment by patrickebates** [comment]
Yes, though I think you will find that you may need to expand permissions to complete setup.

**Comment by arnoldpalar** [comment]
it's progressing now, at least i found another error message :)
so have setup the SQLSrv extension on my php.ini file like this
```
[PHP_SQLSRV]
extension=php_sqlsrv_7_ts_x64.dll
extension=php_pdo_sqlsrv_7_ts_x64.dll
```

And restarted the apache server. I have all of the dll files on <php_home>/ext/
but it's still displaying "Your PHP installation appears to be missing the SQLSrv extension which is required by Project Nami."
did I put wrong SQLSrv dll files?

**Comment by patrickebates** [comment]
I can't help but wonder if you're making it harder than it needs to be.  Have you see the following instruction for RHEL?
https://www.microsoft.com/en-us/sql-server/developer-get-started/php-rhel

**Comment by arnoldpalar** [comment]
Hi Patrick,

Found out that the .dll files from https://www.microsoft.com/en-us/download/details.aspx?id=20098 somehow didn't work. Downloaded the dll file from https://pecl.php.net/package/sqlsrv/4.1.7preview/windows and it works

Thank you Patrick!
