### ISSUE TITLE
Fatal error: Uncaught Exception: Insert query error - <b>[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'advanced'

### ISSUE THREAD

**Issue by TOGROOW** [ProjectNami/projectnami#203]
The following error occurs when i install Revolution Slider Plugin on Kleo Theme

Fatal error: Uncaught Exception: Insert query error - <b>[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'advanced'.</b><br>---<br> Query: INSERT INTO [wp_revslider_css] ([handle], [settings], [hover], [params], [advanced]) VALUES (&#039;.tp-caption.MarkerDisplay&#039;, &#039;{&quot;translated&quot;:5,&quot;type&quot;:&quot;text&quot;,&quot;version&quot;:&quot;5.0&quot;}&#039;, &#039;{&quot;color&quot;:&quot;#ff0000&quot;,&quot;text-decoration&quot;:&quot;none&quot;,&quot;background-color&quot;:&quot;transparent&quot;,&quot;background-transparency&quot;:&quot;1&quot;,&quot;border-color&quot;:&quot;transparent&quot;,&quot;border-style&quot;:&quot;none&quot;,&quot;border-width&quot;:&quot;0&quot;,&quot;border-radius&quot;:[&quot;0px&quot;,&quot;0px&quot;,&quot;0px&quot;,&quot;0px&quot;],&quot;skewx&quot;:&quot;0&quot;,&quot;skewy&quot;:&quot;0&quot;,&quot;scalex&quot;:&quot;1&quot;,&quot;scaley&quot;:&quot;1&quot;,&quot;opacity&quot;:&quot;1&quot;,&quot;xrotate&quot;:&quot;0&quot;,&quot;yrotate&quo in D:\home\site\wwwroot\wp-content\plugins\revslider\includes\framework\functions.class.php on line 14

Thanks for your help

**Comment by patrickebates** [comment]
Please see if the notes here help your issue.

https://github.com/ProjectNami/projectnami/issues/81

**Comment by TOGROOW** [comment]
Thanks, a lot, i will see that.
