### ISSUE TITLE
Performance / Sizing

### ISSUE THREAD

**Issue by nhaberl** [ProjectNami/projectnami#204]
Just would like to know if there are any general recommendations for sizing the system when using NAMI ?
RAM, DB Size and so on.

It's just for personal sites with appx. 10000 views a month.

I have no experience in WP but with MSSQL support I would like to give it a chance.

Thanks Norbert

**Comment by patrickebates** [comment]
You can run a site like that on next to nothing.  For example, a Small Azure Web App and a Basic Azure SQL DB would be overkill, though you can't go any smaller reliably.  Those stats are 1 core, 1.75GB RAM, 10 GB file storage, 5GB DB space.
