### ISSUE TITLE
"Deploy to Azure" button not working

### ISSUE THREAD

**Issue by VickeyC** [ProjectNami/projectnami#205]
I created a new Azure account this morning and logged in.   When I click the "deploy to Azure" button [http://projectnami.org/download/] the "Deploy To Azure" page [https://deploy.azure.com/?repository=https://github.com/ProjectNami/projectnami/tree/latest#/form/setup] opens but never progresses past the setup step.   Any idea why this would occur?

**Comment by patrickebates** [comment]
Couple of questions come to mind.  First, what data center were you attempting to deploy into?  Second, where exactly does it stop, what is the last message seen?

**Comment by VickeyC** [comment]
I'm sorry, I should have been a little more specific.   The page I'm seeing doesn't provide me with any options to select a data center -- I'm guessing that the page is still trying to build.  I don't get any messages, just a spinning circle.   Please see the attached screenshot.
![2017-04-17](https://cloud.githubusercontent.com/assets/19691403/25103700/278614cc-2383-11e7-94be-ff2ff21eb64f.png)

**Comment by patrickebates** [comment]
I'm unable to duplicate this.  The Setup panel loads properly for me.

Perhaps try a different browser, or try in Private mode?

**Comment by VickeyC** [comment]
I tried Chrome, Edge, and Incognito mode.  Any other suggestions?

**Comment by patrickebates** [comment]
Is there anything about your account which might be unusual?  We've had reports of issues related to accounts which were attached to multiple Azure Active Directories, but those issues occurred after submitting the form on this page.

This page is operated by Azure under the Slingshot project.  I may need to file a report with them, but only once I know what to report.

You may want to look at a manual deploy to an Azure Web Site.  We have a video on our site which details the steps in the older portal.  It is applicable to the current portal, though the appearance has changed.

**Comment by VickeyC** [comment]
I wondered about that too.   I am doing some work for a charity and the director just set up the account this morning.   I'll try to create something else and see what happens.

**Comment by VickeyC** [comment]
The account setup was the problem!  A login had been created, but the account didn't have a subscription set up.   I installed this successfully using my account with an active subscription.   

Thanks for your help!
