### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function mysql_error()

### ISSUE THREAD

**Issue by TOGROOW** [ProjectNami/projectnami#207]
Hi and thank for your support

Plugin: Match Me for BuddyPress

The following error occurs when i install Match Me For BuddyPress

Fatal error: Uncaught Error: Call to undefined function mysql_error() in D:\home\site\wwwroot\wp-content\plugins\match-me-for-buddypress\mp-settings.php:52 Stack trace: #0 D:\home\site\wwwroot\wp-content\plugins\match-me-for-buddypress\mp-settings.php(78): WeDevs_Settings_API_Match->hmk_build_field_options() #1 D:\home\site\wwwroot\wp-content\plugins\match-me-for-buddypress\mp-settings.php(24): WeDevs_Settings_API_Match->get_settings_fields() #2 D:\home\site\wwwroot\wp-includes\class-wp-hook.php(298): WeDevs_Settings_API_Match->admin_init('') #3 D:\home\site\wwwroot\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 D:\home\site\wwwroot\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #5 D:\home\site\wwwroot\wp-admin\admin.php(154): do_action('admin_init') #6 {main} thrown in D:\home\site\wwwroot\wp-content\plugins\match-me-for-buddypress\mp-settings.php on line 52

Thanks for your help

**Comment by patrickebates** [comment]
From the error above, it appears that the plugin is attempting to communicate directly with the database via MySQL objects.  This won't work with PN at all.

Furthermore, it appears that the MySQL_error function simply doesn't exist in PHP 7 or greater anyway.  The plugin will need to be updated to even work with WordPress.
http://php.net/manual/en/function.mysql-error.php

**Comment by TOGROOW** [comment]
Thanks i will send this info to the plugin developer.
