### ISSUE TITLE
Support for custom domains

### ISSUE THREAD

**Issue by nickplennox** [ProjectNami/projectnami#209]
Does Project Nami support custom domains in the Azure App Service?

For me this is not working - repro steps:

1. Updated DNS for my custom domain to point to my nami install (using CNAME, not A records).

2. In the Azure portal, update the nami App Service as normal - click on "Custom Domains", then click on "Add hostname".
<img width="1143" alt="untitled2" src="https://cloud.githubusercontent.com/assets/2352526/25313844/33d017d6-282f-11e7-9eb1-77ed614626ec.png">

3. On the next blade, enter the custom domain name, choose CNAME record type and validation all succeeds.
<img width="561" alt="untitled3" src="https://cloud.githubusercontent.com/assets/2352526/25313845/3defd1de-282f-11e7-9014-e6bbe9e1c7d3.png">

4. Click on Add hostname and it appears to work, but **no new hostname appears** under "Hostnames assigned to site" in the app service.

5. Try to go to the url of the custom domain, and get the big blue 404 screen "Web app not found" which normally indicates something wrong in IIS in my experience

<img width="927" alt="untitled" src="https://cloud.githubusercontent.com/assets/2352526/25313808/4b39ff82-282e-11e7-8ec0-b67e6ca51ab9.png">

So, is this supported, anything unusual that I need to do that is different under nami than doing this under any other App Service instance?

Thanks!

**Comment by patrickebates** [comment]
PN has nothing to do with your issue at this level.  Yes, you need to inform PN about the custom domain by either updating your site and host entries (and/or enabling multisite), but the error you are seeing above is strictly with Azure.

The Add Hostname button above appears to be greyed out.  I've seen that when the DNS validation fails.

For the record, we configure custom host names all of the time.  Did one yesterday, in fact.

**Comment by nickplennox** [comment]
Hi Patrick,

thanks for this, and when you do custom host names, you just do it through the App Service blade, per my screenshots above, right? If so I'll persevere, maybe something isn't right in DNS. Funny though, the two validations that the blade does both come up with a big green tick!

I'm interested in the comment you make about updating my site and host entries.By that, do you mean the two url's in the WP General Settings page? When I do this, it breaks my WP install - I can't even get back to the *azurewesbites.net site and have to hack the wp_options table 'home' and 'site url' values in the database to be able to get back in...

**Comment by patrickebates** [comment]
Yes, but you only want to do that once you can confirm that the custom domain is working.  When configured correctly, but before you update the WP Settings, when you attempt to reach the site by the custom domain you should get redirected to the currently configured *.azurewebsites.net URL.

**Comment by nickplennox** [comment]
And another update, my custom domain has now appeared - after waiting well over an hour - so perhaps some latency on the MS side.

**Comment by nickplennox** [comment]
So, now that the custom domain appeared in Azure, I just had to change the two urls on the WP General Settings page and I'm seeing my WP site under the custom domain!

Lesson learned here is that sometimes, **Azure can take over one hour to set up your custom domain** before the Custom Domains blade shows the new entry. You need to wait for this to happen before changing any other config in WP itself!

Perhaps part of the reason for this delay was that the custom domain used to belong to another App Service instance...

Thanks for helping me out Patrick, let's chalk this one up to noob user!

Nick
