### ISSUE TITLE
BuddyPress groups and activity cant work after installation.

### ISSUE THREAD

**Issue by TOGROOW** [ProjectNami/projectnami#210]
Hi, and thanks again for your help.

BuddyPress groups and activity cant work after installation.

Do you have any solution?

**Comment by TOGROOW** [comment]
Hi, guys
Do you have any solution?

Thanks

**Comment by patrickebates** [comment]
None at this time.  Do you have anything from either the php_error.log or the translation.log to point us in the right direction?
