### ISSUE TITLE
Installation format for Database fields in wp-config.php

### ISSUE THREAD

**Issue by blachawk** [ProjectNami/projectnami#215]
I downloaded the latest GitHub project of projectnami to get it up and running on my Windows 10, IIS server with Microsoft SQL Server Management Studio version 13.  I also installed the SQLsrv drivers needed. I successfully have my WordPres install screen up and running.  I also have a database and username I created as well.  But for some reason I am failing to get a database connection to complete the installation process. What is the proper formatting for making a database connection to MSSQL?

I have tried the following, but it fails to make a database connection
```
define('DB_NAME', 'wordpress_base_00');`
define('DB_USER', 'sa.wordpress@6VF6SF9');
define('DB_PASSWORD', 'sapassword');
define('DB_HOST', '6VF6SF9.database.windows.net');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
```

What is wrong with my connection process?  Perhaps I'm not formatting something correctly so that project Nami talks to MSSQL?

Thanks in advance  for any tips

**Comment by patrickebates** [comment]
Did you add your public IP address to the firewall rules of your Azure SQL DB?

**Comment by blachawk** [comment]
I'm now using Azure. I am using Microsoft SQL Server Management Studio locally on my Windows 10 machine.

**Comment by patrickebates** [comment]
So you have firewall rules for both your public IP (for SSMS) and the setting for Allow Azure Services (for your web site) ?

**Comment by blachawk** [comment]
No, I just want to play with Nami on SSMS.  And there is no firewall issues.

**Comment by patrickebates** [comment]
I must be missing something then.  What exactly is your problem, SSMS won't connect or the web site won't connect?  The settings you listed appear to be correct for the web site.

**Comment by blachawk** [comment]
My apologizes.  Just to be clear, when I try to connect with the credentials shown above, WordPress tells me "Error establishing a database connection".  I'm assuming that I'm getting that error message because I am not connecting the right way to my sq. server database.

**Comment by patrickebates** [comment]
Local database?  If so, then yes you're formatting is wrong.  You can drop the DB_USER is simply the username and then DB_HOST will be either localhost or (local).

**Comment by blachawk** [comment]
Yes local database.  Ok, I adjusted the connection strings.  The following still does not work...

```
define('DB_NAME', 'wordpress_base_00');
define('DB_USER', 'sa.wordpress');
define('DB_PASSWORD', 'sapassword');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
```

**Comment by patrickebates** [comment]
Is this SQL Express, and if so did you install as the default instance or a named instance?  The host might be localhost\sqlexpress

**Comment by blachawk** [comment]
This is what I have:
![screenshot 2017-05-10 15 54 08](https://cloud.githubusercontent.com/assets/3985279/25918386/3b4b29ca-3599-11e7-8a98-12b891762bcf.png)

SQL Server 2016
Management Studio

**Comment by patrickebates** [comment]
I'm assuming you are connecting to your DB successfully using SSMS.  What server name are you using there?

**Comment by blachawk** [comment]
Yes I'm connecting to by DB successfully for other projects.  The server name is 6VF6SF2

Thank you so much for walking through this with me! I love your product, and can't wait to get it going!

**Comment by patrickebates** [comment]
Then just use that for DB_HOST

**Comment by blachawk** [comment]
I tried :) It does not work for me.

**Comment by patrickebates** [comment]
The same values you use for SSMS should work here.

I guess you could try the fully qualified domain name, and then try the IP address...

**Comment by blachawk** [comment]
No luck.  Thanks for helping though.

**Comment by PHuhn** [comment]
The database connection is as a specific database user which is not the default configuration.  One needs to turn on ‘SQL Server and Windows Authentication mode’.
Right click and select Properties, on the Security tab, change from ‘Window Authentication mode’ to ‘SQL Server and Window Authentication mode’.  Then login SSMS with the database user account.
Note: keep the SA account DISABLED!
The following is my script for creating a db user:
`
USE master;
CREATE LOGIN WordPress481
  WITH PASSWORD = 'WordPress001xyz';
GO
USE WordPress002;		-- change to your db name

GO
CREATE USER WordPress481
  FOR LOGIN WordPress481
  WITH DEFAULT_SCHEMA = dbo;
GO
sp_addrolemember @rolename='db_owner', @membername ='WordPress481' 
sp_addrolemember @rolename='db_datareader', @membername ='WordPress481' 
sp_addrolemember @rolename='db_datawriter', @membername ='WordPress481' 
GO
CREATE USER [NT AUTHORITY\IUSR]
  FOR LOGIN [NT AUTHORITY\IUSR]
  WITH DEFAULT_SCHEMA=[dbo]
GO
sp_addrolemember @rolename='db_owner', @membername = 'NT AUTHORITY\IUSR'
sp_addrolemember @rolename='db_datareader', @membername = 'NT AUTHORITY\IUSR'
sp_addrolemember @rolename='db_datawriter', @membername = 'NT AUTHORITY\IUSR'
GO
`

Good luck!

**Comment by RemarkLima** [comment]
Also, some default installs of sql server do not have TCP/IP enabled by default. Without this, it'll not connect.
