### ISSUE TITLE
Error while using Caldera Forms

### ISSUE THREAD

**Issue by VickeyC** [ProjectNami/projectnami#217]
I'm receiving the following error in a Caldera Forms plugin:  

WordPress database error: [[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid object name 'wp_cf_form_entries'. Code - 208]
SELECT * FROM wp_cf_form_entries WHERE id = 0

Any ideas on how to proceed?

**Comment by patrickebates** [comment]
Looks like this is a plugin which creates its own database tables.  We have table creation translations which happen to match the format used by WordPress itself, but plugins using a different format will fail.

If you were to manually create the tables, the plugin may begin operating.

**Comment by VickeyC** [comment]
Patrick, you were right, I was missing a table.   I manually created the table and the error went away.   If you're interested, the DDL for the missing table (wp_cf_form_entries) resides in the classes/entry/core.php file in the Caldera Forms plugin.   The other 4 tables referenced in this file were created successfully, just not this one.
