### ISSUE TITLE
Increasing the Maximum Upload Size

### ISSUE THREAD

**Issue by TylerK93** [ProjectNami/projectnami#218]
How would you all suggest I go about increasing the maximum media file upload size? On my installation done via the Deploy to Azure system, it is only 8 MB and it needs to be larger for my client's requirements. Thanks!

**Comment by patrickebates** [comment]
You need to add a file .user.ini to the root of the site.  See the following for more information.

https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-php-configure
