### ISSUE TITLE
Yoast SEO Premium Redirects not functioning

### ISSUE THREAD

**Issue by qdi-staceyw** [ProjectNami/projectnami#219]
We were using the Simple 301 redirect plugin for redirects (successfully).  But are switching to use Yoasts offering.  Sadly we can't get that to work.  We've tested removing all other plugins and themes using only the Yoast one.  I've contacted their support and they are not sure why it's not working and asked me to open an issue with ProjectNami.

Do you have any insight as to why the Simple 301 Redirect would work but Yoast's implementation wont.

Many thanks.

**Comment by patrickebates** [comment]
Yes.  This is an IIS problem rather than a PN problem.

https://yoast.com/wordpress/plugins/seo/redirects-manager/

Yoast relies on .htaccess files to perform the redirects and this is not supported on IIS.

**Comment by qdi-staceyw** [comment]
Ah, thank you for your prompt response.
