### ISSUE TITLE
502 Bad Gateway from wp-admin page

### ISSUE THREAD

**Issue by RehanSaeed** [ProjectNami/projectnami#221]
My site at rehansaeed.com works fine but my rehansaeed.com/wp-admin page is returning a 502 Bad Gateway error. I was on version 1.5.8 when I noticed this error but having upgraded to 1.6.0 it still remains. I'm hosting on Azure Web Apps + recently moved to Cloudflare. How can I troubleshoot this?

**Comment by patrickebates** [comment]
It started after configuring Cloudflare?  Does the error stop if you disable Cloudflare?

**Comment by RehanSaeed** [comment]
If I use my *.azurewebsites.net URL I still get the 502. It could be the plugin I suppose. How can I disable the plugin if I can't get to the admin page?

**Comment by patrickebates** [comment]
Using SSMS you can access your wp_options table and look for option_name of active_plugins

You can edit the option_value to remove reference to cloudflare.  Might even be able to delete the entire row if you don't mind disabling all plugins.

When you edit the data, you will need to adjust the array count at the beginning a:? and update the array index values i:?

**Comment by patrickebates** [comment]
Oh, an easier option is to remove or rename the Cloudflare plugin folder.  I just remembered that one.

**Comment by RehanSaeed** [comment]
I've just renamed my entire `plugins` folder and tried to login to `/wp-admin` but I'm still getting a 502 Bad Gateway.

When I navigate to `/wp-admin`, I can sometimes see the login prompt after a really long loading time. When I enter my credentials, it tries to redirect me to `/wp-login.php?redirect_to=https%3A%2F%2Frehansaeed.com%2Fwp-admin%2F&reauth=1` but again fails with a 502 Bad Gateway.

If this is not my plugins, then is this Nami, or my theme messing up? What can I try next?

**Comment by RehanSaeed** [comment]
I've restored from an Azure backup and that seems to have solved my issue. The backup I restored to still has Cloudflare enabled. I've also upgraded all plugins and themes and so far the site is ok. This makes me think it might be a project Nami upgrade?

My Azure deployment source source was pointed at the Project Nami GitHub project. However, those settings seem to have disappeared. What settings do I need to enter to get them back:

![untitled](https://user-images.githubusercontent.com/2270364/27506677-8884070e-58b5-11e7-87de-89cfa145f6a3.png)

When I select GitHub, it wants me to authenticate my personal GitHub account, then shows me my GitHub projects. This could go very wrong if I get this wrong.

**Comment by patrickebates** [comment]
http://projectnami.org/video-updating-project-nami/

Note — If you need to recreate the Continuous Deployment settings, or never had them because you started with the Gallery installation option, you can use the following settings.

Source -- External Repository 
URL -- https://github.com/ProjectNami/projectnami 
Branch -- latest

**Comment by RehanSaeed** [comment]
Back up and running. For anyone else who needs to restore a project Nami project, Azure backup will not work from the Azure portal because it includes SQL Server, you have to use PowerShell.

1. [Install the PowerShell module](https://docs.microsoft.com/en-us/azure/app-service/app-service-powershell-backup)
2. Login to Azure via PowerShell 
```
Login-AzureRmAccount 
```
2. Get the Backup ID from the Azure portal you want to restore to and pass the name of the web app and resource group like so:

```
$backup = Get-AzureRmWebAppBackup -Name 'MyWepAppName' -ResourceGroupName 'MyResourceGroupName' -BackupId 1234567
```

3. Wait for the restore to complete. I wasn't able to figure out a way to find out when the restore completes. PowerShell doesn't give you any feedback, so I waited an hour.

4. Sadly, Azure backup restore blows away the ProjectNami continuous deployment settings, so add these in the Azure portal manually as @patrickebates listed:

Source -- External Repository
URL -- https://github.com/ProjectNami/projectnami
Branch -- latest
