### ISSUE TITLE
Invalid object name 'wp_options'.

### ISSUE THREAD

**Issue by slimmingworlduk** [ProjectNami/projectnami#222]
Azure Alert after deployment completed :

SchemaIssue was detected on your database 'xxxxxxxxxxxxxxx' on server 'xxxxxx' starting at 2017-06-20T13:34:43.323 UTC. 
Subscription: 	xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Server: 	xxxxxxxxxx
Database: 	xxxxxxxxxxxx
Erorr code: 	208

Message: 	Invalid object name 'wp_options'.

**Comment by patrickebates** [comment]
We have no other reports of schema issues since the most recent update.  I'd recommend that you delete the web app and the database and try again.

**Comment by rikishon** [comment]
Hey, i;ve the exact same. Installed Nami yesterday and had exact same alert
