### ISSUE TITLE
Help for install Centos7 and Sql2012

### ISSUE THREAD

**Issue by ppenav** [ProjectNami/projectnami#225]
Hello ! Greetings from Chile!
Project team, these are the characteristics of my installation:

-----
OS:
CentOS Linux release 7.3.1611 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
CentOS Linux release 7.3.1611 (Core) 
CentOS Linux release 7.3.1611 (Core) 

Apache: 
Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 12 2017 21:03:28

Sql Server: version 11.0.5343.0 (SQL Server 2012)

----------------------------------

You could guide me to continue, as the following message is presented to me, Excuse my ignorance.

_"Your PHP installation appears to be missing the SQLSrv extension which is required by Project Nami."_

Thank you in advance.

**Comment by patrickebates** [comment]
Not 100% sure that you can install SqlSrv on CentOS.

Please see the following page for instructions for Ubuntu and RedHat.
https://github.com/Microsoft/msphpsql
