### ISSUE TITLE
Local SQLExpress. Unable to connect to database. 

### ISSUE THREAD

**Issue by swalker1595** [ProjectNami/projectnami#229]
I have the same issue as this:

https://github.com/ProjectNami/projectnami/issues/215

I am unable to connect to the SQL Database.

Here are my configuration settings:

```
// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'WordPress');

/** MySQL database username */
define('DB_USER', 'shane');

/** MySQL database password */
define('DB_PASSWORD', '******');

/** MySQL hostname */
define('DB_HOST', 'localhost\SQLEXPRESS');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');
```

How should I go about troubleshooting the issue?

**Comment by swalker1595** [comment]
This issue may be due to my SQLExpress Server Configuration. I am able to successfully connect if i do not specify a username and grant IUSR permissions to the database.

**Comment by patrickebates** [comment]
When you installed SQL Express, did you configure for Windows Authentication only, or did you also enable SQL Authentication and set an SA password?

Also, should check that TCP is enabled as a connection protocol.  Though it sounds like it may be since you can connect without username.

**Comment by swalker1595** [comment]
I am almost certain that I configure it for windows auth only, now that you mention it. This was not a fresh SQLExpress install. 

I had to manually enable TCP. 

Everything is working correctly.
