### ISSUE TITLE
Revolution Slider Plugin fails to install

### ISSUE THREAD

**Issue by katamshut** [ProjectNami/projectnami#23]
Hi Guys from project Nami

First of all, I really appreciate your effort to move WP to SQL Server!
I lately working on a project who wants to have the revolution slider plugin enabled. This Plugin use creation of tables which unfortunately is not working by Nami 1.0.4. 

I just wanted to give you that hint, without any logs. You maybe will try yourself and try to fix it. Due to time pressure I need to go with clearDB solutions (even if this sucks).

best wishes
Chris

**Comment by patrickebates** [comment]
What version of Revolution Slider is this?  I'm looking at a site right now where 4.6.0 installed successfully.
