### ISSUE TITLE
Error 500 after login

### ISSUE THREAD

**Issue by cesarsouza** [ProjectNami/projectnami#231]
Hi there,

As soon as I try to login to my Project Nami website in Azure, I get an error 500. 

I know that maybe this might be due to other things not necessarily related to project Nami - though I have to say I do not have any other custom things running on this Azure website. Please, may I ask if someone could give any indication on how I could even begin to troubleshoot this issue?

Regards,
Cesar

**Comment by patrickebates** [comment]
Any recent changes to the web.config file?  That's the first place I would start looking.
