### ISSUE TITLE
multisite redirect loop

### ISSUE THREAD

**Issue by hsp1518** [ProjectNami/projectnami#232]
I am trying to set up multisite using v1.6.0 but I keep getting stuck in a redirect loop whenever I try to log into the dashboard of the subsite.  I set up a fresh install and followed the instructions from here [https://codex.wordpress.org/Create_A_Network](url) but the redirect issue persists.  If it matters, I am running it from my local machine via IIS and PHP 5.3.28.  

I have modified my wp-config.php and web.config according to what the "Network Setup" page instructed.

I didn't have a .htaccess file so I created one with the following contents. I have tried many different variations of the following without success.

`RewriteEngine On`
`RewriteBase /newpress/`
`RewriteRule ^index\.php$ - [L]`

`RewriteRule ^newpress/([_0-9a-zA-Z-]+/)??les/(.+) wp-includes/ms-?les.php??le=$2 [L]`

`RewriteRule ^newpress/([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]`
`RewriteCond %{REQUEST_FILENAME} -f [OR]`
`RewriteCond %{REQUEST_FILENAME} -d`
`RewriteRule ^ - [L]`
`RewriteRule ^newpress/([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]`
`RewriteRule ^newpress/([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]`
`RewriteRule . index.php [L]`

Any help would be appreciated!

**Comment by patrickebates** [comment]
Two things.  First, I recommend that you move to a supported version of PHP like 5.6 or 7.  Second, .htaccess isn't supported in IIS.  You need to create a web.config file with the rewrite rules instead.  Including a sample below, though it may not be the most current.

`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="WordPress Rule 1" stopProcessing="true">
                    <match url="^index\.php$" ignoreCase="false" />
                    <action type="None" />
                </rule>
                <rule name="WordPress Rule 2" stopProcessing="true">
                    <match url="^([_0-9a-zA-Z-]+/)?files/(.+)" ignoreCase="false" />
                    <action type="Rewrite"
                            url="wp-includes/ms-files.php?file={R:2}"
                            appendQueryString="false" />
                </rule>
                <rule name="WordPress Rule 3" stopProcessing="true">
                    <match url="^([_0-9a-zA-Z-]+/)?wp-admin$" ignoreCase="false" />
                    <action type="Redirect" url="{R:1}wp-admin/"
                            redirectType="Permanent" />
                </rule>
                <rule name="WordPress Rule 4" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAny">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile"
                             ignoreCase="false" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory"
                             ignoreCase="false" />
                    </conditions>
                    <action type="None" />
                </rule>
                <rule name="WordPress Rule 5" stopProcessing="true">
                    <match url="(^[_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*)"
                           ignoreCase="false" />
                    <action type="Rewrite" url="{R:2}" />
                </rule>
                <rule name="WordPress Rule 6" stopProcessing="true">
                    <match url="^([_0-9a-zA-Z-]+/)?(.*\.php)$" ignoreCase="false" />
                    <action type="Rewrite" url="{R:2}" />
                </rule>
                <rule name="WordPress Rule 7" stopProcessing="true">
                    <match url="." ignoreCase="false" />
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>`
