### ISSUE TITLE
ms sql on wp

### ISSUE THREAD

**Issue by avdomila** [ProjectNami/projectnami#235]
hi, kinda new here. basically i've been trying to run wp with ms sql server 2012. can you point me in the right direction? thanks in advance.

**Comment by patrickebates** [comment]
Well, could use a little more information first.  How far along are you?  Do you have the server ready and just need to install PN, or do you need guidance on preparing the environment as well?

**Comment by avdomila** [comment]
thanks for taking time. i've already installed php then installed wordpress. i thought i installed the latest php 7.1 version but i guess when i installed wordpress it installed php 5.6 and it took over. i could verify this via phpinfo. now, i'm trying to install the SQLSRV extensions. And I have not started to connect the ms sql server which is also already setup with a couple of databases with tables ready. I'm not sure where to start. Kindly advice.

**Comment by patrickebates** [comment]
If memory serves, you should be able to use the Web Platform Installer to install PHP 7.0 (I'd wait on 7.1 for the moment) and the SqlSrv extensions.
https://www.microsoft.com/web/downloads/platform.aspx

Once that's done, you can unpack PN into your web root.  It installs just like standard WordPress.

**Comment by avdomila** [comment]
thanks patrick, I was able to do that successfully just right now. so does this mean I'm already good to go connecting to the ms sql 2012?

**Comment by patrickebates** [comment]
Provided that your SQL Server is set for Mixed Mode authentication (SQL logins) and you have TCP/IP enabled and the firewall port opened (if on a separate machine), then yes you should be good to go.

**Comment by avdomila** [comment]
yup, ms sql server setup is setup exactly mixed mode, tcpip, not default port on a separate machine. i can't seem to verify if sqlsvr is working. i don't see it in phpinfo but i'll work on that. just a few clarification, the php is the one connecting to the ms sql server and wordpress is connecting to mysql? what we are trying to achieve is wordpress connecting to ms sql server. if php is already connecting to ms sql, does that mean the wordpress can connect to ms sql server that php is connection to?

**Comment by avdomila** [comment]
hi patrick, no luck on the sqlsvr :( i've read on one of the comments that "This driver does not work with Microsoft Windows Server 2012" so i tried this "There is a preview version released by Microsoft that is working. You can download it here  - https://github.com/Microsoft/msphpsql/releases/tag/v4.1.8-preview" but does not work :( kindly advice.

**Comment by avdomila** [comment]
thanks. there is already a 7.1 and  i was able to install php 7.1  everything worked, php test script worked "connection established. i could see sqlsrv in phpinfo, etc. what i need to clarify now is, if php 7.1 is already connecting to ms sql 2012, does this mean wordpress is also connecting to ms sql already?

**Comment by patrickebates** [comment]
Sounds like you should be fine then.

**Comment by avdomila** [comment]
hi patrick, i think i'm able to connect php to ms sql but not yet wordpress on ms sql. i'm not sure on how to do this yet. i'll try to edit wp_config.php and change connection variables and see if wp blows up. i'm not sure how wp would migrate/use the ms sql instead of mysql to its core. any inputs would be appreciated?

**Comment by avdomila** [comment]
as expected, after updating the config file i got "Error establishing a database connection". i've used the same connection variables testing php so i'm sure the connection is working.  i tried http://webshare.dupontregistry.net/homes/wordpress/wp-admin/install.php same thing. now, i need help pointing me in the right directions. kindly advice.

**Comment by patrickebates** [comment]
I don't believe I understand where you are starting from.  I am assuming you are performing a fresh installation of Project Nami.  You do need to have an empty database created on your SQL Server for PN to install into.

Where did the existing wp_config.php come from?

**Comment by avdomila** [comment]
my apologies for the confusion. i have installed wordpress via wpi but was able to successfully install PN already. thanks! one question thou, i don't want to clatter my wordpress with my website files, how do i go doing about this? i tried updating the general settings for the wordpress website url and website url, are there anything i need to update as well?

**Comment by patrickebates** [comment]
Sounds like you are looking to migrate an existing WP site to PN.  If so, you need to export your existing site first.  Then, unpack the latest PN release into a clean folder and start the install by opening that location in a browser.  After install is complete, you can import your site data.

**Comment by avdomila** [comment]
right! that obvious ha? hihihi. will do. thanks a bunch. appreciate it.
