### ISSUE TITLE
Local Install Instructions

### ISSUE THREAD

**Issue by PHuhn** [ProjectNami/projectnami#239]
One option for Project Nami is to install on a local Windows computer using SQL Server 2012 or greater.  I have a Windows 10 computer with SQL Server 2016, and have had some success doing just that.  The information available for local installation seem to be quite limited.  I was hoping to get a number of thing from you.  Security is number one in my book.  The first is a sample web.config, that addresses the htaccess security concerns that are suggested, say in the Bullet Proof's secure.htaccess example.

**Comment by patrickebates** [comment]
The local install instructions are limited because they are essentially the same as standard WP on IIS.  The only difference being the use of SQL Server/Express and the need for SQL login support there.  I'd recommend looking at the numerous articles already available regarding WP security on IIS.

**Comment by PHuhn** [comment]
Hi Patrick:

Per the web.config question, this is my first straw version:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>

    <security>
      <!--
        https://docs.microsoft.com/en-us/iis/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig
      -->
      <requestFiltering>
        <denyUrlSequences>
          <add sequence="config.php" />
          <add sequence="readme" />
        </denyUrlSequences>
        <fileExtensions>
          <add fileExtension=".sql" allowed="false" />
          <add fileExtension=".ini" allowed="false" />
          <add fileExtension=".bat" allowed="false" />
          <add fileExtension=".cmd" allowed="false" />
          <add fileExtension=".ps1" allowed="false" />
        </fileExtensions>
      </requestFiltering>
    </security>

    <directoryBrowse enabled="false" />

    <caching>
      <profiles>
        <add extension=".php" policy="DisableCache" kernelCachePolicy="DisableCache" />
        <add extension=".html" policy="CacheForTimePeriod" kernelCachePolicy="CacheForTimePeriod" duration="14:00:00:00" />
      </profiles>
    </caching>

    <defaultDocument>
      <files>
        <remove value="index.php" />
        <add value="index.php" />
      </files>
    </defaultDocument>

    <!--
      https://codex.wordpress.org/Using_Permalinks
      Requires URL Rewrite module installed to IIS by Web Platform installer
    -->
    <rewrite>
      <rules>
        <rule name="Main WordPress Rule" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <!-- add input="{REQUEST_URI}" matchType="Pattern" pattern="^/wp-admin/" negate="true" /-->
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="index.php" />
        </rule>
      </rules>
    </rewrite>

  </system.webServer>
</configuration>

```
Suggestion/comments desired?

Phil

**Comment by patrickebates** [comment]
Off the cuff, I don't see anything wrong with that.  Though you might also consider adding the following directly above `<requestFiltering>`.  I have forgotten the MS document that recommends this, though you may need to adjust the specific values to taste.

```
<dynamicIpSecurity enableLoggingOnlyMode="false">
                <denyByConcurrentRequests enabled="true" maxConcurrentRequests="10" />
                <denyByRequestRate enabled="true" maxRequests="30" requestIntervalInMilliseconds="300" />
            </dynamicIpSecurity>
```

**Comment by PHuhn** [comment]
Hi Patrick:
I eventually got dynamic IP security to work, but I need to do it a 2nd and 3rd time to know for sure.  My notes are as follows:
In Windows: 'Turn Windows features on or off'
World Wide Web Services + Security => check 'IP Security' => click OK (button)
In: Internet Information Service (IIS) Manager
On site click: IP Address and Domain Restrictions
x Deny IP Address based on the number of concurrent requests
x Deny IP Address based on the number of requests over a preiod of time
x Enable Logging Only Mode

Additionally, per your urging found the following instruction which has helped some: 
[https://codex.wordpress.org/Installing_on_Microsoft_IIS](https://codex.wordpress.org/Installing_on_Microsoft_IIS)
Can you please leave this open so other may add their web.config suggestion.
Thanks Phil

**Comment by PHuhn** [comment]
I have placed the web.config in my repository
[https://github.com/PHuhn/ProjectNami-Windows-Install-Utils](https://github.com/PHuhn/ProjectNami-Windows-Install-Utils)
People can add an issue to contact me per any suggestions.
Thanks Phil

**Comment by boldfather** [comment]
Hello Patrick + Phil...

I hope it's Ok to comment here...

I'm brand new to Word Press + Project Nami, but I've also been tasked with getting our new Intranet Server up + running...
We're using a Windows Server 2019 Datacenter, with IIS 10.0 Express and SQL Server 2016.

We believe Project Nami is the proper match to what we have, but I'm having trouble with the Local Install.
Do I need to Unzip the files into a particular folder for the MS Web Installer to find them?
Is my issue with the IIS 10.0 Express - is it a lesser version?

Thanks for any guidance,
Brad

**Comment by patrickebates** [comment]
If you are running on Windows Server, I don't know why you would be using IIS Express.  I would recommend full IIS as you are already on Server.

Your PHP distribution will need to have the SqlSrv module installed, which may already be present if you used the Web Platform Installer to prepare the server.

As for how to handle the ZIP you downloaded from GitHub, I would delete the files within C:\inetpub\wwwroot (the default root of IIS) and then unpack the ZIP into that folder.  You should then be able to browse to the server and begin the installation.

**Comment by boldfather** [comment]
Thanks Patrick
I'll give that a shot
:)

**Comment by PHuhn** [comment]
My talk on installation is here:
[https://docs.google.com/viewer?a=v&pid=sites&srcid=Y29tcHV0ZXJzb2NpZXR5Lm9yZ3xkZWZhdWx0fGd4OjI4MDgwZWRkNWRmNzY4ZDA](url)
With root folder here:
[http://www.computersociety.org/clients/resources](url)

**Comment by boldfather** [comment]
Thanks Phil... - But Patrick can you look again at this info.?

Still having an issue getting ProjectNami loaded

"...I would delete the files within C:\inetpub\wwwroot (the default root of IIS) and then unpack the ZIP into that folder..." --> I did this + Rebooted the Server

I see this inside WebPI + it's updated to today's date, but wants me to use MySql, so I'm pretty sure it's the wrong thing + it just updated to today's date since I unzipped ProjectNami.

![image](https://user-images.githubusercontent.com/47983815/53370057-afa0e180-391a-11e9-8344-855b140af48e.png)

Patrick - what Server do I browse to in order to Launch ProjectNami?

I believe I have all I need for PHP - it tested Ok, from the PHP Mgr inside WebPI, but not sure.
Here's my SQL Server Installed items - do I have what I need?

![image](https://user-images.githubusercontent.com/47983815/53370270-4ff70600-391b-11e9-83ff-06c0b82383ab.png)

NOT Sure where to go now...
Any more help/tips?
Hopeful,
Brad

**Comment by patrickebates** [comment]
I highly recommend that you look at that first link from @PHuhn as it covers almost everything you have asked about.

You're looking at Applications when all you can use Web PI for in this case is App Framework.  If you think that you have everything you need for PHP, then you are done with Web PI.

You need an empty database in your SQL Server as well, plus you need to be configured for Mixed Mode security.  Then you need a user account with rights to the new DB.

To start the installation, you need to open your browser of choice (Chrome/IE/Edge/etc.) and browse to your server name, IP address, etc.

**Comment by boldfather** [comment]
Thank You, Thank You!!!

Believe it or not the last line got me there...
I still had another tweak inside IIS, but I can now do the Project Nami - WP Install.
Thank You Very Much,
Brad
