### ISSUE TITLE
Warning: inet_pton() for LocalHost with port #

### ISSUE THREAD

**Issue by PHuhn** [ProjectNami/projectnami#240]
One option for Project Nami is to install on a local Windows computer using SQL Server 2012 or greater. I have a Windows 10 computer with SQL Server 2016.  I am trying to create a talk and slide deck on Project Nami for Ann Arbor Computer Society.  I am getting the following warning messages on the top of the dashboard:
```
Warning: inet_pton(): Unrecognized address in C:\inetpub\WordPress002\wp-admin\includes\class-wp-community-events.php on line 271
Warning: inet_pton(): Unrecognized address in C:\inetpub\WordPress002\wp-admin\includes\class-wp-community-events.php on line 277
Warning: inet_ntop(): Invalid in_addr value in C:\inetpub\WordPress002\wp-admin\includes\class-wp-community-events.php on line 277 
```
I noticed that Project Nami has changed the code in class-wp-community-events.php, so I felt it would be in your domain to address this issue instead of WordPress.  It does not look good to see the warnings in the slide deck.  My address is localhost with a port #.  I believe that IPv6 is the preferred/default address for a Windows 10 computer.

**Comment by patrickebates** [comment]
Yes, we changed the code with regards to IPv4 due to an issue we identified with Azure Web Apps.  We haven't touched the IPv6 code yet, in large part due to an open ticket with WP core concerning the exact issue you describe -- port numbers appended to the address.

**Comment by PHuhn** [comment]
So am I to ask this question to WordPress?

**Comment by patrickebates** [comment]
Here's the ticket in progress on the issue.  Three months running and they still haven't settled on the final fix.  Looks like it's been punted to WP 4.9
https://core.trac.wordpress.org/ticket/41083

As for a quick fix, what about disabling IPv6 on your local machine while testing?
