### ISSUE TITLE
Default WordPress generated pages?

### ISSUE THREAD

**Issue by PHuhn** [ProjectNami/projectnami#242]
I have been installing and reinstalling Project Nami, and all of a sudden it is creating a single **Sample Page**.  Previously I would get an **About**, **Contacts**, **Blog** and **Home** pages.  The menu is also not being created.  Where and how are these pages initialized?

**Comment by patrickebates** [comment]
Sample Post and Sample Page should be all that is created.  Are you certain the others were not created by a plugin or theme?

**Comment by PHuhn** [comment]
Absolutely positive!!!

**Comment by patrickebates** [comment]
What theme is that?

**Comment by PHuhn** [comment]
Again, where and how are these pages initialized?

**Comment by patrickebates** [comment]
It appears they were added in WP 4.7.0 and can be found in wp-includes/theme.php

```
/**
 * Expand a theme's starter content configuration using core-provided data.
 *
 * @since 4.7.0
 *
 * @return array Array of starter content.
 */
function get_theme_starter_content()
```

**Comment by PHuhn** [comment]
Thanks for the info, but it yielded me nothing.  Any suggestions why this would happen.  I have retraced my steps and not found anything.

**Comment by patrickebates** [comment]
From wp-includes/class-wp-customize-manager.php, function setup_theme()

Looks like those items are only created when you navigate to the Customizer, and only if the option for fresh_site is still True.

```
		/*
		 * Import theme starter content for fresh installs when landing in the customizer.
		 * Import starter content at after_setup_theme:100 so that any
		 * add_theme_support( 'starter-content' ) calls will have been made.
		 */
		if ( get_option( 'fresh_site' ) && 'customize.php' === $pagenow ) {
			add_action( 'after_setup_theme', array( $this, 'import_theme_starter_content' ), 100 );
		}
```

**Comment by PHuhn** [comment]
That did it.  I would not have guested it was procedural.  I was going to try to remove URL Rewrite.
Thanks a lot!
