### ISSUE TITLE
Deploy to Azure "Failed Deployment"

### ISSUE THREAD

**Issue by DevlinSchoonraad** [ProjectNami/projectnami#244]
When using the Deploy to Azure button from GitHub the process runs to the step "Updating Website Config" before it errors out.

The error message is simply: "Failed Deployment"...

![image](https://user-images.githubusercontent.com/1246669/30282571-f3d25936-9715-11e7-8f10-6db7c415ddbe.png)

I am unable to get past this on the one subscription, but all works fine on my MSDN sub.

**Comment by patrickebates** [comment]
Is there anything unique about the one subscription?  Also, is the MSDN sub the default sub for your account?  I seem to recall a known issue with the Azure Deploy system with subscriptions other than the default.

**Comment by DevlinSchoonraad** [comment]
Thanks for the pointer @patrickebates.

The subscription that it's failing on is on the company EA and as mentioned was not the default subscription. I used Azure Powershell to set it as the rm context, but still bet the same failure. Is there another means of setting a subscription to be the default?

**Comment by patrickebates** [comment]
You'll probably need to do a "manual" deployment.  You will need to create the SQL Database and Web App in the Azure portal.  But you can link the Web App to this repository by using the notes below the video on this page....
http://projectnami.org/video-updating-project-nami/

**Comment by jordanmills** [comment]
I'm getting the same issue.  Using a non-default sub that is MSDN.  Let me know if another data point will help.

**Comment by patrickebates** [comment]
The issue of the non-default sub is with the underlying Slingshot website by Microsoft which processes the request.  Unfortunately, you'll need to use the manual deployment method.
