### ISSUE TITLE
Fresh install with debug turned on.

### ISSUE THREAD

**Issue by PHuhn** [ProjectNami/projectnami#247]
I have a new install of Project Nami.  It has not been launched and I added the following to the wp-config.php file: 

> define('WP_DEBUG', true);
> define('WP_DEBUG_LOG', true);
> 

After adding the administrator user the following appeared:

> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 698
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 731
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 753
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 764
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 771
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 784
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 784
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 805
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 811
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 817
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 829
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 842
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 855
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 869
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 883
> 
> Strict Standards: Only variables should be assigned by reference in C:\inetpub\WPressAACS01\wp-admin\includes\schema.php on line 896
> 
I thought you should know.

**Comment by pippercameron** [comment]
Thanks for reporting this! Fixed in https://github.com/ProjectNami/projectnami/pull/274.
