### ISSUE TITLE
Resetting Password for Administrator

### ISSUE THREAD

**Issue by TylerK93** [ProjectNami/projectnami#248]
Hello,

I just deployed a ProjectNami instance to Azure, via the deploy to Azure button. I was able to set up the installation by visiting my site, but now when I try to log in, using the password I set at installation, I'm being told that password is incorrect. I've tried going in and manually editing the password in the wp_users table using SQL Server Management Studio, filling in the MD5 value of a password I wanted to change it to and hitting "Run SQL." However, it's still not working when I try to log in. Can someone please advise?

Thanks!

**Comment by PHuhn** [comment]
Hi Tyler:
I am doing this on a local install, but I would drop all of the tables an re-setup Wordpress.  I do not know if that is available on Azure.
