### ISSUE TITLE
Thousands of wp_batch_split_terms crons queued for past dates.

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami#25]
It looks like the term splitting introduced in a recent merge has caused thousands of past-dated cron jobs to spin up. We need to nuke these in existing installs, as well as fix the bug that caused it. This is a major hit on performance.

cc @patrickebates since we chatted about this today.

**Comment by patrickebates** [comment]
Turns out this is the same issue reported in WP Core ticket 33423.  We've corrected it ourselves, along with some related SQL for term splitting that got past us, and tagged version 1.1.1
