### ISSUE TITLE
strange characters in sql server

### ISSUE THREAD

**Issue by ViniciusMesquita** [ProjectNami/projectnami#251]
I use projetonami with PHP 5.6 using IIS 8.5 and SQLServer 2014.

My encoding is utf-8 and it's not PHP and in the projectnami, however, when you're upgraded by a content that has a special character such as' ç ~ or '' in my SQLServer writes completely wrong and with strange characters.

What can it be?

**Comment by patrickebates** [comment]
Sorry for the delay in getting back with you, but I suspect this old issue will be your solution.  We handle this in the config for sites deployed to Azure, but you would need to apply the setting yourself for a manual install.

https://github.com/ProjectNami/projectnami/issues/199
