### ISSUE TITLE
Password in Plain Text on Azure Portal

### ISSUE THREAD

**Issue by livehands** [ProjectNami/projectnami#253]
After installing and configuring my site.  I was taking a look at the settings for my Azure App.  I noticed that the password for my SQL server was in plain text on the Azure Portal. To replicate open Azure Portal and navigate to the App service for your blog.  in the settings pane select App Settings.  Once loaded you will see a bunch of ProjectNami settings one of which is the ProjectNami.DBPass.  This value is in plain text in the config file meaning anyone with access to the Azure App can see my password.  Is there a workaround for this or a better way to use this?

**Comment by patrickebates** [comment]
You can remove the value from the Azure portal, as it would have been written to the Wordpress config during installation.  But note that WP stores the DB connection info in plain text in the wp-config.php file as well.  So anyone with access to the Azure App via the portal could still obtain the info with just a little bit of additional work.
