### ISSUE TITLE
Don't include old themes in updates or have the latest versions

### ISSUE THREAD

**Issue by rebeccatech** [ProjectNami/projectnami#256]
Would it be possible to not include all the old default themes like Twenty Twelve through Twenty Fifteen in the updates? It's a bit frustrating to have to keep removing them every time I sync for updates and they get reinstalled. If that's not possible, then making sure that the theme files are updated to the latest versions for new releases so you don't get more update messages would be appreciated. Thanks!

**Comment by patrickebates** [comment]
Per this request, we're removing themes no longer maintained within WP Core effective with PN 1.7.0 release.

**Comment by rebeccatech** [comment]
Thank you!
