### ISSUE TITLE
SSMA Migration

### ISSUE THREAD

**Issue by mgarf** [ProjectNami/projectnami#259]
Been using the SSMA tool to migrate my MYSQL to Azure SQL however I keep running into encoding issues (Editor blank, weird characters). I can;t use the export import since i need to peserve the ids. Any thoughts?

**Comment by patrickebates** [comment]
Two thoughts.

First, the export import should preserve IDs.  I know it does for post_id as we had to update that function specifically.

Second, try adding an app setting of ProjectNami.UTF8 set to 1.  That will force UTF-8 character set with the SQL connection.

**Comment by mgarf** [comment]
@patrickebates thank you! second thought worked perfectly. Really appreciate it - i was bashing my head against a wall these past few days.
