### ISSUE TITLE
Wordpress dashboard started showing permission errors

### ISSUE THREAD

**Issue by WouterDeKort** [ProjectNami/projectnami#262]
Wordpress started showing the following errors today in admin portal:

_Warning: error_log(D:\home\LogFiles\translate.log): failed to open stream: Permission denied in D:\home\site\wwwroot\wp-includes\wp-db.php on line 2391

Warning: error_log(D:\home\LogFiles\translate.log): failed to open stream: Permission denied in D:\home\site\wwwroot\wp-includes\wp-db.php on line 2398_

These errors are inserted at the top of the pages like this:

![image](https://user-images.githubusercontent.com/1763043/35446693-d49f72a4-02b5-11e8-86ed-ea8099bbc280.png)

I'm not sure what changed. I didn't do a WordPress update or something. 

Any idea what went wrong?

**Comment by patrickebates** [comment]
Are you still seeing these errors?  I've been unable to duplicate it.  What is the possibility that it's related to the file storage of the instance being full?

**Comment by WouterDeKort** [comment]
Not sure why but the error has disappeared and everything is working OK now.

Thanks,
Wouter

**Comment by nickotech2000** [comment]
I add in the wp-config.php : 

define('DIRECTORY_SEPARATOR','/');

problem gone
---------------------------------------------------------
I use Ubuntu 18.04, PHP 7.3, SQLSVR 2017 and APACHE

**Comment by nickotech2000** [comment]
I dont know too
I have checked php.ini. There is no DIRECTORY_SEPARATOR
I use php 7.3, Ubuntu 18.04, Apache2, SQLSERVER2017. All completely new installation.
I only add extension=sqlsrv.so and add extension=pdo_sqlsrv.so at PHP.ini

Is it need special PHP installation ?
