### ISSUE TITLE
Slow Query on wp_options (Takes up to 20 mins)

### ISSUE THREAD

**Issue by RehanSaeed** [ProjectNami/projectnami#263]
I have 700,000 records in `wp_options`. I noticed Azure complaining about high DTU usage on this query:

```
SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes'
```

I've seen it take anywhere from a minute to 20 mins when the server is under load. I'm considering adding an index to the table, as there are only a few records where autoload is set to true but wanted to confirm here if this is indicative of some deeper problem.

**Comment by patrickebates** [comment]
I know that we've looked at this before, but I don't see that we've ever added this index, even on the largest production sites we deal with.  Can't hurt to add it and see if it helps.

Might also be worth asking why you have 700k records.  Maybe some transients which aren't being purged properly?

**Comment by RehanSaeed** [comment]
Is there a way I can tell which records are transient and can be safely removed?

**Comment by RehanSaeed** [comment]
I had a large number of transients and deleted them with the command below, I now have 175 records in this table:

```
DELETE FROM wp_options WHERE option_name LIKE '%_transient_%'
```

It might still be worth adding an index as this table can get pretty big. Even after removing most records, it's still the query that is eating the most CPU according to the Azure query advisor.

**Comment by RehanSaeed** [comment]
I'm reopening this issue because my wp_options table is growing rapidly and I'll be in the same situation again if I don't do anything. Since I fixed the issue a couple of days ago, I have 1900 new transients. The two records below are what most of them look like:

> _transient_jpp_li_0016d2213f8748c5319e55414db6850c
> a:5:{s:6:"status";s:5:"error";s:3:"msg";s:25:"This API call is invalid.";s:17:"seconds_remaining";i:60;s:16:"blocked_attempts";s:6:"215958";s:6:"expire";i:1517060782;}

> _transient_timeout_jpp_li_41fd3a7041d45a3390f58112a763fe3a
> 1517149537

I believe this has something to do with JetPack blocking login attempts according to https://github.com/Automattic/jetpack/issues/2430. I would have thought this would be a fairly common problem, since a lot of people use JetPack.

**Comment by RehanSaeed** [comment]
I raised https://github.com/Automattic/jetpack/issues/8642#issuecomment-361535861 and apparently there is supposed to be a cron job that clears these transients every day. Does Nami have this? Is it broken in my case?

**Comment by patrickebates** [comment]
Took me a little bit to figure this one out.  Seems that the CRON job for this is a multi-table delete which isn't supported in SQL Server, and that may be new with WP 4.9.  Looks like this can be handled just as soon as we can figure how to rewrite it in a supported way.

**Comment by patrickebates** [comment]
May wind up having to write this one as a stored procedure or something.  I have come up several individual queries which can identify the rows to remove, but as soon as I combine them into delete statements I begin having datatype errors.  Can't even CAST them into the proper datatypes or reorder the where clause in a way to eliminate them.

**Comment by patrickebates** [comment]
After figuring out about 100 different ways to NOT solve this problem, I finally came up with one that does.

https://github.com/ProjectNami/projectnami/commit/ac063bf521c90805394dc895f7f47b9f7aae8c84

This will be in our next release.
