### ISSUE TITLE
Azure Gov Marketplace template not working

### ISSUE THREAD

**Issue by hdharia** [ProjectNami/projectnami#265]
We are having issues with provisioning project name (web+mobile) template for Azure Gov within marketplace. It seems to provision the resources but fails during configuring the connection string. 

Here is a snapshot of the error:

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Failed\",\r\n \"message\": \"Package deployment failed\\r\\nAppGallery Deploy Failed: 'Microsoft.Web.Deployment.DeploymentDetailedClientServerException: An error occurred during execution of the database script. The error occurred between the following lines of the script: \\\"1\\\" and \\\"5\\\". The verbose log might have more information about the error. The command started with the following:\\r\\n\\\"-- Add here a test to be sure the login does not e\\\"\\r\\n Incorrect syntax near '-'. http://go.microsoft.com/fwlink/?LinkId=178587 Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_SQL_EXECUTION_FAILURE. ---&gt; System.Data.SqlClient.SqlException: Incorrect syntax near '-'.\\r\\n at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\\r\\n at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\\r\\n at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\\r\\n at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)\\r\\n at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)\\r\\n at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean&amp; usedCache, Boolean asyncWrite, Boolean inRetry)\\r\\n at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\\r\\n at Microsoft.Web.Deployment.DBStatementInfo.Execute(DbConnection connection, DbTransaction transaction, DeploymentBaseContext baseContext, Int32 timeout)\\r\\n --- End of inner exception stack trace ---\\r\\n at Microsoft.Web.Deployment.DBStatementInfo.Execute(DbConnection connection, DbTransaction transaction, DeploymentBaseContext baseContext, Int32 timeout)\\r\\n at Microsoft.Web.Deployment.DBConnectionWrapper.ExecuteSql(DBStatementInfo sqlStatement, DeploymentBaseContext baseContext, Int32 timeout)\\r\\n at Microsoft.Web.Deployment.SqlScriptToDBProvider.AddHelper(DeploymentObject source, Boolean whatIf)\\r\\n at Microsoft.Web.Deployment.SqlScriptToDBProvider.Add(DeploymentObject source, Boolean whatIf)\\r\\n at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject source, Int32 position, DeploymentSyncContext syncContext)\\r\\n at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject destParent, DeploymentObject sourceObject, Int32 position)\\r\\n at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)\\r\\n at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\\r\\n at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)\\r\\n at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\\r\\n at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)\\r\\n at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)\\r\\n at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)\\r\\n at Microsoft.Web.Deployment.DeploymentObject.SyncTo(String provider, String path, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)\\r\\n at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentWellKnownProvider provider, String path, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)\\r\\n at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.Deploy(String deploymentSite, String siteSlotId, Boolean doNotDelete)\\r\\n at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()'\"\r\n }\r\n ]\r\n }\r\n}"}]}`

**Comment by hdharia** [comment]
Also I am able to do a template deployment using the ARM template but not with marketplace.

**Comment by patrickebates** [comment]
The copy of PN within the Marketplace is a very old build, so I wouldn't recommend starting with it anyway.  When that build was published, the Marketplace required much older technology than ARM templates and was quite a pain to work with.  Even with Microsoft's help, the Marketplace installation was barely holding together at best.

We received word in February that they now support an ARM template format similar to that used here on GitHub with their Slingshot deployment feature.  We're looking at the modifications needed to update the Marketplace deployment, but at this time don't know when we will complete the updates.

For now, I recommend using either the deployment here or performing a manual deployment using the tools in the Azure portal for Web Apps.

Here's an old video showing the manual deployment method using the prior Azure portal.  The method is the same for the current portal, just the location of the options have moved around a bit.  You can still configure the GitHub connection in the same way from Deployment Options in the current portal, for example.
http://projectnami.org/deploying-project-nami-to-windows-azure-web-sites/
