### ISSUE TITLE
Windows Authentication Not Working

### ISSUE THREAD

**Issue by brentcarlson** [ProjectNami/projectnami#266]
Hello, attempting to set this up using Windows Authentication for an on-premise SQL server and its failing to connect. If I enable SQL Authentication and create a local account in SQL it works. Is Windows Authentication not supported? Or is there another issue/bug here?  Thanks for all the work on this project!

**Comment by patrickebates** [comment]
Windows Authentication is not supported.  At the moment I doubt we would look into it, as it would be quite the edge case.

**Comment by brentcarlson** [comment]
Thanks for the information!
