### ISSUE TITLE
Translations for DISTINCT queries cannot handle table naming

### ISSUE THREAD

**Issue by ariesbeck** [ProjectNami/projectnami#267]
While this issue is rare, and the plugin causing the issue is breaking some good practice rules, the query is actually valid, and the translation is failing. A summarized query that will break is as follows:

`SELECT DISTINCT wp_posts.*, IF (wp_posts.post_type = 'tribe_events', wp_postmeta.meta_value, wp_posts.post_date) AS post_date , wp_posts.post_date FROM wp_posts  LEFT JOIN wp_postmeta as wp_postmeta on wp_posts.ID = wp_postmeta.post_id AND wp_postmeta.meta_key = '_EventStartDate' WHERE 1=1  AND wp_posts.post_name = 'events' AND wp_posts.post_type IN ('post', 'page', 'attachment', 'tribe_venue', 'tribe_events', 'tribe-ea-record') AND ((wp_posts.post_status = 'publish' OR wp_posts.post_status = 'inherit' OR wp_posts.post_status = 'private'))  ORDER BY post_date DESC`

The problem exists due to the developer of this plugin using both a DISTINCT clause AND renaming the table by using:
`wp_postmeta as wp_postmeta`

While it is poor form, it is valid SQL and could result in other issues if plugins attempt to use temporary tables. 

The issue lies in /wp-includes/translations.php in the function get_as_fields($query). This function is attempting to obtain the list of columns being requested and renamed using "as". However, it is also picking up the renaming of the table and adding the table name to the order by clause breaking the query. The simple solution would be to detect "from" and stop processing by changing:

```
for ( $i = 0; $i < $count; $i++ ) {
        if ( strtolower($tok[$i]) === 'as' ) {
            $arr[] = $tok[($i + 1)];
        }
}
```

to:

```
for ( $i = 0; $i < $count; $i++ ) {
        if ( strtolower($tok[$i]) === 'as' ) {
            $arr[] = $tok[($i + 1)];
        }
        if(strtolower($tok[$i]) === 'from' ) {
            break;
        }
}
```

**Comment by patrickebates** [comment]
Tribe Events has been something of a constant pain point for PN.  But I appreciate this insight and suggested fix as it might also resolve a couple of other outstanding issues.  We will review and look to test this on our dev server soon.  Thanks.

**Comment by patrickebates** [comment]
Committed to master
