### ISSUE TITLE
varchar to nvarchar translation becomes nnvarchar

### ISSUE THREAD

**Issue by kylesimmonds** [ProjectNami/projectnami#268]
Using the Redirection plugin, it creates a table with a column of type `nvarchar`. This line of fields_map.php searches for only `varchar` and replaces it with `nvarchar`, so if the current type was already `nvarchar` it becomes `nnvarchar`:

https://github.com/ProjectNami/projectnami/blob/331920979704fbb20ff549297934ba0a0025393c/wp-includes/fields_map.php#L153

There's one other place I think is related to the issue, here: https://github.com/ProjectNami/projectnami/blob/331920979704fbb20ff549297934ba0a0025393c/wp-includes/translations.php#L1472

Other than that I'm not familiar enough with this project to have a deep understanding of where else this may be happening

**Comment by kylesimmonds** [comment]
Ok, I was able to find why it was doing that here:

https://github.com/ProjectNami/projectnami/blob/331920979704fbb20ff549297934ba0a0025393c/wp-includes/translations.php#L1626

That string comparison only looks for uppercase `NVARCHAR`, so lowercase `nvarchar` falls under the same replacement as `varchar` and `VARCHAR`

I'll make a PR for this since it seems like a simple enough change

**Comment by patrickebates** [comment]
Merged, and thanks.
