### ISSUE TITLE
Bug in Wordpress plugin Ultimate Member

### ISSUE THREAD

**Issue by JohnWDawson** [ProjectNami/projectnami#278]
Bug found in the Ultimate Member plugin for Wordpress. Reported to Ultimate Member, but their team showed that bug _not_ manifest in a native MySQL host, hence possibly related to use of SqlServer / ProjectNami. Bug visible in this screenshot; evidently cannot see page definitions: 
![um settings](https://user-images.githubusercontent.com/26284517/40237183-364e4494-5a9f-11e8-86b6-051eda8f0f9a.png)

**Comment by patrickebates** [comment]
Do you have the PHP error log and/or the PN translation log file available?

**Comment by JohnWDawson** [comment]
Debug switched on, output here:
[Debug.txt](https://github.com/ProjectNami/projectnami/files/2017022/Debug.txt)

**Comment by JohnWDawson** [comment]
Sorry, what's the PN translation log?

**Comment by JohnWDawson** [comment]
Can offer a little more; tried the (apparently) offending query in the debug log (above); seems to fail similarly when tried in SQL Server Management log, but is OK if double quotes replaced by single quotes; related to SET QUOTED_IDENTIFIER { ON | OFF }? Could it be this simple?

**Comment by JohnWDawson** [comment]
Can offer a little more; tried the (apparently) offending query in the debug log (above); seems to fail similarly when tried in SQL Server Management log, but is OK if double quotes are replaced by single quotes; related to SET QUOTED_IDENTIFIER { ON | OFF }? Could it be this simple?

**Comment by JohnWDawson** [comment]
And finally; tested in SQL Server Management Studio
![quoted_identifier on](https://user-images.githubusercontent.com/26284517/40242331-ee889a34-5aac-11e8-88e1-dd24e66b181b.PNG)

**Comment by JohnWDawson** [comment]
And with it off: 
![quoted_identifier off](https://user-images.githubusercontent.com/26284517/40242350-fa95b3b6-5aac-11e8-8e67-5b583053aab6.PNG)

**Comment by patrickebates** [comment]
There are several things in SQL Server which break if this is left off, per
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-quoted-identifier-transact-sql?view=sql-server-2017

I examined the translations, and seems that we have tightly controlled when double-quotes are replaced with single-quotes in order to prevent damaging post content.  At the moment, I'm not settled on how we would catch this instance without causing more problems.

There is a simple fix for it by editing a line in the plugin itself.  /includes/core/class-query.php, line 97.  Simply swap all single-quotes and double-quotes on that line and it should work properly.

**Comment by patrickebates** [comment]
Looking through the rest of that same file, the bigger question is why they aren't using WP_Query or get_posts like they do elsewhere.  This query which is giving you trouble seems to be the exception to their coding standards.

**Comment by JohnWDawson** [comment]
If single quotes are used for literals in SQL, which is the preferred practice, then it doesn't matter about QUOTED_IDENTIFIER, so this seems to be the way to go, so line 97 in class-query.php goes
from: 'SELECT * FROM '.$wpdb->posts.' WHERE post_type = "page" AND post_status = "publish" '
to:     'SELECT * FROM '.$wpdb->posts.' WHERE post_type = \'page\' AND post_status = \'publish\' '
so the SQL looks like: SELECT * FROM wp_posts WHERE post_type = 'page' and post_status = 'publish'
which works ...
Thanks for help; will pass onto UM
