### ISSUE TITLE
H5P Plugin does not work properly 

### ISSUE THREAD

**Issue by acds** [ProjectNami/projectnami#279]
Hi I have a support issue open with H5P to instal their plugin 
https://h5p.org/documentation/setup/wordpress

I have multi-site enabled, and it error when trying a network activation but seem OK with a site activation.

It does not seem to be able to connect to their site to download content.
<img width="1084" alt="screen shot 2018-05-17 at 6 07 24 pm" src="https://user-images.githubusercontent.com/1319833/40260955-9e3420c0-5ab2-11e8-8557-088380927335.png">
<img width="981" alt="screen shot 2018-05-18 at 3 46 47 pm" src="https://user-images.githubusercontent.com/1319833/40260975-b8776c58-5ab2-11e8-9e29-c1c4dd193ffc.png">

**Comment by patrickebates** [comment]
So after a quick scan of a couple of the plugin's files, I can confirm that it will never run on PN without a significant rework.  Found instances of MySQL commands which have no equivalent in SQL Server.
