### ISSUE TITLE
SQL Server 2008 - Is emulating MySQL LIMIT through OFFSET FETCH the only issue?

### ISSUE THREAD

**Issue by johnwigley** [ProjectNami/projectnami#281]
Hi,

ProjectNami docs mention that SQL Server 2012 is required because until then SQL Server didn't support the Offset Fetch methods which allow efficient emulation of MySQL's LIMIT functionality.

Is this actually the only issue preventing running Project Nami on SQL Server 2008? Because if so then it seems you can emulate Offset / Fetch using a SQL subquery as demonstrated here:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f24c0a3d-e8e9-4041-aca5-590a6e1a2e81/how-to-use-offset-fetch-next-in-sql-server-2008-r2?forum=databasedesign

If this is indeed the only issue, then I would like to see if it's possible to use that workaround with Project Nami - where in the codebase are the SQL queries constructed that use the Offset Fetch methods?

Thanks,
John

**Comment by patrickebates** [comment]
They are pretty much everywhere.  Some are built using the constructors in WP_Query, others are hard coded within various features throughout Wordpress.

Additionally, I feel it's worth noting that mainstream support for SQL 2008 (with or without R2) ended in 2014.  Extended support ends about a year from now on 7/9/2019.
https://blogs.msdn.microsoft.com/sqlreleaseservices/end-of-mainstream-support-for-sql-server-2008-and-sql-server-2008-r2/

Personally, I'd suggest SQL Express 2012 or newer if you are looking for the free or low-cost option for the DB.
