### ISSUE TITLE
UTF-8 Issue

### ISSUE THREAD

**Issue by vampireleon** [ProjectNami/projectnami#282]
Hi all, I am experiencing some issues with the UTF-8 (release 1.9.6)
having all the setup here with forcing UTF-8

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', 'SQL_Latin1_General_CP1_CI_AS');

putenv('ProjectNami.UTF8=1');

I can view my previous post with UTF8 perfectly, however, when I save anything to the DB it will convert the text to "Windows-1252" encoding?

any idea how to save everything in UTF?

**Comment by vampireleon** [comment]
I have found the following need to replaced in order to work

wp-db.php

$query = preg_replace( '/(?<!%)%s/', "'%s'", $query ); // Quote the strings, avoiding escaped strings like %%s.

need to change to 

$query = preg_replace( '/(?<!%)%s/', "N'%s'", $query ); // Quote the strings, avoiding escaped strings like %%s.

**Comment by Frossard** [comment]
Thanks for sharing, helped me alot!
