### ISSUE TITLE
API version error when deploying 

### ISSUE THREAD

**Issue by jvravensberg** [ProjectNami/projectnami#29]
Today I tried to deploy Project Nami by using the "Deploy to Azure" button. The deployment fails with the following error:
The api-version '2.0' is invalid. The api version must be of the following format: yyyy-MM-dd. This format supports the following suffixes: '-preview,-alpha,-beta,-rc,-privatepreview'.

Is this a wrong setting from my side, or is this a bug in the application?

**Comment by patrickebates** [comment]
Might have something to do with the release of the new Azure Portal from earlier this week.  I was able to duplicate the issue and will try to identify what has changed.  Thanks for alerting us.

**Comment by jvravensberg** [comment]
Thanks Patrick! I tried this from the Azure Portal as well, but doesn't work too. Maybe it's because of the new portal indeed.

**Comment by patrickebates** [comment]
Do you mean that our deployment in the Azure Gallery failed as well?

**Comment by jvravensberg** [comment]
Yes that's correct. I've tried to deploy it from the Azure Portal / Gallery multiple times and from the website.

**Comment by patrickebates** [comment]
OK, I need to escalate this to Microsoft then.  They produced the ARM template that is used by the Gallery.  This must be a much larger problem.

**Comment by jvravensberg** [comment]
Yes indeed. Can you reproduce it from the Azure Gallery too? When I click the OK button when configuring the database server, the "New Server" tile crashes with the error: "Error loading tile. Click to reload."

**Comment by patrickebates** [comment]
Could you please try our Deploy To Azure method again?  I believe we have a fix in place.

**Comment by jvravensberg** [comment]
Yes, works fine now! Thanks for fixing this quickly!
