### ISSUE TITLE
Right steps to migrate from MySQL to AzureSQL(MsSQL)

### ISSUE THREAD

**Issue by grzegorzszypa** [ProjectNami/projectnami#291]
Hi.

Did anyone make it before?

**Comment by patrickebates** [comment]
Depending on the size of the site, we recommend using Wordpress Export from the first site and Import into the new site.  For larger sites, it may be necessary to look at wp-cli instead.

**Comment by grzegorzszypa** [comment]
I agree, but how to do it, to do not destroy Wordpress+AzureSQL structure?

**Comment by patrickebates** [comment]
Use the Export and Import tools with Wordpress itself.  Not at the database level.

**Comment by grzegorzszypa** [comment]
For example this: All-in-One WP Migration plugin?

**Comment by patrickebates** [comment]
No, not a plugin.  The built-in tools.
![wpimportexport](https://user-images.githubusercontent.com/4357158/43040099-ced1c174-8d2a-11e8-84fe-60fb9731ae91.PNG)

**Comment by mikeman23** [comment]
How do you use wp-cli with azure. I have MySQL database dump. Can i just import that into MS SQL using wp-cli? thanks!

**Comment by patrickebates** [comment]
Two distinct questions there.  First, you should be able to run wp-cli through the Kudu shell available in web apps.  I haven't done that in some time, and I see that the Site Extension for it may not be available now.  You might be able to upload the files via FTP.

As for the database dump, what we recommend instead is a WP Export XML as above.  There are some tools available from Microsoft for migrating MySQL to Azure SQL, but we don't have experience with those.

**Comment by mikeman23** [comment]
Hi Patrick,
Thanks for the reply. I just checked the WP export/import and it looks like it only takes max 8mb XML files whereas my XML export from my existing site is 25mb. Is there a way to increase the file size upload in azure? Thanks!
