### ISSUE TITLE
DB connection errors

### ISSUE THREAD

**Issue by CaroeK** [ProjectNami/projectnami#301]
Hi
Installed xampp on Windows 10. Apache and PHP. Installed the PHP MSSQL extension. Installed MSSQL EXPRESS. Created a database 'wordpress'. A user wpuser and his is sysadmin on database.
Copied ProjectNami to xampp htdocs and it start up. But when i enter the informations I keep getting a "Error establishing a database connection".  For Database host I use: .\sqlexpress
I have tried a lot of stuff, but it never seems that the actual connection is made. There are no tries in the MSSQL log... Can anybody help ?

**Comment by patrickebates** [comment]
Couple of things to check.  First, can you confirm via phpinfo that the SQLSRV extension is properly loaded?  Second, is TCP/IP enabled as a connection protocol for SQL Express?

**Comment by CaroeK** [comment]
![phpinfo](https://user-images.githubusercontent.com/31595463/44667732-e48bb480-aa1b-11e8-98d6-a80e139337c6.PNG)
TCP/IP was disabled. Enabled did not help. Can you see the PHPINFO if that is correct?

**Comment by patrickebates** [comment]
After enabling, did you restart the SQL service?  It won't bind until that is done.

**Comment by CaroeK** [comment]
I tried now….no change… does the PHPinfo look correct?

**Comment by patrickebates** [comment]
What of it I can see, yes.  Though there should be a section further down dedicated to SQLSRV.
I would also recommend switching to PHP 7.0 or 7.1

Was SQL Express installed as the default instance or as a named instance?  That might explain your connection issues as well.

**Comment by CaroeK** [comment]
as a default instance. Through management Studio i can connet to .\sqlexpress and localhost\sqlexpress and machinename\sqlexpress but nothing works through the WordPress site

**Comment by patrickebates** [comment]
That indicates it is a named instance of "sqlexpress" rather than a default instance.

So you tried using all of these examples as the DB server name during the installation of Project Nami?  What about 127.0.0.1\sqlexpress ?

Did you also create a database to install into?

Also, I want to confirm that you enabled TCP/IP for the SQL Server instance.  Have seen a couple of these reports where the user enabled for the client protocols but not the server protocols.

**Comment by patrickebates** [comment]
Might also look at this.

https://stackoverflow.com/questions/41547504/sqlsrv-connect-not-working-with-instance

**Comment by CaroeK** [comment]
Thank you very much for helping. I did it on a hyper-v machine. I'm starting over on my own laptop now. Trying to do the same. I'll be back with result and with your links and tips in mind..

**Comment by CaroeK** [comment]
Okay so now I got connected. The problem was with the database only allowed windows authentication. Not SQL server authenticating.
Next problem is a lot of
Warning: error_log(C:\xampp\php\logs\translate.log): failed to open stream: No such file or directory in C:\xampp\htdocs\wpsqltest\wp-includes\wp-db.php on line 1817

Any idea?

**Comment by patrickebates** [comment]
It sounds like there is no permission to create and/or write to the translation log file.  It is placed in the same location as the standard PHP log file.

**Comment by CaroeK** [comment]
Everuthing works now, Thanks
