### ISSUE TITLE
Enabling Azure CDN with Project Nami Blob Cache

### ISSUE THREAD

**Issue by Vidocq24601** [ProjectNami/projectnami#310]
HI Patrick,

Creating as new since the referenced issue below become a longer troubleshoot. 

**From #116** 

>... We've knocked around the idea of doing more, but the other plugins out there seem to already do a good job with those features.

What if any additional considerations exist when configuring Azure CDN to work most effectively with Blob Cache?

Any recommendations on overall best practices is greatly appreciated. 

Thank you greatly for any guidance and also overall for the amazing efforts with this project.

**Comment by patrickebates** [comment]
Is this in regards to W3 Total Cache like the issue you referenced?

**Comment by Vidocq24601** [comment]
Currently asking about up to date recommended best practices to configure Azure CDN to work with PN Blob cache.

From previous issue referenced:
> Might be off the area, but i'd love to see the nami cache plugin be integrated with the Azure CDN as i use W3 Total Cache for this purpose.

That user was only using W3 Total Cache as a workaround to configure Azure CDN (W3TC is not in use on any of our environments today). 

Since that was a couple of years ago, I was not sure if there was a more recent or recommended method of configuring Azure CDN to work in conjunction with PN Blob Cache.

**Comment by patrickebates** [comment]
I haven't attempted to do anything with CDN, so I can't really offer any recommendations.  But I did find this article which mentions using the CDN Enabler plugin, apparently to handle the rewrites.

https://blogs.msdn.microsoft.com/azureossds/2015/04/27/improving-wordpress-performance-use-azure-cdn/

Since that plugin is configured to exclude PHP files, and Blob Cache is focused on those specifically, it may be a good pairing.

**Comment by patrickebates** [comment]
One thing I can recommend is https://wordpress.org/plugins/windows-azure-storage/

We use that in almost all circumstances to offload the Media library to Blob Storage.

**Comment by patrickebates** [comment]
Here we go.
https://docs.microsoft.com/en-us/azure/cdn/cdn-create-a-storage-account-with-cdn

Combining Blob Storage with Azure CDN might be a very effective option for you.  Doesn't necessarily help with traditional theme elements (unless you store them in Media library), but for most sites I deal with the theme elements are much lighter weight than the Media.
