### ISSUE TITLE
URL Rewrite/PermaLink + Project Nami.

### ISSUE THREAD

**Issue by Alipoodle** [ProjectNami/projectnami#312]
ATM I seem to be having some issues with getting Perma Link and URL Rewrite to work correctly at the moment! I'd like to make URLs clean and remove the `index.php/page/sub-page` (explained more below).
I've minimal experiences with `web.config` but was able to get a MySQL version of WP to work fine with the *majority* of the settings I've used below. 

[web.configs I've used](https://gist.github.com/Alipoodle/878da842238006478080d2a775c275ee)

Using:  `.../ProjectNami/index.php/page/sub-page/` will:
- if permalink is set to `/%postname%/` I'm redirected to `.../ProjectNami/page/sub-page/` however returns **Error establishing a database connection** 
- if permalink is set to `/index.php/%postname%/` Pages will successfully work, however they include the index.php which I would like to remove.

I've tried messing around a little bit with the rules of web.config, but I really lack any knowledge of it... is it possible that someone could provide some help. Both of the configs are the same as compared to original WP

**Using:**
- Running on a local Machine.
- Nami is in it's own folder /projectnami/ (although will change in future)
- MySQL WP is also in /wordpress/
- URL Write 2 is installed - And worked fine for original WP
- PHP 7.2
- MS SQL Server 2017

**Comment by patrickebates** [comment]
Has to be a web.config rewrite rule issue.  Some questions...

1)  Are /wordpress/ and /projectnami/ configured as distinct web apps in IIS?
2)  Are the web.config files for each install located within each of those folders rather than at the root of the site?

**Comment by Alipoodle** [comment]
Thanks for the reply quick reply:
Currently both in the same web apps for IIS and there's "3" web.config files.
In the gist, there's a GLOBAL-web.config which is placed in the root most folder `/html/web.config`
and then there's NAMI-web.config with is placed within nami's directory `/html/projectnami/web.config`

----------------------------------------------------
While writing this comment I realised that the **Error establishing a database connection** was coming from the WP which didn't have it's database connected and I've likely solved my issued by the ordering of the Rules within the root most `web.config`.

I will close this issue for now and I will likely do the smart decision and make separate webapps for each one *if I continue to use WP*
