### ISSUE TITLE
Path to translate.log in wp-db.php throws "failed to open stream" error on Unix systems.

### ISSUE THREAD

**Issue by kieranpotts** [ProjectNami/projectnami#316]
Variations of the following line appears in six places in ``wp-includes/wp-db.php``:

```
error_log( $msg, 3, dirname( ini_get('error_log') ) . '\translate.log' );
```

For Unix systems, the directory seperator needs to be a forward slash:

```
error_log( $msg, 3, dirname( ini_get('error_log') ) . '/translate.log' );
```

This resolves the "failed to open stream" error.

**Comment by patrickebates** [comment]
Thanks for both the report and the fix.  This is merged into Master.
