### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by Kagelol** [ProjectNami/projectnami#322]
Im feeling somewhat stupid at the moment, but i cannot seem to figure this out.
I have installed 

PHP 7.2.7
Microsoft Drivers 5.2 for PHP v7.2 for SQL Server in IIS

Through the webplatform installer.
I have created a new website in IIS, and placed all the project nami files in the root folder.
When i go to the website i get the WP-admin/setup-config.php page and i fill in the information in the fields.

Databasename -  The database i created through SSMS
Servername 127.0.0.1\SQLEXPRESS   (I have a named instance, i read in another issue i should put it like this)
Username and pw, i created a SQL User WPUser  and made it at first DBOwner, right now i have made it sysadmin but still it doesnt seem to work.

I have checked in SQL Server Configuration Manager and i have enabled TCP/IP on every level

Im not sure what im missing.  Any idea what else it could be.

**Comment by kilasuit** [comment]
I was having this issue with a relatively long password and once i shortened it I found it worked fine, I haven't looked further into where this issue actually surfaces

**Comment by Kagelol** [comment]
> I was having this issue with a relatively long password and once i shortened it I found it worked fine, I haven't looked further into where this issue actually surfaces

I was sceptical at first, but this actually worked.  Thanks!

**Comment by kilasuit** [comment]
I think this should be re-opened though as to work out where the issue actually lies and I wonder what @patrickebates thoughts are on where the issue could be?

**Comment by patrickebates** [comment]
Off the cuff, I'm pretty sure the PHP drivers for SQL still run over ODBC.  I suspect there is some max password length associated with that.  Any idea what length was too long?

**Comment by patrickebates** [comment]
See the third post here for a list of characters not allowed in passwords sent to SQL Server via ODBC.

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/6a26aa9d-2640-4f1c-8a9a-5637c412266f/sql-passwords?forum=sqlsecurity

**Comment by kilasuit** [comment]
seems my password was using some of those characters - I have amended this to not use symbols and only use numbers and letters and can now use a 64char length password

**Comment by kilasuit** [comment]
@patrickebates I think that this can be closed as this is not a PN issue
