### ISSUE TITLE
Call to undefined function mysql_get_client_info() on fresh install using local SQL Server 2012

### ISSUE THREAD

**Issue by jwbrady** [ProjectNami/projectnami#33]
On a fresh install of 1.1.2, I get the following error after going through the "Setup Configuration File" form:

```
Fatal error: Call to undefined function mysql_get_client_info() in <web root snipped>\wp-includes\wp-db.php on line 3097
```

This is in the `has_cap` function when looking for the `utf8mb4` feature. It looks like it is still using mysql functions. Is there a reason for this? I've simply told it to return false on line 3094, and that seems to work. Is this an appropriate fix?

This is on IIS 7.5, Windows 2008 R2, with SQL Server 2012 SP2 and PHP 5.6.16.

**Comment by patrickebates** [comment]
Yes, that should work fine.  But I'm not certain how that function was triggered.  There have been numerous installations of 1.1.2 without similar reports.  Regardless, simply having the function return false should solve the issue.

I'll be certain we review this closely with 1.2.0

Thanks

**Comment by patrickebates** [comment]
https://github.com/ProjectNami/projectnami/commit/0e23f30b8fae6c430ded930a1e058a797101851a
