### ISSUE TITLE
Weird SQL error after updating to PN 2.1

### ISSUE THREAD

**Issue by Ozkovacs** [ProjectNami/projectnami#331]
Hello there.

I have Project Nami installed on a Windows server at home - not Azure.
It is a Win 2016 STD server, and db is MS SQL 2017 STD.
I replaced the code from my installation with the updated PN 2.1 by copying the new files over the old ones.
When done, reconnecting to the site and accessing the back end showed me the DB upgrade message.
When setup ran, I got the following messages: 
(messages are based on French - the first part should read as something like : WordPress database error(...))

Erreur de la base de données WordPress : [[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '('. Code - 102]
CREATE TABLE (meta_id int NOT NULL identity(1,1), blog_id int NOT NULL default 0, meta_key nvarchar(255) default NULL, meta_value nvarchar(max), constraint _PK CONSTRAINT [_meta_id] PRIMARY KEY CLUSTERED (meta_id) WITH (IGNORE_DUP_KEY = OFF) );

Erreur de la base de données WordPress : [[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '('. Code - 102]
CREATE CLUSTERED INDEX _CLU1 on (blog_id);

Erreur de la base de données WordPress : [[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '('. Code - 102]
CREATE INDEX _IDX2 on (meta_key);

Indeed, some of the messages don't make sense.  

Did anyone else have the same issues?

Thanks!

**Comment by patrickebates** [comment]
A new table was added in WP 5.1 -- wp_blogmeta.  The errors you list appear to be the functions to create that table and its indexes during the DB upgrade.  Except they are missing the table reference.

First case I have heard of, and I've updated at least a dozen sites myself.

**Comment by Ozkovacs** [comment]
Thanks Patrick for the reply.
Looks like I'm special! :)
It is weird indeed - I spotted the table name missing from the first query.  
At least, I've got the table name now - I'll fix the queries and run manually.
Hopefully it will do the trick.

I'll post the "fixed" queries here if I succeed.  This way if someone else has the same error, they'll know what to do.

Thanks again!

**Comment by Ozkovacs** [comment]
...here is some feedback.

The second part of the error message is about creating a clustered index named _CLU1.
The table isn't mentioned here either - it can't be the same table (wp_blogmeta) as there is already a clustered index on that table (meta_id).  So it must be either a different table, or a non-clustered index.
If you happen to know for which table, please let me know.
In the meantime, I'll create the index on that table, but non-clustered.
Here are the new queries - note that I ran these "within" my database - you might have to give the full name to your table (like dbname.dbo.wp_blogmeta)

Here goes the updated queries : 
CREATE TABLE wp_blogmeta 
(
	meta_id int NOT NULL identity(1,1), 
	blog_id int NOT NULL default 0, 
	meta_key nvarchar(255) default NULL, 
	meta_value nvarchar(max), 
	constraint [_meta_id] PRIMARY KEY CLUSTERED (meta_id) WITH (IGNORE_DUP_KEY = OFF) 
);


CREATE INDEX _CLU1 on wp_blogmeta (blog_id);


CREATE INDEX _IDX2 on wp_blogmeta (meta_key);

**Comment by patrickebates** [comment]
Here are the full queries as detailed in /wp-admin/includes/upgrade.php and assuming the default prefix of wp_ and formatted for immediate execution in SSMS.

```
CREATE TABLE wp_blogmeta (meta_id int NOT NULL identity(1,1), blog_id int NOT NULL default 0, meta_key nvarchar(255) default NULL, meta_value nvarchar(max), constraint wp_blogmeta_PK PRIMARY KEY NONCLUSTERED (meta_id))
GO
CREATE CLUSTERED INDEX wp_blogmeta_CLU1 on wp_blogmeta (blog_id)
GO
CREATE INDEX wp_blogmeta_IDX2 on wp_blogmeta (meta_key)
GO
```

**Comment by gunnersleague** [comment]
Hey, I am getting a same kind of error with Projectnami and azure. I have purchased a template pack for word press and its giving me this error:
**Cannot export CREATE TABLE sql for commentmeta. [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'wp_commentmeta'.**

**Comment by rhirhi1231** [comment]
@gunnersleague did you ever get to the bottom of this? I'm in the exact same situation!

**Comment by gunnersleague** [comment]
I had to switch my application to WordPress resources available in azure and that worked fine.
