### ISSUE TITLE
Problem with release 5.1.0

### ISSUE THREAD

**Issue by lelandholmquest** [ProjectNami/projectnami#332]
I deployed 5.1.0, now I only get a "Site Under Construction" message no matter where I go in the site. I tried redeploying the previous version (that had been working perfectly up to this release) but am getting the exact same results. How do I go about fixing this?

**Comment by patrickebates** [comment]
Not quite sure what would be generating that.  To start with, if there is a .maintenance file in the root of the site, delete it.

What about the php_error.log?  Anything of interest in it?

**Comment by lelandholmquest** [comment]
(Please bear with me as I am not super familiar with this platform,)
I checked - no .maintenance files.
And I don't have a php_error.log file, but when I check the Azure "Diagnose and solve problems" section in the portal, it says:
Your app may have been impacted due to a site deployment. 
Operation "RestartSite" initiated by user detected. (That was me trying to restart the app)
48.48% of failures came from '/favicon.ico' path.

**Comment by patrickebates** [comment]
Ok, so this is a deployment on Azure App Services.  Which then confuses me even more.

How was the update applied?  Did you upload via FTP, sync through Deployment Options, etc?

You mentioned no php_error.log.  If you connected via FTP, then the log files will be found in their own folder and not within the site files.  Come to think of it, I'm not sure how else you get to them...

**Comment by lelandholmquest** [comment]
Whenever I see on WP that an update is available, I go to the Azure portal, Deployment Center, and then click "Sync", which then grabs the latest copy from GitHub and does the deployment. At least, that is my understanding. I've had this site up for well over a year and have always followed this route and never had a problems. :-)

**Comment by patrickebates** [comment]
When in Deployment Center, there is a Log icon to the right for each deployment entry.  One of the lines will be Running Deployment Command and have an additional Show Logs link available.

1)  Does that log conclude with Finished Successfully?
2)  When you are in the logs, a new button is at the top for Redeploy.  Have you tried that to repair the site?

**Comment by lelandholmquest** [comment]
![image](https://user-images.githubusercontent.com/6992545/54056867-2e610e80-41a6-11e9-89d4-46d7d9f5df2d.png)
I had tried redeploying the 5.1.0, when that didn't change anything, I tired redeploying the previous release. It shows that previous release is now active, but it didn't fix anything. Which I thought was super weird. But I also wondered if I was not doing something right. It almost seems too easy. If I look at the logs for the redeployment of the previous I see:
![image](https://user-images.githubusercontent.com/6992545/54057019-9a437700-41a6-11e9-8ae2-3111a236a501.png)

**Comment by lelandholmquest** [comment]
BTW - I'm stressed right now, so if I am not coming off as appreciative, its just the stress. There is a whole bunch of gratitude that you are helping me!

**Comment by lelandholmquest** [comment]
And for more clarity, I've never FTP to my site. When I needed to change pages myself, I went in through the App Service Editor (preview) and did everything, which was really convenient. At one point, I had put in a error log because I was trying to track something down. I did it through this editor as well. But I removed it when done. The site I had referenced that showed how to do it recommended turning it off when not in need.

**Comment by patrickebates** [comment]
Let's try a full reset.  Click the Disconnect button to break the deployment.  This may take a minute...

Now, to set it back up...
Choose External (you may need to scroll down to see it), click Continue
Choose App Service Kudu build server, Continue

Repository -- https://github.com/ProjectNami/projectnami
Branch -- latest
Continue

Finish

**Comment by lelandholmquest** [comment]
OK. Done, Now click 'Sync'?

**Comment by patrickebates** [comment]
It should start on its own.  If it doesn't, I recommend repeating the disconnect and reconnect.

**Comment by lelandholmquest** [comment]
yes - it started on it own. ;-)

**Comment by lelandholmquest** [comment]
It looked successful:
![image](https://user-images.githubusercontent.com/6992545/54057832-db3c8b00-41a8-11e9-8467-93be9c08876f.png)
But when I go to the site (even tried inPrivate browser):
![image](https://user-images.githubusercontent.com/6992545/54057883-0aeb9300-41a9-11e9-9b06-90b7e9e18a98.png)

**Comment by patrickebates** [comment]
Check for something resembling APP_OFFLINE.htm in the site root.  Delete it if present.

**Comment by lelandholmquest** [comment]
Son of a …
OK. I found and deleted that file. Then refreshed the browser with the site. My home page came in beautiful. I clicked to go to the WP dashboard and got: 
![image](https://user-images.githubusercontent.com/6992545/54058099-bb599700-41a9-11e9-9edc-ede5afa89b85.png)
Expected? Go ahead and click on update?

**Comment by patrickebates** [comment]
Expected.  WP added a new table in this release.

**Comment by lelandholmquest** [comment]
I appear to be back in business. Thank you SO MUCH for the help. I never would have recovered this. 
Any idea where that APP_OFFLINE file came from?

**Comment by lelandholmquest** [comment]
And also - I love Project Nami. I'm a huge fan of WordPress, but getting it on Azure with Azure SQL Server just ROCKS!!

**Comment by patrickebates** [comment]
Yes.  It's created automatically when a new deployment begins and is deleted when it completes.  If you dig deep enough into the Deployment logs in the portal, you should find it mentioned.

I suspect the line you mentioned
`Your app may have been impacted due to a site deployment.`
was from the earlier deployment failing and the file was never deleted.

**Comment by lelandholmquest** [comment]
And then subsequent deployments wouldn't remove that file. Makes perfect sense.
Again, thank you so much for the support!
