### ISSUE TITLE
Parse error in wp-admin/network.php

### ISSUE THREAD

**Issue by jaredbob** [ProjectNami/projectnami#34]
After enabling multisite in wp-config.php and then going to Tools->Network Setup an error is thrown instead of the page being rendered:

Parse error: syntax error, unexpected end of file in D:\home\site\wwwroot\wp-admin\network.php on line 135

Using latest branch.

**Comment by patrickebates** [comment]
Looks like something went wrong with our merge for this file.  I have committed a change to Master, but would like to know if it solves the issue for you.  Would you please either update your site with the file wp-admin/network.php from Master branch, or review the commit and update your file accordingly?
https://github.com/ProjectNami/projectnami/commit/5989b7c6cfe6c926c6dd0485b574c34e6cebcb67

Thanks.

**Comment by jaredbob** [comment]
That fixed the issue. Thanks so much for your quick response. Happy New Year!
