### ISSUE TITLE
Subdomain Multisite ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Vidocq24601** [ProjectNami/projectnami#345]
When creating new multisite network (utilizing subdomains), an ERR_TOO_MANY_REDIRECTS occurs. This has been reproduced multiple times on vanilla PN installations.

**Repro Steps**
1) deploy project nami site
2) add custom domain to site
3) set PN site URL to custom domain
4) enable multisite
5) set network to use subdomains for subsites
6) attempt to access main site

**Result:**

Attempting to access main site results in ERR_TOO_MANY_REDIRECTS
Updating multisite setting within wp-config to 'false' allows access to main site (albeit not network enabled)
This error has been reproduced on multiple vanilla PN installs

**Current web.config as instructed by GUI**

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="WordPress Rule 1" stopProcessing="true">
                    <match url="^index\.php$" ignoreCase="false" />
                    <action type="None" />
                </rule>
                <rule name="WordPress Rule 2" stopProcessing="true">
                    <match url="^wp-admin$" ignoreCase="false" />
                    <action type="Redirect" url="wp-admin/" redirectType="Permanent" />
                </rule>
                <rule name="WordPress Rule 3" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAny">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" />
                    </conditions>
                    <action type="None" />
                </rule>
                <rule name="WordPress Rule 4" stopProcessing="true">
                    <match url="^(wp-(content|admin|includes).*)" ignoreCase="false" />
                    <action type="Rewrite" url="{R:2}" />
                </rule>
                <rule name="WordPress Rule 5" stopProcessing="true">
                    <match url="^(.*\.php)$" ignoreCase="false" />
                    <action type="Rewrite" url="{R:2}" />
                </rule>
                <rule name="WordPress Rule 6" stopProcessing="true">
                    <match url="." ignoreCase="false" />
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
		
```

**Current addition to wp.config**

```
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', 'example.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
```
_Note: 'example.com' is placeholder value for describing network issue, accurate hostname is set on this installation_. 

**Additional Information**

Several networks have been configured and installed using the methods as described above. Cloudflare is the DNS provider that also provides SSL cert. Within Cloudflare, SSL setting has been set to full. In addition, attempts to clear cache and disable Cloudflare tools have been unsuccessful in resolving the redirect error. This setup has not been problematic in the past. To clarify: same steps have been utilized successfully in the past, however recently it has not been possible to configure a new multisite network using steps outlined above.

**Comment by patrickebates** [comment]
I installed a new multisite myself in just the past few weeks.  Same web.config and nearly the same wp-config.php changes, and it runs normally.

You might try adding this to wp-config
`define('COOKIE_DOMAIN', '');
`

**Comment by Vidocq24601** [comment]
**Attempted suggestion to no avail**

In previous weeks, deployments proceeded as expected and multisite configuration was successful. These previous networks are also running normally. The current issue impacts recently deployed sites that get upgraded to multisite (within last week or two). 

With regards to wp-config, this is what has been currently added:

```
/* Multisite */
define( 'WP_ALLOW_MULTISITE', true );

define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', 'example.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

define('ADMIN_COOKIE_PATH', '/');
define('COOKIE_DOMAIN', '');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');
```
"example.com" is a placeholder value for true URL. All networks almost always utilize Apex domain for parent site (no WWW). Upon first installation, standalone site always loads correctly after custom domain has been set. However, upon enabling multisite, attempts to access the primary site URL result in a redirect loop. More pecifically:

**https://example.com**

Reditects to:

**https://example.com/wp-signup.php?new=example.com**

**Additional Factors**
- Within Azure, SSL setting was updated to always load via HTTPS.
- Within Cloudflare dashboard, SSL was also set to load via HTTPS.
- Upon disabling both Azure and Cloudflare SSL settings, main site (example.com) still redirects to **https://example.com/wp-signup.php?new=example.com** and results in error (ERR_TOO_MANY_REDIRECTS)

Appreciate your help in identifying the issue. It's particularly painful due to the fact that this has occurred on multiple separate deployments even when following documented steps. For the life of me cannot identify the root cause (within previous 1-2 weeks)

**Comment by patrickebates** [comment]
Does the issue occur before or after you add a second site (or both)?

**Comment by Vidocq24601** [comment]
Issue actually occurs immediately when confirming sub-domain and multisite configuration. At that time, it is no longer possible to access the main site dashboard (WordPress) due to the redirect loop. Extraordinarily unusual and frustrating.

**Follow Up: Note :**

```
**Currently these values are are set:** 

/* Multisite */
define( 'WP_ALLOW_MULTISITE', true );

define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', 'example.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

define('ADMIN_COOKIE_PATH', '/');
define('COOKIE_DOMAIN', '');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');
```

If multisite setting above (MULTISITE; true) is manually redefined to 'false', then main WP site is accessible once again. Pulling hair out attempting to resolve the issue.

**Comment by patrickebates** [comment]
Do the rows in wp_blogs and wp_site look correct to you, specifically the Domain columns?

Is this an Azure Web App?  If so, what happens if you leave the initial site set to yoursite.azurewebsites.net?

**Comment by Vidocq24601** [comment]
Rows in wp_blogs and wp_site are checked out and look accurate. This is an Azure Web App. If a custom domain is not set, then it is not possible to configure a subdomain network.

If `define('MULTISITE', true);` is adjusted to `define('MULTISITE', false);`it is possible to again visit main site (albeit not network configured)

**Comment by patrickebates** [comment]
Of course multiple custom domains need to be set.  I was just wondering if you tried to perform the initial setup and enabling of multisite using the default domain, then adding your first domain as your second site?  It appears that the most recent multisite I set up followed that pattern.

Grasping at straws as I can't think of a good reason you would be seeing this issue.

**Comment by Vidocq24601** [comment]
I am now really at a loss. 

Attempted to perform initial setup and enabling of multisite using default domain. Upon completing this, presented with exact same redirect error as before when attempting to access main site. 

**Specifically:** 

https://example.azurewebsites.net/wp-signup.php?new=example.azurewebsites.net and results in error (ERR_TOO_MANY_REDIRECTS)

Literally no other steps. Deploy new installation from github into new resource group, 5-min install, set multisite to allow, update web.config and wp-config as directed, then too many redirects. I have set up a number of networks and this is the first time this behavior has happened.

**Comment by Vidocq24601** [comment]
Looked at php_errors.log:

```
[18-Apr-2019 22:14:53 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:14:55 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:15:01 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:15:01 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:15:03 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:15:03 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:15:43 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:15:44 UTC] PHP Warning:  sqlsrv_query() expects parameter 1 to be resource, null given in D:\home\site\wwwroot\wp-includes\wp-db.php on line 1957
[18-Apr-2019 22:15:44 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'wp_'. Code - 207 for query SELECT wp_
[18-Apr-2019 22:23:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'wp_users' in the database. Code - 2714 for query CREATE TABLE wp_users (
  ID int NOT NULL identity(1,1),
  user_login nvarchar(60) NOT NULL default '',
  user_pass nvarchar(64) NOT NULL default '',
  user_nicename nvarchar(50) NOT NULL default '',
  user_email nvarchar(100) NOT NULL default '',
  user_url nvarchar(100) NOT NULL default '',
  user_registered datetime2(0) NOT NULL default '0001-01-01 00:00:00',
  user_activation_key nvarchar(60) NOT NULL default '',
  user_status int NOT NULL default 0,
  display_name nvarchar(250) NOT NULL default '',
  spam tinyint NOT NULL default 0,
  deleted tinyint NOT NULL default 0,
  constraint wp_users_PK PRIMARY KEY  (ID)
)
 made by install_network, dbDelta
[18-Apr-2019 22:23:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The operation failed because an index or statistics with name 'wp_users_IDX1' already exists on table 'wp_users'. Code - 1913 for query 
CREATE INDEX wp_users_IDX1 on wp_users (user_login)
 made by install_network, dbDelta
[18-Apr-2019 22:23:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The operation failed because an index or statistics with name 'wp_users_IDX2' already exists on table 'wp_users'. Code - 1913 for query 
CREATE INDEX wp_users_IDX2 on wp_users (user_nicename)
 made by install_network, dbDelta
[18-Apr-2019 22:23:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'wp_usermeta' in the database. Code - 2714 for query 
CREATE TABLE wp_usermeta (
  umeta_id int NOT NULL identity(1,1),
  user_id int NOT NULL default 0,
  meta_key nvarchar(255) default NULL,
  meta_value nvarchar(max),
  constraint wp_usermeta_PK PRIMARY KEY NONCLUSTERED (umeta_id)
)
 made by install_network, dbDelta
[18-Apr-2019 22:23:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The operation failed because an index or statistics with name 'wp_usermeta_CLU1' already exists on table 'wp_usermeta'. Code - 1913 for query 
CREATE CLUSTERED INDEX wp_usermeta_CLU1 on wp_usermeta (user_id)
 made by install_network, dbDelta
[18-Apr-2019 22:23:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The operation failed because an index or statistics with name 'wp_usermeta_IDX2' already exists on table 'wp_usermeta'. Code - 1913 for query 
CREATE INDEX wp_usermeta_IDX2 on wp_usermeta (meta_key)
 made by install_network, dbDelta
[18-Apr-2019 22:23:45 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert explicit value for identity column in table 'wp_blogs' when IDENTITY_INSERT is set to OFF. Code - 544 for query INSERT INTO [wp_blogs] ([site_id], [blog_id], [domain], [path], [registered]) VALUES (1, 1, 'EXAMPLE.azurewebsites.net', '/', '2019-04-18 22:23:45') made by populate_network

```

**Comment by patrickebates** [comment]
I'm confused.  I thought you said above that the entries in wp_blogs appeared as expected?  Are there no rows present in the table?

**Comment by patrickebates** [comment]
Looks like somewhere since 5.0.0 that the IDENTITY_INSERT changes for handling wp_blogs were removed.  I'll track that down, but for now you can find those changes in commit 7a69d5be3194626d39a924078020aa11f3b2638f or you can download a copy of the Latest branch.  New deployments via Deploy to Azure will include this update as well.

I would prepare a formal release, but as I'm expecting WP 5.2 to drop at any time I will just wait for that.

**Comment by Vidocq24601** [comment]
Realized I was making an error last night which is when I dumped error log running out the door (reviewed incorrect DB when troubleshooting, apologies). Just now tested and can confirm latest commit resolved issue setting up new networks. Thanks for prompt response and helping troubleshoot problem.
