### ISSUE TITLE
Warning: preg_replace(): Compilation failed: missing ) at offset... Peter's Login Redirect

### ISSUE THREAD

**Issue by swatersfla** [ProjectNami/projectnami#349]
I received several error messages like the errors below after activating and assigning a wordpress user a redirect url through a plugin called Peter's Login Redirect. The plugin allows you to redirect a user to a specified url after login.

Warning: preg_replace(): Compilation failed: missing ) at offset 193 in C:\inetpub\wwwroot\projectnami-2.1.0\wp-includes\translations.php on line 1483

Warning: Cannot modify header information - headers already sent by (output started at C:\inetpub\wwwroot\projectnami-2.1.0\wp-includes\translations.php:1483) in C:\inetpub\wwwroot\projectnami-2.1.0\wp-includes\pluggable.php on line 1251

Any idea what could be causing the errors? Thank you for your help with this.

SW

**Comment by patrickebates** [comment]
Delete the file /wp-includes/fields_map.parsed_types.php

We're starting to see more and more corruption issues with that log file, so I suspect we will remove it completely soon.

**Comment by swatersfla** [comment]
Thank you for the quick response. I deleted the file and gave it a go. I received an additional error that says ****ERROR: Unknown error adding user-specific redirect for user testname*** This happened when I selected a username and and assigned the redirect URL.
I'm beginning to think it's a plugin issue.
SW
