### ISSUE TITLE
Debugging tips for PHP Timeouts?

### ISSUE THREAD

**Issue by A-Matt** [ProjectNami/projectnami#351]
**Project Nami Version:** 2.2.0 + 1.9.8
**Previous SQL Version:** V14 / 2017
**New SQL Version:** v14.0.1000.169 (X64) / 2017

For some reason today after moving to a different server, later on in the day the day every time I go into a Page edit screen of a page of a decent size, it will take extremely long till the point where IIS will Time out FastCGI. Smaller pages of around 5 lines of HTML are fine and take what I would expect of a larger page to load previously, with a page of 300 lines, just about peaking the timeout time.
This seems to only be an issue with the page edit as, loading into the actual page takes the same amount of time as before, especially on the larger pages.

I don't desperately want to extend this time as it's set to around a minute already, but this page had been working fine after I had migrated to this new SQL Server, and nearing the end of the day has suddenly started to fail. Migration seems to have worked fine by the fact everything else is working fine, as well as another database set which again works fine.

I've already tried looking into WordPress' Debugging stuff, however no issues are caused from it, causing nothing to be placed into PHP's Error, or into the WordPress one (it only seems to love PHP errors though?).
There's no major spikes in PHP's Fast-CGI within windows making me suspect it might be something to with not correctly getting values back or something.
Checking SQL Management Studio's `SQL Server Queries` , it seems to be running them quickly and not causing any issues that I'm aware of.
_I should say, I have no idea what I should expect from these background queries for WordPress_

I've additionally (Accidentally) tested running it on 1.9.8 with the same issues, tried with using one of Wordpress' themes, and without plugins, still to no success.
Tried with Block and Classic editor.

--------
Is there any other things that can be done to help me with fixing this issue or debug in any shape or form, as this is now preventing me from being able to update pages anymore!?

**Comment by A-Matt** [comment]
Update
------
After playing around a little bit to see what it might be, this seems to be an issue with revisions of the file.
The largest of the files I have had around 250 revisions and reducing it down to 20 seems to have made it to an acceptable amount of time to load.
The 300 line page I had mentioned has around 100 revisions total.

Is there any explanation to why this might be causing issues for me now on this new server which should improve the performance of my SQL Server (as it's a faster machine) and reduced load on my local machine running the site?

**Comment by patrickebates** [comment]
It almost seems like an indexing issue.  How did you migrate the data to the new server?

**Comment by A-Matt** [comment]
I'm not much of an SQL person besides running queries for getting of our data.

But as asked by my Boss:
- Within SSMS Deattach database from Server1
- Copy `.mdf` file located  `C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\`
- Save onto external drive

From here, my Boss did all of the work attaching it, so I assume it's a simple paste of the `.mdf` within Server2's data folder and Attaching in SSMS.


Thank you for the reply.

**Comment by patrickebates** [comment]
That should be pretty straightforward.  But just in case some optimizations were lost with the migration, you might want to update statistics and/or rebuild indexes to see if performance improves.

**Comment by A-Matt** [comment]
Thank you very much. I will look into running this before I leave work to hopefully reduce the load on the server while people are using it.
I assume I would have to do something like what is explained within [this MS Doc](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/reorganize-and-rebuild-indexes?view=sql-server-2017) on reorganise and rebuild index

**Comment by patrickebates** [comment]
Yes.  And I recommend setting ONLINE = ON or the site will be inaccessible during the rebuild depending on which table is currently undergoing work.  We have an Azure web job for performing this as an automated task.  Here's the key functions
https://github.com/ProjectNami/ProjectNamiDBWebJob/blob/master/ProjectNamiDBWebJob/Module1.vb

I recommend that you start with the post data, so you will need these commands:

```
ALTER INDEX ALL ON wp_posts REBUILD WITH (ONLINE = ON)
ALTER INDEX ALL ON wp_postmeta REBUILD WITH (ONLINE = ON)

```

**Comment by A-Matt** [comment]
Sadly doing the rebuild and reindex doesn't seem to have fixed issues with it loading.
Hopefully with all existing things being now placed onto this new server, all new indexes will be fine and should reduce any more load growing over time.
I'm considering at the moment if I really need to keep many of the previous revisions to see if removing all of them will overall fix the opening of the pages.

But at least thank you with providing me with what advice you could provide!

**Comment by A-Matt** [comment]
Been 2 months now, and issue seems to have fixed itself now!
Will Close the ticket, and thank you for the ideas for fixing it 👍
