### ISSUE TITLE
Access data from MS SQL and display on page

### ISSUE THREAD

**Issue by swatersfla** [ProjectNami/projectnami#353]
How would we access data directly from MS SQL table and display it in wordpress.  Would we use wpdb class?

Thank you,
Susan

**Comment by patrickebates** [comment]
Assuming it's in the same DB as the site, then yes that should be the cleanest option.

**Comment by swatersfla** [comment]
Thank you Patrick. Is there an example or any documentation on this? 

Susan

**Comment by patrickebates** [comment]
https://codex.wordpress.org/Class_Reference/wpdb

**Comment by swatersfla** [comment]
Thank you.
