### ISSUE TITLE
Need access to php.ini file

### ISSUE THREAD

**Issue by gunnersleague** [ProjectNami/projectnami#358]
Hey, I wanted to increase the upload size for my themes but I am not able to find the php.ini file. Would you be able to provide me with the access of the php.ini file. My app service name is - Technology-Distilled-Dev-App. If not is there any other way to upload a theme zip file that is greater than 25 MB in size.

**Comment by patrickebates** [comment]
What you're looking for is .user.ini file which is placed in the root of your web app and overrides values in the default php.ini file.

https://blogs.msdn.microsoft.com/kaushal/2014/01/01/windows-azure-web-sites-file-upload-limit-for-php-sites-hosted-on-waws/

**Comment by gunnersleague** [comment]
Thanks that worked
