### ISSUE TITLE
Full text search  - Invalide object name when creating the full text view

### ISSUE THREAD

**Issue by Athone** [ProjectNami/projectnami#359]
Hi, 

I had a error with the full text search : 
Invalid object name 'dbo.wp_users'. Code - 208 pour la requête if not exists (select * from INFORMATION_SCHEMA.TABLES where table_name ...

it didn't take into account the prefix I've put for the table. It did for the full text catalog but not for the users table so I change the line 51( at the end ) in the pn-fulltext-search.php file of the plugins and added the prefix for the users tables like so : ... inner join dbo.**{$wpdb->get_blog_prefix()}**users on {$wpdb->get_blog_prefix()}posts.post_author = **{$wpdb->get_blog_prefix()}**users.ID')" );

Now the search work and i don't have any error in my debug.log.

It might be a good idea to integrate this change in the plugins, I'm probably not the only one who had this problem.

**Comment by patrickebates** [comment]
Good catch.  Will look to get that updated soon.
