### ISSUE TITLE
Compatibility with Elementor

### ISSUE THREAD

**Issue by Vidocq24601** [ProjectNami/projectnami#361]
Most recent version of Elementor plugin (2.6.xx) causes PHP errors on a clean installation of Project Nami using default theme. The following error repeats until the plugin has been downgraded to Elementor 2.5.16

`[24-Jul-2019 16:50:42 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"140a790c2ab81aff9e2bc348f5047043";O:31:"Elementor\Core\Logger\Items\PHP":9:{s:7:"'. Code - 105 for query UPDATE [wp_options] SET [option_value] = 'a:2:{s:32:"140a790c2ab81aff9e2bc348f5047043";O:31:"Elementor\Core\Logger\Items\PHP":9:{s:7:"`

The translate log also has the following error generating repeatedly:

```
2019-07-24 19:25:37 Error Code: 105 -- Begin Query translation attempt:
UPDATE [wp_options] SET [option_value] = 'a:2:{s:32:"140a790c2ab81aff9e2bc348f5047043";O:31:"Elementor\Core\Logger\Items\PHP":9:{s:7:"*file";s:98:"D:\home\site\wwwroot\wp-content\plugins\elementor\includes\settings\system-info\classes\server.php";s:7:"*line";i:238;s:7:"*date";s:19:"2019-07-17 16:48:45";s:7:"*type";s:6:"notice";s:10:"*message";s:54:"Trying to get property &#039;Value&#039; of non-object";s:7:"*meta";a:1:{s:5:"trace";a:1:{i:0;a:3:{s:8:"function";s:8:"shutdown";s:5:"class";s:29:"Elementor\Core\Logger\Manager";s:4:"type";s:2:"->";}}}s:8:"*times";i:1;s:14:"*times_dates";a:1:{i:0;s:19:"2019-07-17 16:48:45";}s:7:"*args";a:5:{s:4:"type";s:6:"notice";s:7:"message";s:44:"Trying to get property ''Value'' of non-object";s:4:"file";s:98:"D:\home\site\wwwroot\wp-content\plugins\elementor\includes\settings\system-info\classes\server.php";s:4:"line";i:238;s:5:"trace";b:1;}}s:32:"0265a3cfe6c331e85b1478fccec05efe";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"*date";s:19:"2019-07-24 19:25:36";s:7:"*type";s:4:"info";s:10:"*message";s:47:"Elementor data updater process has been queued.";s:7:"*meta";a:3:{s:6:"plugin";s:9:"Elementor";s:4:"from";s:5:"2.6.5";s:2:"to";s:5:"2.6.6";}s:8:"*times";i:1;s:14:"*times_dates";a:1:{i:0;s:19:"2019-07-24 19:25:36";}s:7:"*args";a:3:{s:4:"meta";a:3:{s:6:"plugin";s:9:"Elementor";s:4:"from";s:5:"2.6.5";s:2:"to";s:5:"2.6.6";}s:7:"message";s:47:"Elementor data updater process has been queued.";s:4:"type";s:4:"info";}}}', [autoload] = 'no' WHERE [option_name] = 'elementor_log'
2019-07-24 19:25:37 -- Translation result:
UPDATE [wp_options] SET [option_value] = 'a:2:{s:32:"140a790c2ab81aff9e2bc348f5047043";O:31:"Elementor\Core\Logger\Items\PHP":9:{s:7:"*file";s:98:"D:\home\site\wwwroot\wp-content\plugins\elementor\includes\settings\system-info\classes\server.php";s:7:"*line";i:238;s:7:"*date";s:19:"2019-07-17 16:48:45";s:7:"*type";s:6:"notice";s:10:"*message";s:54:"Trying to get property &#039;Value&#039; of non-object";s:7:"*meta";a:1:{s:5:"trace";a:1:{i:0;a:3:{s:8:"function";s:8:"shutdown";s:5:"class";s:29:"Elementor\Core\Logger\Manager";s:4:"type";s:2:"->";}}}s:8:"*times";i:1;s:14:"*times_dates";a:1:{i:0;s:19:"2019-07-17 16:48:45";}s:7:"*args";a:5:{s:4:"type";s:6:"notice";s:7:"message";s:44:"Trying to get property ''Value'' of non-object";s:4:"file";s:98:"D:\home\site\wwwroot\wp-content\plugins\elementor\includes\settings\system-info\classes\server.php";s:4:"line";i:238;s:5:"trace";b:1;}}s:32:"0265a3cfe6c331e85b1478fccec05efe";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"*date";s:19:"2019-07-24 19:25:36";s:7:"*type";s:4:"info";s:10:"*message";s:47:"Elementor data updater process has been queued.";s:7:"*meta";a:3:{s:6:"plugin";s:9:"Elementor";s:4:"from";s:5:"2.6.5";s:2:"to";s:5:"2.6.6";}s:8:"*times";i:1;s:14:"*times_dates";a:1:{i:0;s:19:"2019-07-24 19:25:36";}s:7:"*args";a:3:{s:4:"meta";a:3:{s:6:"plugin";s:9:"Elementor";s:4:"from";s:5:"2.6.5";s:2:"to";s:5:"2.6.6";}s:7:"message";s:47:"Elementor data updater process has been queued.";s:4:"type";s:4:"info";}}}', [autoload] = 'no' WHERE [option_name] = 'elementor_log'
```
I have contacted Elementor support, however hoping to receive any possible guidance on how to determine the source of the issue since I am unable to replicate on a standard WordPress installation.

**Comment by patrickebates** [comment]
This caught my attention quickly because I happen to be dealing with a brand new site using Elementor 2.6.1 this week.  I don't see this error reported anywhere in my site.

**Comment by Vidocq24601** [comment]
I can confirm this is blocking updates to Elementor on multiple networks so isn't an isolated incident. 

Have you ever updated Elementor on the new site? Asking because it was when the plugin was updated via the WordPress GUI that I saw the spike in Average Response Time which led me to review logs.

**Comment by patrickebates** [comment]
No, this is a fresh site that I believe started at 2.6.1

Is it possible that something changed in the format of the option with 2.6.x?

**Comment by Vidocq24601** [comment]
**Similar Error on Separate Network**

```
[11-Jul-2019 02:17:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"809584ad2db9836cf123e79ec088b7c7";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"'. Code - 105 for query UPDATE [wp_2_options] SET [option_value] = 'a:2:{s:32:"809584ad2db9836cf123e79ec088b7c7";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"
[11-Jul-2019 02:17:43 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"809584ad2db9836cf123e79ec088b7c7";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"'. Code - 105 for query UPDATE [wp_2_options] SET [option_value] = 'a:2:{s:32:"809584ad2db9836cf123e79ec088b7c7";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"
[11-Jul-2019 02:17:45 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"809584ad2db9836cf123e79ec088b7c7";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"'. Code - 105 for query UPDATE [wp_2_options] SET [option_value] = 'a:2:{s:32:"809584ad2db9836cf123e79ec088b7c7";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"

```

**Similar Error on Separate Network**
```
[12-Jul-2019 15:09:46 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"c16eb10d40b48092e6a1f8fe5b760da7";O:30:"Elementor\Core\Logger\Items\JS":10:{s:9:"'. Code - 105 for query UPDATE [wp_3_options] SET [option_value] = 'a:2:{s:32:"c16eb10d40b48092e6a1f8fe5b760da7";O:30:"Elementor\Core\Logger\Items\JS":10:{s:9:"
[12-Jul-2019 15:09:47 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"c16eb10d40b48092e6a1f8fe5b760da7";O:30:"Elementor\Core\Logger\Items\JS":10:{s:9:"'. Code - 105 for query UPDATE [wp_3_options] SET [option_value] = 'a:2:{s:32:"c16eb10d40b48092e6a1f8fe5b760da7";O:30:"Elementor\Core\Logger\Items\JS":10:{s:9:"

```
**Similar Error on Separate Network**
```
[12-Jul-2019 12:28:33 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"dc008c085d6f09dc0f54c2879b45a9a0";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"'. Code - 105 for query UPDATE [wp_11_options] SET [option_value] = 'a:2:{s:32:"dc008c085d6f09dc0f54c2879b45a9a0";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"
[12-Jul-2019 12:28:33 UTC] WordPress database error [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:2:{s:32:"dc008c085d6f09dc0f54c2879b45a9a0";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"'. Code - 105 for query UPDATE [wp_11_options] SET [option_value] = 'a:2:{s:32:"dc008c085d6f09dc0f54c2879b45a9a0";O:32:"Elementor\Core\Logger\Items\Base":7:{s:7:"

```

**Comment by Vidocq24601** [comment]
Honestly, I am not sure. I just tested and confirmed that the initial install of the plugin _should_ work without errors. However, when the plugin gets updated, that is when issues occur. Impact to performance is significant since the error is continuously being generated in the logs.

On a separate network, can confirm that Elementor Pro is unable to be updated, but can open a separate issue for that with more details.

**Timeline**

July 9th: updated a network from 2.5.16 to 2.6.0. Issue present but undetected off hours. 
July 10th: began to troubleshoot. By downgrading to 2.5.16, issue temporarily resolved
Circa 19th: created a clean installation and installed 2.6.2 (worked as expected)
July 24th: upgraded the clean installation from 2.6.2 to 2.6.6. Same errors as before. Downgrading to 2.5.16 resolves the issue on clean installation.

Honestly at a bit of a loss, but more than happy to provide additional details or information if it helps.

**Comment by patrickebates** [comment]
I just duplicated the issue when upgrading the plugin to 2.6.6, and immediately cleared it up by rolling back to 2.6.1.

By any chance did you attempt to roll that last one back to 2.6.2 before going all the way back to 2.5.16?

**Comment by patrickebates** [comment]
It appears to be related to the option elementor_log but that's all I know so far.

**Comment by Vidocq24601** [comment]
Manually updated plugin to 2.6.2 on clean install and so far appears to be working as expected, but will be doing further testing.

In the meantime, manually updated a separate network to 2.6.2 (which did not start at 2.6.2) and it also appears to be working but will report back after further testing.

Do feel better that issue can be reproduced. From notes, can confirm all errors I've at least personally seen thus far involve the option elementor_log

**Comment by patrickebates** [comment]
It appears that the writing of the original option value was corrupted as well.  The Serialized data is clearly incomplete.

**Comment by Vidocq24601** [comment]
Tested upgrading to 2.6.2 Elementor and 2.6.1 Pro on an existing network which resulted in a cascade of logging errors similar to those previously described. Additionally, on this network upgrading resulted in the following fatal error on admin screen (public facing also resulted in a fatal error):

```
Fatal error: Uncaught Error: Undefined class constant 'BETA_TESTER_META_KEY' in D:\home\site\wwwroot\wp-content\plugins\elementor\core\admin\admin.php:724 Stack trace: #0 D:\home\site\wwwroot\wp-includes\class-wp-hook.php(286): Elementor\Core\Admin\Admin->init_beta_tester(Object(WP_Screen)) #1 D:\home\site\wwwroot\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 D:\home\site\wwwroot\wp-includes\plugin.php(465): WP_Hook->do_action(Array) #3 D:\home\site\wwwroot\wp-admin\includes\class-wp-screen.php(411): do_action('current_screen', Object(WP_Screen)) #4 D:\home\site\wwwroot\wp-admin\includes\screen.php(241): WP_Screen->set_current_screen() #5 D:\home\site\wwwroot\wp-admin\admin.php(206): set_current_screen() #6 D:\home\site\wwwroot\wp-admin\edit.php(10): require_once('D:\\home\\site\\ww...') #7 {main} thrown in D:\home\site\wwwroot\wp-content\plugins\elementor\core\admin\admin.php on line 724

```

**Current Determination**

Most reliable configuration with Elementor and Elementor Pro on PN is 2.5.16 and 2.5.12 Pro. There are cases where other versions _might possibly_ work, particularly on new installations, however those instances may or may not be stable.

As always, help determining root cause and/or a complete resolution is greatly appreciated. Of course let me know if there is any assistance I can offer in isolating/resolving the issue. I will also update if Elementor support responds.

**Comment by patrickebates** [comment]
So this appears to be an issue with NULL characters in the serialized string failing to write to the DB.  I just synced a commit to deal with this.
https://github.com/ProjectNami/projectnami/commit/d72bb9ec2546dece59cd70eca1af42ff3aa8ccb2

Please either make those changes yourself or download that file to your local install, then let me know if you find the issue resolved.

I suspect this will end up being the solution to some other plugin issues we've seen from time to time where only partial data was being written to the DB.

**Comment by patrickebates** [comment]
FYI, I have now applied this change to the new site I was working with and upgraded Elementor to 2.6.6.  So far I have no errors and Elementor has scheduled a cron job that is running updates.

Looking good to me.

**Comment by patrickebates** [comment]
Ran into some issues with the cron job.  Unfortunately I have no error logs that show where the problem was occurring, but it had something to do with the icon updates.  I forced the option for elementor_version to 2.6.6 and the excessive activity stopped.

**Comment by Vidocq24601** [comment]
Hi Patrick,

Made changes and ran into the same issue with icon updates. Thankfully however manually setting option for elementor_version to 2.6.6 resolved that problem for me as well. All networks have now been updated. I can see how this could cause issues for other plugins as well so I'm glad you were able to resolve. As always, your assistance is greatly appreciated. Thanks again.
