### ISSUE TITLE
Project Nami - Sync from Deployments Center Failed

### ISSUE THREAD

**Issue by JanVerwaest** [ProjectNami/projectnami#369]
The Sync from the Deployment Center failed with an unknown error.

![DeploymentCenterStatusFailed](https://user-images.githubusercontent.com/55002206/64458483-c0b28280-d0f5-11e9-941f-7b26344d18b5.JPG)

**Comment by patrickebates** [comment]
Not sure what this might be, but you could try removing the sync settings and recreating from scratch.

I suspect some of the titles might have changed with the update to Deployment Center, but here's the important values you will need:


Source | External Repository
URL | https://github.com/ProjectNami/projectnami
Branch | latest

**Comment by JanVerwaest** [comment]
Hi Patrick,

Thanks for the swift reply. This did indeed work. Much appriciated.
![DeploymentCenterStatusSuccess](https://user-images.githubusercontent.com/55002206/64459559-78489400-d0f8-11e9-8c84-4b5936ed5374.JPG)
