### ISSUE TITLE
How do we test this outside of Azure locally and is there any docker/windows container story yet?

### ISSUE THREAD

**Issue by jacobrillema** [ProjectNami/projectnami#37]
Is there any documentation on how to setup and test locally with project nami? Also any story yet around hosting in docker container/windows containers? I think this will become a priority with the explosion around docker and containers.

**Comment by patrickebates** [comment]
Nothing with containers yet, though we should probably look into that.

We have several users running production sites in-house.  Rules are much the same as vanilla WordPress.  IIS and PHP runtime.  Just need to be certain that the SQL driver for PHP is installed and the SqlSrv module loaded.  I would recommend using WebPI to install PHP 5.6.16, as this method will allow you to choose the 3.2 SQL drivers as well (actually, it may select them for you once you choose PHP).
https://www.microsoft.com/web/downloads/platform.aspx

**Comment by patrickebates** [comment]
I did find reference to a Windows Container with PHP at this location
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_images

**Comment by jacobrillema** [comment]
Do you have steps on how to install the files or setup IIS+PHP? I presume we install this in some sort of hosting folder, create an IIS website with PHP configuration and modify some configuration settings? Also will this work against SQL Express 2014? Do i need to be aware of x64 vs x86 issues? Sorry for coming at this very green but I want to eventually get this into a windows container so I wanted to do a manual install first locally to understand it. My end goal here is to have WordPress + WP-CLI + OpenSsh + IIS + PHP in one container and Sql Server 2014 in another windows container. I guess I should ask does WP-CLI work with your version of WordPress?

**Comment by patrickebates** [comment]
Use WebPI to install PHP 5.6, matching SQL drivers, and URL Rewrite 2.0
https://www.microsoft.com/web/downloads/platform.aspx
Should work just fine with SQL Express 2014.  The install option above should configure your PHP env to deal with any x64 vs x86 issues.

After setting up the environment, you should be able to drop the PN contents into the IIS root and get to work.

I'll let Spencer address the WP-CLI more accurately, but it is my understanding that WP-CLI has issues with Windows in general (so the problems are not specific to PN).  We're working on getting PN to run on Linux, which would allow full WP-CLI support.  Stay tuned.

**Comment by jacobrillema** [comment]
Ah sweet news on getting PN to run on Linux that would be nice to see. I see there was a nice write up over at the forums section regarding self hosted install. I will have to take a peak at that as well. Thanks for the quick feedback!

http://support.projectnami.org/viewtopic.php?f=4&t=79

**Comment by pippercameron** [comment]
@jacobrillema `wp-cli` actually works in windows out of the box, mostly. The biggest thing you don't get, outside of the Linux tool chain which some of us (like me) are used to and would really miss, is access to `wp shell`. The `shell` command doesn't work because the faux shell is created using *nix constructs that just don't exist in Windows, unfortunately.

That being said, Linux support is coming soon.

**Comment by Cyberboss** [comment]
https://github.com/Cyberboss/ProjectNamiDocker
