### ISSUE TITLE
New Wordpress version but no Nami one?

### ISSUE THREAD

**Issue by benoithamet** [ProjectNami/projectnami#371]
Hi there

I understand this can be a complicated work - and I appreciate it - but seems the new Wordpress version 5.2.4 released few days ago did not made it to Nami
Previous Wordpress releases where available within the day following their availability
Do we have to think to move away and go back to MySQL? :(

**Comment by patrickebates** [comment]
No, nothing so drastic.  This just happened to be the first release in a very, very long time which dropped while I've been out of town.

Look for the new version over the weekend.

**Comment by benoithamet** [comment]
👍 
Thanks Patrick
Not a problem, was thinking about something like that
Keep up the good work on Nami; really like it
