### ISSUE TITLE
Insecure PHP message

### ISSUE THREAD

**Issue by mileaminute** [ProjectNami/projectnami#378]
After updating to the latest project nami build, I see this message in the Dashboard: WordPress has detected that your site is running on an insecure version of PHP.

Is updating PHP version something I'd do outside of the projectnami install? Does anyone have any pointers?

Thanks

**Comment by patrickebates** [comment]
Yes, this is done in your server environment.  Are you running on Azure Web Apps or a full server install?

**Comment by mileaminute** [comment]
In Azure Web Apps

**Comment by patrickebates** [comment]
In the Azure portal, select your web app.  Then Configuration, and the General Settings option in the right-hand panel.  Stack Settings should be Stack = PHP and PHP version = whatever works with your themes and plugins.

I can confirm that PN on it's own works just fine with PHP 7.3, which is currently the highest version supported by Web Apps.
