### ISSUE TITLE
Restore after updating Project Nami

### ISSUE THREAD

**Issue by mileaminute** [ProjectNami/projectnami#379]
This is related to #295 (exporting & importing), but more focused on updates (not restoring to a new install) and using Azure Web Apps.

Scenario: I've setup a deployment and eventually I click sync (e.g. to get 5.3 update). At that point files are copied from Github and changes are complete - is that right?

I did this recently and seemed to lose my wp-content uploads and plugins. Is that expected or did I do something wrong?

Also it doesn't seem that the database was overwritten (but if it was I could reimport my wp export.xml file). For images and plug-ins I could restore with ftp. But am I missing anything else that I'd need to reconfigure? And if I had woo commerce would there be something special with that?

Thanks

**Comment by patrickebates** [comment]
I have dozens of sites hooked up and updating in this manner, and I've never seen the results you describe.  Sync does indeed pull down files from GitHub and overwrite as needed, but this should not impact anything you added.  Now if you are modifying the default themes, then yes that could be overwritten.  But uploads, plugins, themes that you have added should be left alone.

**Comment by mileaminute** [comment]
Thanks for confirming, I likely did something inadvertently like redeploy or swapping deployments.

**Comment by patrickebates** [comment]
Swapping makes the most sense to me.  I have performed redeploys and not see what you describe either.

Also, our merge with 5.3 isn't ready yet.  Still working through about half of several dozen rejections, so check again in 24 to 48 hours.

**Comment by mileaminute** [comment]
One more related question. When I create a second slot for staging and then access the page, I get the "Hey, App Service developers!" page when accessing it. I feel like I'm missing a simple step or a setting (I did change stack to PHP but that was all I could find to change). Any suggestions?

**Comment by patrickebates** [comment]
Pretty sure that all new slots are created empty.

On Nov 15, 2019, at 2:39 PM, mileaminute <notifications@github.com> wrote:

﻿

One more related question. When I create a second slot for staging and then access the page, I get the "Hey, App Service developers!" page when accessing it. I feel like I'm missing a simple step or a setting (I did change stack to PHP but that was all I could find to change). Any suggestions?

**Comment by mileaminute** [comment]
I had cloned settings from production but now realize that doesn't really clone files so it was a newb move. I appreciate you responding.
