### ISSUE TITLE
Turn back on found rows query for comments.

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami#38]
We need fix up the SQL [here](https://github.com/ProjectNami/projectnami/blob/master/wp-includes/class-wp-comment-query.php#L399) and [here](https://github.com/ProjectNami/projectnami/blob/master/wp-includes/class-wp-comment-query.php#L836) and turn found rows back on.

Disabled in 9cf6d44.

**Comment by patrickebates** [comment]
Fixed for 1.3.0
