### ISSUE TITLE
PHP Fatal error: Call to undefined function wp_kses_normalize_entities()

### ISSUE THREAD

**Issue by eduardoboca** [ProjectNami/projectnami#386]
I've upgrade projectnami to 2.3.2 release and now I'm facing some timeout and out of memory problems. The error log show these messages:

PHP Fatal error: Call to undefined function wp_kses_normalize_entities()
Uncaught Error: Class 'NOOP_Translations' not found in \htdocs\wp-includes\l10n.php:1230

Does that mean there was a problem with the upgrade?

**Comment by patrickebates** [comment]
Looks like something did go wrong somewhere.  That function exists in the current release.  You might want to copy the files over fresh.  If you are using a sync with the GitHub repo, you may want to break it and reconfigure so it does a fresh pull.

What size web app / server are you running on?  What version of PHP?

**Comment by eduardoboca** [comment]
PHP Version 7.3.11
I don't have full access to the server, so I can't answer the size question... it should be my fault then, thanks a lot!
