### ISSUE TITLE
An automated updated has failed to complete

### ISSUE THREAD

**Issue by RehanSaeed** [ProjectNami/projectnami#392]
I'm using the latest version and can't get past this screen. When I click the button, it seems to start doing something and then comes back to this screen.

![image](https://user-images.githubusercontent.com/2270364/75144917-ed804380-56ef-11ea-967f-c0332155e383.png)

**Comment by patrickebates** [comment]
Automated updates should be disabled.  This appeared in the last 24 hours?  Are there other users who have permission levels to perform manual updates?

**Comment by patrickebates** [comment]
Check for the presence of the .maintenance file in the root of the site as well.  After a quick search, I have yet to find anything else which might be setting the flag to enable that notice.

**Comment by RehanSaeed** [comment]
I wa trying to update some plugins a few days ago and can't do so anymore. It looks like the update is happening but the page refreshes and the update is still there. I can do manual updates but would prefer a fix.

No .maintenance file in Azure:

![image](https://user-images.githubusercontent.com/2270364/75174129-f260e980-5727-11ea-8ccf-bd2930b48353.png)

**Comment by patrickebates** [comment]
I wonder if this is somehow related to a failed plugin update then.  Checking to see if there is an option or similar flag within the DB which hasn't been cleared.

**Comment by patrickebates** [comment]
Check for a site option auto_core_update_failed and try changing its value.

**Comment by RehanSaeed** [comment]
I now seem to be able to upgrade plugins again. Did them one at the time and the message is gone. Weird.
