### ISSUE TITLE
Invalid argument in last update on D:\home\site\wwwroot\wp-includes\translations.php

### ISSUE THREAD

**Issue by nunoarias** [ProjectNami/projectnami#400]
In the last update, I have the following error:

Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1283

Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\translations.php on line 1477

WordPress Updates
Last checked on May 20, 2020 at 4:27 pm.   Check Again

You have Project Nami 2.4.1 which contains the latest version of WordPress.
If you need to re-install, please check the Project Nami Download page for the latest build.

**Comment by patrickebates** [comment]
Look for a file /wp-includes/fields_map.parsed_types.php and if you find it, rename it.  This file is a log of translated schema for tables created through plugins.  Sometimes it becomes corrupted during upgrades.  We're trying to remove the dependency on this log.

Note that an empty file may be recreated after you rename it.

**Comment by nunoarias** [comment]
Many thanks Patrick, problem solved !

**Comment by patrickebates** [comment]
We're looking for testers for the update to finally remove the dependency on that log file.  Let me know if you're interested.

**Comment by nunoarias** [comment]
Great. Yes, I'm interested !

**Comment by patrickebates** [comment]
https://projectnami.blob.core.windows.net/plugins/fields_map.php

This is a replacement for the corresponding file in /wp-includes/
I suggest making a backup copy of the current file in the event you see any errors or unexpected operation of the site.
What's changed is that the necessary schema is read in from the database rather than relying on the log file.

**Comment by nunoarias** [comment]
Hi Patrick, the site is working without any issues. I think it's ok.
