### ISSUE TITLE
WP Query filter by custom post type

### ISSUE THREAD

**Issue by nsposit** [ProjectNami/projectnami#401]
I have the following code to filter search results by custom post types (the value of the query parameter 'p'). The function works as intended on the base wp install; however, it does not seem to set the 'post_type' on ProjectNami. I have verified that the function is working properly and narrowed down the issue to the following: `$query->set('post_type', [SOME POST TYPE]);`

`function search_filter($query)
{
    if (!is_admin() && $query->is_main_query()) {
        if (is_search()) {
            if (isset($_REQUEST['p']) && !empty($_REQUEST['p']) && $_REQUEST['p'] != 'all') {
                $query->set('post_type', esc_html($_REQUEST['p']));
            } 
        }
    }
}
add_action('pre_get_posts', 'search_filter');`

**Comment by patrickebates** [comment]
So far I've been unable to find any differences in the handling of post_type in wp-includes/class-wp-query.php  And I can't see any strange actions with pre_get_posts either.

Is it possible for you to provide a sample of the query generated by either WP or PN, or preferably both?

**Comment by nsposit** [comment]
I checked the SQL logs and noticed that there was another plugin that was overriding the query. Sorry for the inconvenience. There should be nothing wrong with the PN class.
