### ISSUE TITLE
Fatal error after installing WooCommerce plugin - not able to open website anymore

### ISSUE THREAD

**Issue by JanVerwaest** [ProjectNami/projectnami#404]
Dear,

When trying to install a WooCommerce plugin, the website returned a fatal error. Any idea how to recover from this or roll it back?

Website: https://kapua.azurewebsites.net/

Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"'. in D:\home\site\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 D:\home\site\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 D:\home\site\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 D:\home\site\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 D:\home\site\wwwroot\wp- in D:\home\site\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php on line 44

**Comment by JanVerwaest** [comment]
Hi Patrick,

Did some further debugging and across this additonal message

WordPress database error: [[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"'. Code - 105]
INSERT INTO [wp_actionscheduler_actions] ([hook], [status], [scheduled_date_gmt], [scheduled_date_local], [schedule], [group_id], [args]) VALUES ('action_scheduler/migration_hook', 'pending', '2020-07-01 22:42:15', '2020-07-01 22:42:15', 'O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"*scheduled_timestamp";i:1593643335;s:41:"ActionScheduler_SimpleScheduletimestamp";i:1593643335;}', '1', '[]')

**Comment by patrickebates** [comment]
Sorry for the delay in getting back with you.

First, to the error itself.  This appears to be an issue with attempting to write a serialized object to a column in the DB.  We have encountered similar issues before, specifically when writing to wp_options and made accommodations by using parameterized queries there.  If there are NULL values being written, they break in a similar fashion unless they are sanitized.  Not much we can do about that on a custom DB call.

Second, to the larger issue of WooCommerce in general.  If you check our Plugin Compatibility page (http://projectnami.org/plugin-compatibility/) you will find that WooCommerce is the one plugin we specifically call out as being unsupported.

**Comment by JanVerwaest** [comment]
Hi Partrick,

Thank you for your reply. It clarifies the situation. I have overlooked the Plugin Compatibility page and will take that into account in the future. In the mean while I have been able to remove the plugin and could recover the site.
