### ISSUE TITLE
A vanilla installation of 2.5.0 on Windows Server 2019 with SQL Server 2017 CU21 gives "Error 500"

### ISSUE THREAD

**Issue by RichardsWeb** [ProjectNami/projectnami#409]
Hi,

I successfully installed ProjectNami 2.4.2 on this same Windows Server last month and it went just fine. I did get the usual error messages during the installation which I ignored, but it's been working fine ever since.

I wanted to setup a brand new IIS WordPress site for another project so I downloaded ProjectNami 2.5.0 and followed the same installation steps as for my 2.4.2 site - I created the site in IIS, created a SQL database, copied-in the extracted files from the ProjectNami 2.5.0 download, gave IUSR both MODIFY and WRITE permissions, and then browsed the website to start setup.

I selected English (UK) and entered the database details. I got a message confirming that ProjectNami could talk to my database, I clicked next/continue and then just got "Error 500". This wasn't an IIS Error page, it was a plain text "Error 500".

I deleted the contents of the IIS site folder, tried again, exactly the same result - it will talk to the database but it won't then continue with the setup. I just get "Error 500".

I deleted the contents of the IIS site folder again, extracted ProjectNami 2.4.2 into the folder, and the setup worked fine. My site is up and running.

I HAVE NOT tried upgrading from v2.4.2 to v2.5.0 yet - I'm too nervous at this stage!

Any suggestions welcome, I'd be happy to re-test on another vanilla site and provide feedback or error logs if you can tell me where to look for them.

Thanks,

Richard.

**Comment by patrickebates** [comment]
I'll test a fresh install and get back to you.

I can tell you that I have upgraded multiple sites at this point without issue.  I would suggest making a backup copy just in case, but it should work fine.

**Comment by RichardsWeb** [comment]
Thanks for such a prompt response Patrick. I'll bite the bullet and do a backup-then-upgrade tomorrow and let you know how it goes either way.

**Comment by patrickebates** [comment]
Found and fixed.  Rolled back a change to a DB query during install that WP made in 5.5.  It might be poorly formed in vanilla WP as well.

New version here
https://github.com/ProjectNami/projectnami/archive/2.5.1.zip

**Comment by RichardsWeb** [comment]
That's great! Thanks so much Patrick. I'd barely done anything on the new site yet, so I blew away the site and database and then installed from scratch. The new v2.5.1 installed just fine.

Thanks again,

Richard.
