### ISSUE TITLE
Fix Invalid MSSQL Syntax In wp-admin/includes/class-wp-upgrader.php

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami#41]
Need to adjust `INSERT IGNORE` [here] (https://github.com/ProjectNami/projectnami/commit/d2b19f1a25a75fc833ac41696a14d4a9d560fa38#diff-58c2d7df47b07fa60493f695e57a8458R774) to MSSQL friendly syntax.

**Comment by pippercameron** [comment]
WP Core ticket for reference: https://core.trac.wordpress.org/ticket/34878

**Comment by yorek** [comment]
Here a MERGE statement should do the trick

**Comment by pippercameron** [comment]
Would it be easier to just do a `NOT EXISTS` on `option_name`?

**Comment by yorek** [comment]
It will work too, I thought the MERGE syntax is just easier to implement.

**Comment by pippercameron** [comment]
Do you want to work up an example for comparison? It seemed like `NOT EXISTS` would be cleaner and more straightforward for this purpose, but I'd love to see a `MERGE` example also.

**Comment by patrickebates** [comment]
This may be what we are looking for
`$lock_result = $wpdb->query( $wpdb->prepare( "IF NOT EXISTS (SELECT * FROM [$wpdb->options] WHERE [option_name] = '%s') INSERT INTO [$wpdb->options] ( [option_name], [option_value], [autoload] ) VALUES (%s, %s, 'no') else UPDATE [$wpdb->options] set [option_value] = '%s', [autoload] = 'no' where [option_name] = '%s'", $lock_option, $lock_option, time(), time(), $lock_option ) );`

**Comment by yorek** [comment]
Here's a MERGE sample: 
```
MERGE INTO dbo.wp_options t 
USING (VALUES('o2', 'v3', 1)) s(option_name, option_value, autoload) ON t.option_name = s.option_name
WHEN MATCHED THEN UPDATE SET t.option_value = s.option_value, t.autoload = s.autoload 
WHEN NOT MATCHED THEN INSERT VALUES (s.option_name, s.option_value, s.autoload);
```

**Comment by patrickebates** [comment]
MERGE option will bring some sanity to the number of items passed into `$wpdb->prepare`

`$lock_result = $wpdb->query( $wpdb->prepare( "MERGE INTO [$wpdb->options] t USING (VALUES(%s, %s, 'no')) s(option_name, option_value, autoload) ON t.option_name = s.option_name WHEN MATCHED THEN UPDATE SET t.option_value = s.option_value, t.autoload = s.autoload WHEN NOT MATCHED THEN INSERT VALUES (s.option_name, s.option_value, s.autoload);", $lock_option, time() ) );
`

**Comment by pippercameron** [comment]
@yorek, @patrickebates, I think I would rather use `NOT EXISTS` for a few reasons:

1. It's faster inserting the the lock when no lock exists already (by 40-60% after a few runs on an existing multisite running in Azure).
2. It's on par performance-wise with `MERGE` when the value already exists (the two queries actually trade places with each other in terms of which one's faster or slower depending on current database load/latency.
3. It's much clearer what's actually going on when you look at. Readability is also an important factor.

One other comment about the `MERGE` example, the `WHEN MATCHED THEN UPDATE SET` bit would need to be omitted since the existing MySQL `INSERT IGNORE` doesn't update an existing lock, it just bails and leaves it intact.

**Comment by patrickebates** [comment]
Then the `ELSE` clause of the `NOT EXISTS` option needs to be dropped as well.  It would update the existing lock.

**Comment by pippercameron** [comment]
Yep. I think we're good to merge this in. I'll do a pull request.
