### ISSUE TITLE
Help needed modifying SQL-Parser-Engine

### ISSUE THREAD

**Issue by mssqlserver** [ProjectNami/projectnami#415]
Hi!

I'm facing problems with several Plugins (like buddypress for example).
What I plan to do is to fix SQL-Errors by myself, but I need to know where in the code you do modifications to SQL-Statements.

Here's an example of a PHP-Code-Snippet in Buddypress (wp-content\plugins\buddypress\bp-notifications\classes\class-bp-notifications-notification.php):

		// SELECT.
		$select_sql = "SELECT id, user_id, item_id, secondary_item_id, component_name, component_action, date_notified, is_new, COUNT(id) as total_count ";

		// FROM.
		$from_sql = "FROM {$bp->notifications->table_name} n ";

		// WHERE.
		$where_sql = self::get_where_sql( array(
			'user_id'        => $user_id,
			'is_new'         => 1,
			'component_name' => bp_notifications_get_registered_components(),
		), $select_sql, $from_sql );

		// GROUP
		$group_sql = "GROUP BY user_id, component_name, component_action";

		// SORT
		$order_sql = "ORDER BY date_notified desc";

The SQL-Code which is executed by projectnami is:

SELECT id, user_id, item_id, secondary_item_id, component_name, component_action, **_date_not CASE WHEN ied THEN_**  is_new ELSE  COUNT(id END as total_count  FROM wp_bp_notifications n  WHERE user_id IN (1) AND component_name IN ('xprofile','friends','messages','activity','groups','blogs','buddydrive','forums') AND is_new = 1 GROUP BY user_id, component_name, component_action ORDER BY date_notified desc

As you can see the parser does some unwanted modifications to the code.
Where can I find the parser-code so that I can optimize this?

My plan is to optimize the parser-code in order to fix further problems like replacing "TRUNCATE" (MYSQL) to "TRUNCATE TABLE" (T-SQL).

Thank you for your support!

BR,
Bob

**Comment by patrickebates** [comment]
You're looking for https://github.com/ProjectNami/projectnami/blob/master/wp-includes/translations.php

**Comment by mssqlserver** [comment]
Perfect! Thank you!

**Comment by srutzky** [comment]
@mssqlserver (and @patrickebates ): please see #416 😺
