### ISSUE TITLE
Fix Invalid MSSQL Syntax In wp-admin/includes/upgrade.php

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami#42]
We need to replace `REGEXP` [here](https://github.com/ProjectNami/projectnami/commit/d2b19f1a25a75fc833ac41696a14d4a9d560fa38#diff-edf10fb2833dc3fa63e4d9879ce60bfdR1434) since it's not compatible with MSSQL. Can we just replace `REGEXP` with `LIKE` since it supports regex in MSSQL?

Needs some testing.

cc @patrickebates

**Comment by yorek** [comment]
Unfortunately SQL Server "LIKE" doesn't really support REGEXP.....in the mentioned case it would work anyway, but maybe it could be interesting to provide such functionality via SQLCLR?

**Comment by pippercameron** [comment]
What would be the benefit of SQLCLR in this case over `LIKE` -- or did you just mean something in SQLCLR for general use in other cases?

**Comment by yorek** [comment]
The mail point is that LIKE doesn't really support regexp....just support some simple search pattern. So if we need to have REGEXP support the only way is SQLCLR

**Comment by pippercameron** [comment]
Gotcha. That makes sense.

**Comment by patrickebates** [comment]
We have corporate users who have already informed us that SQLCLR is blocked in their organizations due to security concerns, so we shouldn't resort to it for something in Core if we can help it.

**Comment by yorek** [comment]
Unfortunately there is no other way to have a proper regex implementation in SQL Server than using SQLCLR :(

**Comment by yorek** [comment]
for what security concern. Then main problem, usually, is that fact that assemblies downloaded from web can contain malicious or dangerous code...so that's why DBA are not happy to enable it. But if you can provide a SIGNED assembly, which means that DBA can instruct SQL Server to execute only that signed assemblies, and only in Project Nami database, that should do the trick.

**Comment by pippercameron** [comment]
This should be sufficient: https://github.com/ProjectNami/projectnami/pull/44

It will match any option name that starts with at least one integer, has zero or more string characters (presumably integers), followed by `_new_email`. This is almost identical to the MySQL `REGEX` version and I think close enough for this use case.

**Comment by yorek** [comment]
Sure for this specific case will work like charm

**Comment by pippercameron** [comment]
Thanks for the feedback, @yorek.

Also, for posterity, here's a list of the very limited pattern matching support for `LIKE` in MSSQL: https://technet.microsoft.com/en-us/library/ms187489(v=sql.105).aspx

**Comment by pippercameron** [comment]
It just occurred to me that `_new_email` doesn't mean the same thing in an MSSQL like as it does in a MySQL like. Since there is limited pattern matching here, underscores actually mean "any single character". These should be encapsulated in `[]` for good measure.

**Comment by patrickebates** [comment]
LIKE '[0-9]%[_]new[_]email'
Yes, that should be what you're looking for.

**Comment by pippercameron** [comment]
Yep, that's exactly what I was thinking.

**Comment by pippercameron** [comment]
Addressed this in https://github.com/ProjectNami/projectnami/pull/45.

**Comment by pippercameron** [comment]
Closing this issue out.
