### ISSUE TITLE
Update Using Azure Deployment Center

### ISSUE THREAD

**Issue by Colbz** [ProjectNami/projectnami#429]
We have an Azure App Service that host two Deployment Slots for Production and Development. I tested the 'Sync' button in our Dev slot first which pulled the latest Project Nami commit and deployed it. I then open the admin center where I was prompted to update the WP database. The Update message disappeared and the version was updated.

Repeating these exact same steps in our Production slot, I was NOT prompted to update the WP database and the version remained the same. Exact same results in the log, but the deployment didn't upgrade the WP version and I'm still prompted ("WordPress 5.7 is available! Please update now.") whereas Dev worked seamlessly. Is there an extra step I can take to finish the deployment or should I try another Sync?

![image](https://user-images.githubusercontent.com/1844805/113626591-99000500-961f-11eb-90e1-f052cf762980.png)

**Comment by patrickebates** [comment]
This is interesting.  I would assume that both slots reference the same DB?  So updating the dev site should have performed the DB updates for both.

I have seen a situation recently on some Web App instances that the built-in caching is sticking with some settings.  Might want to look at Restarting both slots.

**Comment by Colbz** [comment]
Thanks for the quick reply. Dev and Prod have different Databases but it looks like all traffic is going to slot1 instead of "Production". Slot1 is not connect to the Project Nami repository so I will try performing a Sync on that one to see if it helps. All 3 slots have different DBs

![image](https://user-images.githubusercontent.com/1844805/113628188-c2ba2b80-9621-11eb-9e93-a020eb2a6fc7.png)

**Comment by Colbz** [comment]
That worked, just had to connect slot1
