### ISSUE TITLE
SQL Server Fail after PHP upgrade

### ISSUE THREAD

**Issue by itcbaillie** [ProjectNami/projectnami#453]
Hi all,

I recently upgraded to Project Nami v5.7.2, PHP 7.4.13, and the MS SQL drivers v5.9. I have loaded the SQL driver for PHP v7.4 in IIS and they are showing as loaded in phpinfo().

However, when I try to browse the site I get the message saying there was an error connecting to the DB. If I swap back to PHP v5.6 in IIS, the site loads as expected.

Anyone seen this before?

**Comment by patrickebates** [comment]
On Azure Web Apps, PHP 7.4.15 currently includes the following SqlSrv version.
5.7.1-preview+12728

My first suggestion would be to try that version or perhaps 5.8.1.
https://github.com/microsoft/msphpsql/releases

**Comment by itcbaillie** [comment]
Hi Patrick,

That's perfect, 5.8 is working a treat! Thank you.
