### ISSUE TITLE
README Description Needs An Update

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami#46]
It's been awhile since we've had a meaningful update here and it's out of date. A good place to start would be the [description](https://github.com/ProjectNami/projectnami/blob/master/README.md#description).

> Essentials supported include ( but are not limited to ) the following:
> 
> import
> export
> media upload
> posts
> pages
> user management
> comments
> multisite
> In a nutshell, we're sure there are bugs, but we don't know of any right now.

These sort of things are no longer representative of the current builds. Everything works. PN has been stable for ages now.

**Comment by patrickebates** [comment]
Made an initial pass at this in 1.4.0.  What else to we want to change?
