### ISSUE TITLE
Google Site-Kit not working on last update

### ISSUE THREAD

**Issue by benjamingranados** [ProjectNami/projectnami#472]
I had to erase the folders and now I'm not even able to reinstall it :S Happened while updating the plugin. The site was inoperable and this was the message:

Warning:include(D:\home|site|wwwroot|wp-content|plugins\google-site-kit/third-
n D:\home|site|wwwroot|wp-content|plugins\google-site-kit\includes|loader.phponline
28

Warning: include(): Failed opening 'D:\home|site|wwwroot|wp-content|plugins\google-site-
kit/third-party/vendor/composer/autoload_classmap.php'forinclusion
(include_path=';C:|php\pear')inD:|home|site|wwwroot|wp-content\plugins\google-site-
kit|includes\loader.php on line 28

Warning: array_merge(): Expected parameter 2 to be an array, bool given in
D:|home|site|wwwroot|wp-content\plugins|google-site-kit|includes|loader.phponline28
Warning: require (D: home|site|wwwroot|wp-content plugins\google-site-kit/third-
party/vendor/autoload_files.php): failed to open stream: No such file or directory in
D:\home|site|wwwroot|wp-content\plugins(google-site-kit\includes|loader.php on line 51

Fatal error: require(): Failed opening required 'D:\home|site|wwwroot wp-
content|plugins\google-site-kit/third-party/vendor/autoload_files.php'
(include_path=!;C:|php|pear')inD:(home|sitelwwwroot|wp-content|plugins|google-site-
kitlincludes\loader.php on line 51

**Comment by patrickebates** [comment]
Not sure what to tell you.  I just downloaded the pluging and enabled it on a dev/test site.  Never used this plugin before myself, but it seems to be working?  Went through site setup with Google, etc.

**Comment by benjamingranados** [comment]
Ok, then it just is my website maybe... Thank you for testing on another site!

**Comment by benjamingranados** [comment]
Thank you very much for testing; thought it was the plugin but it was my site. After stopping and restarting the WebApp in Azure, and by reinstalling the plugin, it worked! you pointed me in the right direction!!!!
