### ISSUE TITLE
Trying to activate "Project Nami Full Text Search" plugin 

### ISSUE THREAD

**Issue by AposKaragiannis** [ProjectNami/projectnami#482]
I'm trying to activate "Project Nami Full Text Search" plugin  in Wordpress installed on Xampp server running on localhost.
PHP Version 8.1.6 , projectnami ver.: 3.0.1

I get the message:
Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method PN_Fulltext_Search::activate() cannot be called statically in C:\xampp\htdocs\prjNami\wp-includes\class-wp-hook.php:307 Stack trace: #0 C:\xampp\htdocs\prjNami\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #1 C:\xampp\htdocs\prjNami\wp-includes\plugin.php(476): WP_Hook->do_action(Array) #2 C:\xampp\htdocs\prjNami\wp-admin\plugins.php(194): do_action('activate_pn-ful...') #3 {main} thrown in C:\xampp\htdocs\prjNami\wp-includes\class-wp-hook.php on line 307

Thanks!

**Comment by nickLacatusu** [comment]
Had the same issue.
After checking the folder access permissions (check that the wp-content folder is not read only), I am able to Activate the plugins.
