### ISSUE TITLE
Cant activate Project Nami Full Text Search

### ISSUE THREAD

**Issue by JenniferSweden** [ProjectNami/projectnami#487]
Hello
When I am trying to activate Project Nami Full Text Search I get this error 

Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($function) must be a valid callback, non-static method PN_Fulltext_Search::activate() cannot be called statically in C:\inetpub\wwwroot\wp-includes\class-wp-hook.php:307 Stack trace: #0 C:\inetpub\wwwroot\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters() #1 C:\inetpub\wwwroot\wp-includes\plugin.php(476): WP_Hook->do_action() #2 C:\inetpub\wwwroot\wp-admin\plugins.php(194): do_action() #3 {main} thrown in C:\inetpub\wwwroot\wp-includes\class-wp-hook.php on line 307

Environment : Windows 2022 Server, MSSQL 2019 Express with adv features and Full text search installed and service started
The user is SA and shall be allowed to create the full text catalogue

Thanks
Jennifer

**Comment by patrickebates** [comment]
Finally duplicated this error.  Looks like the Activate and Deactivate functions need to be declared as Static now.  Might be a PHP 8.x thing.  Will be releasing a fix in the very near future.  In the meantime, you can add `static` in front of those function definitions to move forward.
