### ISSUE TITLE
Undefined variable: groupby in wp-includes\class-wp-term-query.php

### ISSUE THREAD

**Issue by PHuhn** [ProjectNami/projectnami#489]
I'm running ProjectNami on my Windows 10 laptop.  I updated to 3.0.3 (WordPress 6.0.3) on a test site and I'm getting a notice on all pages of:

`Undefined variable: groupby in C:\inetpub\ ... \wp-includes\class-wp-term-query.php on line 754`

I checked your source versus WordPress's source and yours is different, so I'm alerting you this issue.  The `groupby` variable only appears twice in `class-wp-term-query.php` as follows:

```
    public function get_terms() {
        ...
        $this->sql_clauses['limits']  = $limits;
        if ( $distinct ) {
            $groupby = "group by $fields $orderby_fields";
        }

        $this->request = "
            {$this->sql_clauses['select']}
            {$this->sql_clauses['from']}
            {$where}
            {$groupby}
            {$this->sql_clauses['orderby']}
            {$this->sql_clauses['limits']}
        ";

        $this->terms = null;
```

I've limited PHP programming experience, but I think `groupby` is out-of-scope.  I placed a 
```
        $groupby = "";
```
at the beginning of the function `get_terms()`, and that solved the problem.

**Comment by patrickebates** [comment]
Resolved this with https://github.com/ProjectNami/projectnami/commit/4cc4d0674a3f8415f8633dd0d1f560f45a299f7d
Included in 3.0.4 as part of PHP 8.1 support.
