### ISSUE TITLE
Workaround to update to WordPress 6.1

### ISSUE THREAD

**Issue by sikitrakix** [ProjectNami/projectnami#498]
Hello

I am required to update to WordPress 6.1 to address some security vulnerabilities but I know you have not released a Project Nami version that contains 6.1 or higher. Is it possible to know how if there are any workarounds or mitigations that we can put in place while you work on your next release?

Alternatively, do you have any expected release date for this new version?

Thanks

**Comment by patrickebates** [comment]
I finally have a merge attempt that has left me with only about 25 rejections to manually process.  Provided there are no big surprises, I should be able to begin testing within a day and hope to release merge with 6.1.1 sometime this coming week.

**Comment by patrickebates** [comment]
PN 3.1.1 released.  After getting the merge down to that few rejections, it went pretty fast.

**Comment by sikitrakix** [comment]
Hi Patrick

That was quick! Thanks for the update. 
I have never updated Project Nami before and as such would like to ask if you have any upgrade instructions available?
I found a link to a video in your site but the video is unavailable. Also, I don't have the option to automatically update in the admin console so it would have to be a manual update.

Any help with this will be greatly appreciated
Thanks again!

**Comment by patrickebates** [comment]
It's a manual update unless you connect your site to the GitHub repo.  If you are running on Azure Web App, I can walk you through that.

**Comment by sikitrakix** [comment]
Hi Patrick

Thank you for the quick reply. That is exactly my case, running it on Azure web app. 
If you can walk me through it or send me the steps I would greatly appreciate it.

**Comment by sikitrakix** [comment]
Hi Patrick

Checking if you have the upgrade instructions available.

Thanks again!
