### ISSUE TITLE
Project Nami Full Text Search not working

### ISSUE THREAD

**Issue by Flying-Bas** [ProjectNami/projectnami#504]
Hello, 
A self hosted website on the latest project nami version with Project Nami Full Text Search enabled.
When searching for words on the Wordpress website the result is a list with the latest posts and  not a list with posts containing those words that has been searched for.

When I de-activate Project Nami Full Text Search, all is working fine. It used to work all fine. I think until I upgraded to the latest PHP version that came with the previous project nami version a few weeks ago.
How is this possible?

thanks
Bas

**Comment by patrickebates** [comment]
Had this reported just over a week ago, and while I have been able to duplicate the issue, I have not yet been able to generate an error log to see what is breaking.  If you are able to generate an error, please let me know what it is.

**Comment by Flying-Bas** [comment]
Hi Patrick,
I’ll try, but I am not sure if I am the right person to ask for debugging logs.

**Comment by patrickebates** [comment]
Please see this new ticket for an update to resolve your issue.
https://github.com/ProjectNami/projectnami/issues/505
