### ISSUE TITLE
Patterns not supported

### ISSUE THREAD

**Issue by PHuhn** [ProjectNami/projectnami#511]
Hey Patrick:
Per this article:
[Create a Pattern](https://wordpress.com/support/wordpress-editor/create-a-pattern/)
WordPress supports sync'd and non-sync reusable parts now called patterns.  I do not find it in 6.2.2 Project Nami version.
Phil

**Comment by patrickebates** [comment]
I'm not seeing this either, but then until now I have been mostly using Classic Editor to support some older themes.

Wondering if this might be a theme issue on my end as well.  Will look into it more.  The feature should be there, as when merging new WP versions the CSS and JS files are completely copied over by the lastest version of WP.

**Comment by PHuhn** [comment]
Hey Patrick:
I moved to Gutenberg when it was the main editor.  Full Site Editing is a great reason to move to Gutenberg.  Menus are a big change under FSE.  Patterns with non-async allows one to create ones own reusable component without a plugin.  I'm trying to create a team member reusable component.
Phil

**Comment by PHuhn** [comment]
Hey Patrick:
Any word on this issue.  I tried to find how I could find the version of the for the blocks, but no luck.
Phil

**Comment by patrickebates** [comment]
I'm dumbfounded actually.  Planning to see what happens after a full merge check with 6.3 later this week.

**Comment by PHuhn** [comment]
Hey Patrick:
Any word on why **patterns** are not showing up.  I'm assuming that the build

**Comment by PHuhn** [comment]
Hey Patrick:
I just downloaded Gutenberg and installed it now I'm even later release than 6.2.2 version.
Phil

**Comment by PHuhn** [comment]
I'm cool with the download.
