### ISSUE TITLE
Error enabling WPML

### ISSUE THREAD

**Issue by guidooliveira** [ProjectNami/projectnami#56]
I'm getting this error when trying to enable the WPML 3.3.7 plugin

Fatal error: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near '36'. in D:\home\site\wwwroot\wp-content\plugins\sitepress-multilingual-cms\inc\setup\sitepress-schema.php on line 346

**Comment by pippercameron** [comment]
The plugin is making direct SQL calls with `$wpdb` that are for MySQL and being properly translated into MSSQL syntax as a fallback. We'll look into the feasibility of fixing this in the translation code.

Thanks for reporting!

**Comment by guidooliveira** [comment]
Do you need any files for this?

**Comment by pippercameron** [comment]
Oh, it's a premium plugin. @guidooliveira, can you copy the actual SQL call and paste it here?

**Comment by guidooliveira** [comment]
probably should send it through a private channel, wich one would you prefer?

**Comment by pippercameron** [comment]
Even though it's a premium plugin, it's probably still GPL, right? Also, it's just the SQL I need, so not really an issue either way. :)

**Comment by guidooliveira** [comment]
`		$icl_translation_sql = "
             CREATE TABLE IF NOT EXISTS {$wpdb->prefix}icl_core_status (
            `id` BIGINT NOT NULL auto_increment,
            `rid` BIGINT NOT NULL,
            `module` VARCHAR( 16 ) NOT NULL ,
            `origin` VARCHAR( 64 ) NOT NULL ,
            `target` VARCHAR( 64 ) NOT NULL ,
            `status` SMALLINT NOT NULL,
            PRIMARY KEY ( `id` ) ,
            INDEX ( `rid` )
            ) {$charset_collate}
      ";
		if ( $wpdb->query( $icl_translation_sql ) === false ) {
			throw new Exception( $wpdb->last_error );
		}

		$icl_translation_sql = "
            CREATE TABLE IF NOT EXISTS `{$wpdb->prefix}icl_content_status` (
            `rid` BIGINT NOT NULL ,
            `nid` BIGINT NOT NULL ,
            `timestamp` DATETIME NOT NULL ,
            `md5` VARCHAR( 32 ) NOT NULL ,
            PRIMARY KEY ( `rid` ) ,
            INDEX ( `nid` )
            ) {$charset_collate} 
      ";
		if ( $wpdb->query( $icl_translation_sql ) === false ) {
			throw new Exception( $wpdb->last_error );
		}

		$icl_translation_sql = "
            CREATE TABLE IF NOT EXISTS `{$wpdb->prefix}icl_node` (
            `nid` BIGINT NOT NULL ,
            `md5` VARCHAR( 32 ) NOT NULL ,
            `links_fixed` TINYINT NOT NULL DEFAULT 0,
            PRIMARY KEY ( `nid` )
            ) {$charset_collate}  
      ";
		if ( $wpdb->query( $icl_translation_sql ) === false ) {
			throw new Exception( $wpdb->last_error );
		}

		$icl_translation_sql = "
            CREATE TABLE IF NOT EXISTS `{$wpdb->prefix}icl_reminders` (
            `id` BIGINT NOT NULL ,
            `message` TEXT NOT NULL ,
            `url`  TEXT NOT NULL ,
            `can_delete` TINYINT NOT NULL ,
            `show` TINYINT NOT NULL ,
            PRIMARY KEY ( `id` )
            ) {$charset_collate}  
      ";
		if ( $wpdb->query( $icl_translation_sql ) === false ) {
			throw new Exception( $wpdb->last_error );
		}

	} catch ( Exception $e ) {
		trigger_error( $e->getMessage(), E_USER_ERROR );
		exit;
	}`

**Comment by pippercameron** [comment]
Yikes. Table creation. :) We could work on a translation, but other parts of the plugin will probably still break. This is likely just the first point of breakage, but we'll look into it.

**Comment by guidooliveira** [comment]
At the moment i'm more worried with importing the content to azure, this particular one could wait :)

**Comment by pippercameron** [comment]
Sounds good. I'll reply to you over in #63. :)

**Comment by guidooliveira** [comment]
I really appreciate the help :)
