### ISSUE TITLE
Error of Maximum execution time when importing a XML using the importer plugin

### ISSUE THREAD

**Issue by guidooliveira** [ProjectNami/projectnami#63]
i'm receiving this error when performing the import to migrate a blog, several images were imported but when the posts begin, i get this error

Página “Sobre” já existe.
Falha ao importar Post “Tratar mensagens de log do event viewer do Windows com Powershell”
Falha ao importar Post “List GPO Settings”
Falha ao importar Post “Valide se as GPOs do SYSVOL constam no AD com Powershell”
Falha ao importar Post “Acesso negado para administrador via PSRemoting”
Post “Descubra a data de instalação do Windows usando Powershell” já existe.
Fatal error: Maximum execution time of 60 seconds exceeded in D:\home\site\wwwroot\wp-includes\class-wp-http-curl.php on line 309

**Comment by pippercameron** [comment]
How many posts are in your import file? You have a few options here.

1. Split the XML file into smaller chunks (there are tools for this) and import each of them on their own.
2. Increase the maximum execution time in a custom `php.ini`.

Both of these can be used together.

**Comment by guidooliveira** [comment]
The XML File is about 1.4Mb, it contains around 56 posts and I’ve changed the maximum execution time to 6000 I the .user.php file

**Comment by patrickebates** [comment]
If you are performing this import on an Azure Web App, note that your maximum execution time will be controlled by the effects of the reverse proxy which would limit you to between 180 and 300 seconds.  Repeating the import should cause only the missing items to be processed.

**Comment by pippercameron** [comment]
After changing the maximum execution time, are you still getting the fatal referencing 60 seconds?

>Repeating the import should cause only the missing items to be processed.

Yep. You will, however, get duplicate postmeta on each pass -- in case that looks alarming, it's expected behavior.

**Comment by guidooliveira** [comment]
even changing the max execution time i get the same 60 second error, however the posts aren't getting dupplicated

**Comment by pippercameron** [comment]
>even changing the max execution time i get the same 60 second error, however the posts aren't getting dupplicated

Right. Posts won't duplicate due to the `post_exists` check the importer does. Can you paste your `php.ini` contents here so I can see them? Also, can you tell me what directory you're putting it in and the Application setting name and value you're using in the portal let PHP know where to look for other `.ini` files?

**Comment by guidooliveira** [comment]
i'm using the default PHP.ini for azure web apps in version 5.6, my .user.ini has the following at the moment:

[PHP]
default_socket_timeout = 600
memory_limit = 256M
post_max_size = 64M
upload_max_filesize = 64M
max_execution_time = 1200
max_input_time = 1200

**Comment by patrickebates** [comment]
I seem to recall we located one or more places in Core that reset the timeout to 60.  Is it possible those have returned?

**Comment by guidooliveira** [comment]
how can i determine that? i could use Kudo to quickly change the file and test that

**Comment by patrickebates** [comment]
I'm trying to remember myself.  I've executed several searches, but haven't found anything yet.  Hoping Spencer can tell me if I'm right or wrong on this.

**Comment by pippercameron** [comment]
Here's a brief explanation of how to get this to work. :)

1. Create an arbitrary directory somewhere writable on site (or in your Git deployment or other source control -- wherever/however you're publishing to the server). You could also just use an existing directory. That's fine too.

2. We'll assume we created the directory `config` in `wwwroot` -- `wwwroot` is where the installation lives and where your code/deployments get published to.

3. Add a file `php.ini` and put these contents in it.

```ini
; These two values can both be larger, but it's likely you'll hit the timeout before you reach it.
; It's good to set these high, since you may want to upload large media (the default values are 8M each).
; Adjust as needed.
upload_max_filesize = 512M
post_max_size = 512M

; The maximum execution time per request.
; In an Azure Website, 300 seconds is the global maximum.
; Setting this higher than 300 won't give you more than 300.
max_execution_time = 300
```

4. Now in your app settings in the portal, add `PHP_INI_SCAN_DIR` and set it to `D:\home\site\wwwroot\config`.

5. Restart the Website.

Follow these steps to increase the execution time. 5 minutes should be enough for your import size.

WP Core doesn't change max input time, but it does adjust memory limits -- which aren't directly applicable here.

**Comment by pippercameron** [comment]
>i'm using the default PHP.ini for azure web apps in version 5.6, my .user.ini has the following at the moment:

It sounds like these values aren't being set properly. Can you try dropping a call to `phpinfo()` somewhere in a `.php` file on the site and run it? Look for the values you're trying to set, like `max_execution_time` and paste here what you see. You should see two values, the current value first, followed by the default value.

**Comment by pippercameron** [comment]
If `phpinfo()` reveals the values are set properly, you can disregard the steps I outlined above, naturally.

**Comment by guidooliveira** [comment]
phpinfo was returning the right intel, so i've decided to look for "set_time_limit(60)" in the files, and i've found at line 3632 from the file deprecated.php within the wp-includes folder,the following:

`@set_time_limit( 60 );`

after changing it to 160, the import process finished sucessfully.

so, it seems that core is hard coding this value in this file, but there could be others :)

**Comment by pippercameron** [comment]
Good catch. I didn't realize that was still being used for retrieving media during import since it's been deprecated.

It's not a good idea to call `set_time_limit()` with a low value during import. It's effectively resetting PHP's timeout counter and limiting you to another 60 second of runtime regardless of your `max_execution_time`, if another call to `set_time_limit()` is not made to reset the counter again.

I think the goal here is noble (i.e. trying to give you extra time to fetch remote objects), but an exception should be made for imports since it actually has an opposite effect.. I'll open a ticket with WP Core.

Thanks again for pointing this out.
