### ISSUE TITLE
Changing a user password generates a 500 error

### ISSUE THREAD

**Issue by yorek** [ProjectNami/projectnami#67]
If I try to change the password of an account, I receive and HTTP 500 error for a timeout. If I try to change name or surname I don't have this problem.

**Comment by pippercameron** [comment]
Thanks for reporting! We're looking into this now.

**Comment by patrickebates** [comment]
While I'm seeing that it takes a few seconds (maybe four) longer to update a user while changing the password, I'm not seeing any timeout or 500 errors and nothing in the error logs.

Could there be something else contributing to this?  A plugin perhaps?

**Comment by pippercameron** [comment]
I would recommend disabling other plugins and trying again. I'm also unable to duplicate. Changing the password took about a second both times I tested.

**Comment by yorek** [comment]
Found it! It seems to be the "SMTP Configuration" plugin. As soon as I enable it I cannot change the Password anymore. It's probabily related to the fact that SMTP config was wrong.

**Comment by yorek** [comment]
mmmm...I've changed the configuration to the correct one and I'm still having the same problem. I'm using it on Azure, using the SendGrid service.

**Comment by pippercameron** [comment]
Can you link me to the plugin's code? There's likely a hook in play here breaking this.

**Comment by yorek** [comment]
Here's the code: [projectnami/wp-content/plugins/smtp-configuration/smtp-configuration.php](https://github.com/ProjectNami/projectnami/blob/master/wp-content/plugins/smtp-configuration/smtp-configuration.php)

**Comment by pippercameron** [comment]
Oh, I wrote that.. Ahem, I'll have a look. ;) It probably needs updating since it hasn't been touched in a few years.

**Comment by yorek** [comment]
Thanks!

**Comment by pippercameron** [comment]
Strange. It doesn't appear to be a bug in the SMTP plugin. I just set it up and tested and was able to change my password without any issues.

I tried both with and without correct SMTP credentials and it worked the same both times, with the obvious exception that I didn't receive an email with broken credentials.

The fact that an email is sent for a password change is probably related to the timeouts here. Any more info you can provide?

**Comment by yorek** [comment]
Nope sorry...I just get stuck with the timeout error. Maybe is something specific to the SendGrid service?

**Comment by pippercameron** [comment]
It could be. If you're feeling adventurous and want to test more, let us know how it goes! I don't think there's too much more we can do here from this end, though.

**Comment by yorek** [comment]
Sure, I'll try to understand if there is some specific problem with SendGrid. If I discover something I'll post it here. In the meantime, I'm using the "Easy WP SMTP" that works well. Thanks!

**Comment by pippercameron** [comment]
>In the meantime, I'm using the "Easy WP SMTP" that works well. Thanks!

Oh, that's an interesting piece of the puzzle. Perhaps there is an unsupported feature SendGrid needs to be fully setup? Can you share generally how you have/had this set up for each plugin? Just dummy data/fields would be great.
