### ISSUE TITLE
error when calling wp-cron from command line

### ISSUE THREAD

**Issue by guidooliveira** [ProjectNami/projectnami#69]
I'm getting the following error when trying to run wp-cron manually:

D:\home>"D:\Program Files (x86)\PHP\v5.6\php.exe" D:\home\site\wwwroot\wp-cron.php cli/auto

Erro de banco de dados do WordPress [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Cannot insert duplicate key row in object 'dbo.gd_options' with unique index 'gd_options_UK1'. The duplicate key value is (_transient_doing_cron). Code - 2601 para a consulta IF NOT EXISTS (SELECT \* FROM [gd_options] WHERE [option_name] = '_transient_doing_cron') INSERT INTO [gd_options]([option_name], [option_value], [autoload]) VALUES ('_transient_doing_cron', '1460836545.4543950557708740234375', 'yes') else UPDATE [gd_options] set [option_value] = '1460836545.4543950557708740234375', [autoload] = 'yes' where [option_name] = '_transient_doing_cron' feita por set_transient, add_option

**Comment by pippercameron** [comment]
That's an odd error since the SQL call should prevent insertion of a duplicate key with `IF NOT EXISTS`. Looking into it.

**Comment by pippercameron** [comment]
FWIW, this isn't directly because it's called via CLI. This also happens during the regular cron execution during a web request.

**Comment by patrickebates** [comment]
It's also occurring inconsistently.  Wondering if your suspicion of this being some sort of race condition might be on target.

**Comment by pippercameron** [comment]
I'm working on duplicating reliably.

**Comment by pippercameron** [comment]
The race condition would almost need to be a failure in the cron to get a lock properly, because this sort of thing should already be prevented.

**Comment by patrickebates** [comment]
Here's a different take on the query.  We should test to determine if it is more reliable.
`INSERT INTO [wp_options] ([option_name], [option_value], [autoload]) VALUES ('_transient_doing_cron', '1460976629.3438420295715332031250', 'yes') where not exists (select * from [wp_options] where [option_name] = '_transient_doing_cron')`

**Comment by guidooliveira** [comment]
Should i run this on my database?

**Comment by pippercameron** [comment]
@guidooliveira, you can try it if you feel like testing to see if that fixes the race condition for you.
