### ISSUE TITLE
Pictures not shown - after latest update

### ISSUE THREAD

**Issue by TheDaveKurth** [ProjectNami/projectnami#70]
After the latest Wordpress Update, just a few days old. I've updated my installation as shown in the video on channel9. Now since then, the blogs don't show my header pictures. Surprisingly IE shows them, but none of the other browsers, any idea why this could have happened and how I could fix it?

Surprisingly, when you click on the "fileName" where the picture should be shown, it can load the picture. I just tried it now also from a Mac with FireFox, Chrome and Safar, non of which show the picture. Internet Explorer on Win10 and on Windows 8.1 on my phone, show the blogs as they should be. I did delete all the cache and so on in the browser. 

Any help is highly appreciated. My site: http://www.thedavekurth.com

**Comment by patrickebates** [comment]
Version 1.3.1 contained a fix for this.  Have you updated to it yet?

**Comment by pippercameron** [comment]
It looks like you're still running 1.3.0.

```html
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.thedavekurth.com/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.5" /><meta name="projectnami:version" content="1.3.0" />
```

Updating will fix this, as @patrickebates mentioned. :)

**Comment by TheDaveKurth** [comment]
Hi guys, thank you so much. After the message from Patrick I run the update and it did the trick. Sorry that I didn't find it on my own. I wish you a great rest of the weekend.

**Comment by patrickebates** [comment]
Fixed in https://github.com/ProjectNami/projectnami/commit/c00de1bd72f2c3fe4af34c4bc5bb769ca5d8704d
