### ISSUE TITLE
non terminating error in wp-db.php on page load

### ISSUE THREAD

**Issue by guidooliveira** [ProjectNami/projectnami#71]
i'm getting the following error shown when loading my website on Edge, it loads sucessfully after a couple of seconds, but since i believe it was not intended i thought of reporting it.

Warning: mysql_num_fields(): supplied resource is not a valid MySQL result resource in D:\home\site\wwwroot\wp-includes\wp-db.php on line 3021

Running it on a Web App with SSL and custom DNS enabled Standard01

http://guidooliveira.com

**Comment by pippercameron** [comment]
Thanks for reporting! We'll look into it. In the meantime, I'd suggest disabling `WP_DEBUG` to suppress visually displaying those warnings -- and also in general for production sites.

**Comment by pippercameron** [comment]
Interestingly, this has been around since the first build 3 years ago. However, the warnings have been suppressed by WP Core until 4.5. See [here](https://github.com/ProjectNami/projectnami/blame/master/wp-includes/wp-db.php#L3021).

I'll leave this open for now since we need to look at refactoring that.

**Comment by guidooliveira** [comment]
i've just checked WP_DEBUG is set to false on WP-config, perhaps it was enabled somewhere by some plugin.

**Comment by pippercameron** [comment]
Do you have `display_errors` on in your `.user.ini` / `php.ini`?

**Comment by guidooliveira** [comment]
i don't, already checked it, i'll see if some plugin is defining that somewhere else. I'm using W3 Total Cache with Azure CDN

**Comment by pippercameron** [comment]
>i'll see if some plugin is defining that somewhere else.

Yeah, something's doing it somewhere.

**Comment by guidooliveira** [comment]
i couldn't locate any setting other than define(WP_DEBUG, false) on the wp-config file, and i'm still getting error messages, could this be due to connection limit with the database, like with ClearDB ?

**Comment by pippercameron** [comment]
>i couldn't locate any setting other than define(WP_DEBUG, false) on the wp-config file, and i'm still getting error messages, could this be due to connection limit with the database, like with ClearDB ?

No, it's not. If you're unable to turn off error displaying (which is the better option), you can add back the `@` in front of `mysql_num_fields()` to suppress the warning.

**Comment by guidooliveira** [comment]
like this?

		if ( $this->use_mysqli ) {
			@$num_fields = mysqli_num_fields( $this->result );
			for ( $i = 0; $i < $num_fields; $i++ ) {
				$this->col_info[ $i ] = mysqli_fetch_field( $this->result );
			}
		} else {
			@$num_fields = mysql_num_fields( $this->result );
			for ( $i = 0; $i < $num_fields; $i++ ) {
				$this->col_info[ $i ] = mysql_fetch_field( $this->result, $i );
			}
		}

**Comment by pippercameron** [comment]
Almost, the `@` symbol goes in front of the function you want to suppress errors from: `@mysql_num_fields()`

**Comment by guidooliveira** [comment]
the warning still appears =/

**Comment by Angelixion** [comment]
I have fixed it like this, since i do not use mysql and it shouldnt do it if you dont have mysql.

```
protected function load_col_info() {
	if ( $this->col_info )
		return;
    
	if ( $this->use_mysqli ) {
		$num_fields = mysqli_num_fields( $this->result );
		for ( $i = 0; $i < $num_fields; $i++ ) {
			$this->col_info[ $i ] = mysqli_fetch_field( $this->result );
		}
	} else {
	    return;
		//$num_fields = mysql_num_fields( $this->result );
		//for ( $i = 0; $i < $num_fields; $i++ ) {
		//	$this->col_info[ $i ] = mysql_fetch_field( $this->result, $i );
		//}
	}
}
```

**Comment by pippercameron** [comment]
>..since i do not use mysql and it shouldnt do it if you dont have mysql.

Agreed. This whole block here still needs to be refactored, though, at some point -- preferably in the next version of PN . We'll need to look at how `load_col_info()` is being used throughout Core. Any takers for fixing this? ;)

**Comment by patrickebates** [comment]
And therein lies the problem.  `load_col_info()` is only called in two places within Core, and one of them is inside `get_col_info` which isn't called anywhere within Core.  That's why we haven't encountered this issue ourselves.  It must be called by just a few plugins.

**Comment by pippercameron** [comment]
That makes sense. Let's still try to ship a fix in the next version.

**Comment by planetburns** [comment]
So what's the best way to fix this please? Is it code or config? Thanks in advance.

**Comment by Angelixion** [comment]
@planetburns Read my comment above, needs to be refactored but until then, put a `return` in the `else`, it will make stop the error and destroying your website like it happened to me.

**Comment by guidooliveira** [comment]
If i supress the errors with the @ sign on the latest release, i get a internal server error. And i still get the warnings, mine on line 3035 though

**Comment by patrickebates** [comment]
Found some code from an old translation drop-in attempt that might can be modified to fix this, but I've been waiting on a reply from a resource at Microsoft that I reached out to.  Want to be certain I haven't overlooked another option.

**Comment by guidooliveira** [comment]
totaly unrelated but microsoft will also release the driver for PHP 7, would this also happen there?

**Comment by patrickebates** [comment]
The fix I'm looking at should work with either driver.  But better support in the new driver would be appreciated.
