### ISSUE TITLE
Best place to add an add_filter('query','functionname')

### ISSUE THREAD

**Issue by KY4U** [ProjectNami/projectnami#75]
Some queries that are run through the translations.php script look like this:

`UPDATE [wp_aiowps_login_activity] SET [logout_date] = %1$s WHERE [user_id] = 13 AND [login_ip] = %2$s AND [logout_date] = %3$s`

The query that SQL executes looks like this (login_ip shown is masked):

`UPDATE [wp_aiowps_login_activity] SET [logout_date] = '2016-04-28 13:45:45' WHERE [user_id] = 0 AND [login_ip] = 'xxx.xx.xxx.xxx' AND [logout_date] = '0000-00-00 00:00:00'`

The translations.php script would not catch the conversion of '0000-00-00 00:00:00' to '0001-01-01 00:00:00'

Should a query filter ( **add_filter('query','functionname')** ) and function be added to the code?  If so, should the translate function be called from within that function?  If you agree with adding the filter and the function, where is the best place in the code to place these?

**Comment by patrickebates** [comment]
Do you have output in either php_errors.log or translation.log which shows this occurring?  The translation layer should only be called after all parameters have been filled in and the completed query submitted to the SQL Server.  Line 729 of translations.php should be able to catch this.

**Comment by KY4U** [comment]
I added a wp_mail() line just prior to 729.  Here are multiple examples of queries that were sent to me

`SELECT DISTINCT wp_posts.ID , wp_posts.post_date FROM wp_posts  INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) WHERE 1=1  AND (
  ( wp_postmeta.meta_key = %1$s AND CAST(wp_postmeta.meta_value AS CHAR) = %2$s )
) AND wp_posts.post_type = %3$s AND ((wp_posts.post_status = %4$s))  ORDER BY wp_posts.menu_order, wp_posts.post_date DESC OFFSET  0 ROWS FETCH NEXT 100 ROWS ONLY`

`SELECT post_type, MAX(post_modified_gmt) AS date
                        FROM wp_posts
                        WHERE post_status IN (%1$s,%2$s)
                                AND post_type IN (%3$s,%4$s,%5$s,%6$s,%7$s,%8$s,%9$s,%10$s,%11$s,%12$s)
                        GROUP BY post_type
                        ORDER BY post_modified_gmt DESC`

`SELECT COUNT(ID) as Computed
                        FROM wp_posts

                        WHERE post_status IN (%1$s,%2$s)
                                AND post_password = %3$s
                                AND post_date != %4$s
                                AND post_type = %5$s`

**Comment by KY4U** [comment]
My original query sent to me at line 729
`UPDATE [wp_aiowps_login_activity] SET [logout_date] = %1$s WHERE [user_id] = 13 AND [login_ip] = %2$s AND [logout_date] = %3$s`

The error log showed this:
`[28-Apr-2016 15:53:26 UTC] WordPress database error [Microsoft][SQL Server Native Client 11.0][SQL Server]Conversion failed when converting date and/or time from character string. Code - 241 for query UPDATE [wp_aiowps_login_activity] SET [logout_date] = '2016-04-28 15:53:25' WHERE [user_id] = 16 AND [login_ip] = xxx.xxx.xx.xx' AND [logout_date] = '0000-00-00 00:00:00' made by require_once('D:\home\site\wwwroot\wp-admin\admin.php'), require_once('D:\home\site\wwwroot\wp-load.php'), require_once('D:\home\site\wwwroot\wp-config.php'), require_once('D:\home\site\wwwroot\wp-settings.php'), do_action('init'), call_user_func_array, AIO_WP_Security->wp_security_plugin_init, do_action('aiowps_force_logout_check'), call_user_func_array, AIOWPSecurity_User_Login->aiowps_force_logout_action_handler, AIOWPSecurity_User_Login->wp_logout_action_handler
`

**Comment by KY4U** [comment]
@patrickebates are you seeing similar queries at line 729?

**Comment by patrickebates** [comment]
Not yet.  I hope to have some time over the weekend to test with this specific plugin.

**Comment by patrickebates** [comment]
I think you've identified an issue related to something else which I identified some time back, but it seemed to be randomly occurring as I couldn't reliably reproduce it.  We're looking into a broad solution for both.

**Comment by pippercameron** [comment]
Noting we'll need to move the current string replacement for date values since it's never worked here. The translation class parses out the values into placeholders, so there are no values currently to manipulate when it gets to `translation_specific()`.

I think instead of adding another filter on `query`, we can take care of it later/earlier from within the translation class. It's an easy fix.

**Comment by pippercameron** [comment]
Here's a first pass at refactoring this: 0072c820f31cb5e161037d0bbeefd4708fb373a4

I've added a new function `pre_translate_query()` to accommodate query manipulation before any translations are done and before the values are parsed out.

The replacement has also been improved by removing the single quotes (since double quotes could be possible and would break the match). The function has also been changed from `str_ireplace()` to `str_replace()` since case sensitivity isn't a factor here.

The next thing we'll need to do is move the existing PN specific additions to `translate_specific()` since value manipulation won't work there anyway.

**Comment by pippercameron** [comment]
Filter added in 65995ab.

**Comment by pippercameron** [comment]
Echoing the chat I just had with @patrickebates, we're going to add a regex instead of string replacement here to try to avoid botching up legitimate uses of `0000-00-00 00:00:00`, like in `post_content`.

Let's leave this issue open until that's patched.
