### ISSUE TITLE
Frequent http 500 and timeout erros

### ISSUE THREAD

**Issue by guidooliveira** [ProjectNami/projectnami#76]
I'm getting frequent 500 erros in the homepage and even more to access the dashboard, has this been experienced by anyone else?

**Comment by patrickebates** [comment]
Are you running on Azure Web Apps, and if so what service tier (Free, Shared, Basic, Standard, Premium) ?

**Comment by guidooliveira** [comment]
Yes i am,standard 1 tier

Sent from my Windows Phone
________________________________

**Comment by patrickebates** [comment]
It shouldn't be server performance then.  ProjectNami.org itself runs as one of multiple sites on a Basic 1 with a Basic SQL DB behind it.  What about plugins and themes?  Could you have any which might be causing issues?  If you disable plugins and switch to a default theme, do the problems persist or go away?

**Comment by patrickebates** [comment]
Are you using our Blob Cache on your site?  If so, are you using the cache loader web job?  We use it to enable high performance with our site and can help you configure it for a similar result with your site.

**Comment by guidooliveira** [comment]
mostly i'm unable to acess the dashboard, after restarting the website it gets back to normal. I'm using W3 Total Cache with Azure CDN, media files are stored in blob also. performance itself isn't and issue, it's just the 500 error when accessing the site. Average pageload time is 2.5 seconds. For the plugins i couldn't determine wich one was causing it. I have the 1.3.1 branch version deployed at the moment

**Comment by patrickebates** [comment]
W3TC is a fine product, but its Enhanced full-page caching mode is not available on IIS.  I would recommend that you try our Blob Cache system as an alternative for full-page caching.  For starters, our method delivers cache hits without starting WP or even the PHP runtime itself.  This produces a significant improvement in server performance.

**Comment by guidooliveira** [comment]
Can it coexist with w3tc? If so i'd gladly put it to work

Sent from my Windows Phone
________________________________

**Comment by patrickebates** [comment]
It can, though you will want to disable full-page caching within W3TC.  The other features of W3TC should be fine.

**Comment by guidooliveira** [comment]
is there a link explaining how to properly configure it?

**Comment by patrickebates** [comment]
http://projectnami.org/blob-cache/
Everything you need should be in the text files within the ZIP.  The one thing to keep in mind is that if you use the Cache Loader (and I recommend that you do) you need to set the Cache Duration / TTL to a number greater than the time between executions of the Web Job.  For example, if you run the job every two hours then you will want a Cache Duration of at least 2.5 hours (9000 seconds).

**Comment by patrickebates** [comment]
And always dedicate a container in your storage account for use with Blob Cache.  You can share the account with other items, but not the container.  The Cache Cleanup job is designed to purge anything within the container which is either expired or not flagged with a Cache Duration.

**Comment by guidooliveira** [comment]
great, i set the expires header at 360000 seconds, so i should probably be fine. but i'll give it a try :) 

is there a plugin to test for these 500 errors in the dashboard?

**Comment by patrickebates** [comment]
None that I am aware of, but if these 500 errors are the result of sudden resource issues then this caching option should help greatly.  Eliminating the need for the PHP runtime to be loaded for public access can significantly reduce load.

**Comment by pippercameron** [comment]
The 500 errors should be in your `php-errors` file. I'd like to see that if you can grab it. This sounds like a plugin is making external requests. Another possibility, but probably less likely, is a plugin is doing to much in a single request and not finishing some of the time (causing the timeouts).

Any more info you can provide would be helpful.

**Comment by guidooliveira** [comment]
i tried enabling the cache plugin and after adding:
	<modules>
            <add name="ProjectNamiBlobCache" type="ProjectNamiBlobCache.CacheFrontEnd" />
        </modules>

to my web.config i got the white screen issue. The Bin folder is inside the wwwroot folder with the proper dll files.

**Comment by patrickebates** [comment]
Just to double-check, you have this Modules block inside the system.WebServer block in the web.config?  And you have the configuration key/value pairs set in App Settings?

**Comment by guidooliveira** [comment]
yes, and the app settings for both the plugin and the web jobs

**Comment by patrickebates** [comment]
If you leave the plugin enabled, but remove the Modules block from web.config, does the site operate normally when you are not logged into WordPress?  If so, when you look at the contents of the storage container, do you see hashed file names as this would indicate page output is being stored.

**Comment by guidooliveira** [comment]
I'm uploading the php_errors.log because i'm still getitng those errors, the Dashboard often goes blank when navigating in it.
[php_errors.zip](https://github.com/ProjectNami/projectnami/files/265429/php_errors.zip)

**Comment by guidooliveira** [comment]
I couldn't find anything that would cause these http 500 erros and timeouts, have you found anything on the php_errors file?

**Comment by patrickebates** [comment]
Nothing that seemed to indicate an answer.  Tell me, what version of PHP are you running, and is it 32-bit or 64-bit?  I did see something similar to your report over the weekend, but it was with testing I did with PHP 7 and an early release of SqlSrv 4.  Again, nothing in any log files to indicate a problem though.

**Comment by guidooliveira** [comment]
I’m currently using PHP 5.6 64-bit, on a Azure S01 App Instance. SQL Database is a S0 instance

**Comment by patrickebates** [comment]
I'm curious to know if switching back to 32-bit solves your 500 errors

**Comment by guidooliveira** [comment]
I’ll try it out and let you know, I’m also gathering telemetry with Application Insights so there could be more information there.

**Comment by guidooliveira** [comment]
I also forgot to mention the website has Always On enabled.

**Comment by patrickebates** [comment]
ProjectNami.org runs with AlwaysOn enabled as well, so I doubt that would be related.  But to add to the confusion, it seems we are also running PHP 5.6 64-bit.  I would have sworn we were still on 32-bit.

**Comment by guidooliveira** [comment]
changing it to 32-bit php has reduced a lot the problems i was having, any idea why this would happen?
