### ISSUE TITLE
Visual Composer not working after latest upgrade.

### ISSUE THREAD

**Issue by UstatSingh** [ProjectNami/projectnami#78]
Hi guys,
          I upgraded to the latest project nami update and VC stopped working properly. I also updated VC to the latest build as suggested by VC board for compatibility with wordrpress 4.5.1. however VC is still not working. VC is not picking up the correct columns. The headings on all pages come out as gibrish, and background images and videos dont load. For an example go to www.fabonista.com 

Any insight into what might be happening?

Ustat

**Comment by patrickebates** [comment]
I did a quick review of some recent posts on VC, and I have only two ideas.  First, could you please check your php_errors.log and translations.log for recent errors?  Second, have you looked into rolling back to an older version of PN?  I see where some people have needed to resort to this with vanilla WordPress as well.  If you are using Azure Web Apps and Sync'd to update, you should be able to roll back to an earlier deployment using the portal.

**Comment by UstatSingh** [comment]
Hi Patrick,
            I just reverted everything back including VC and site displays fine again. Completely mind boggling. Can you send me the threads on VC you are talking about?  Ill try to follow them untill they have a resolution.   Also nothing in the error or translation logs at all.

Thanks again

**Comment by patrickebates** [comment]
https://wordpress.org/support/topic/problems-using-visual-composer-with-wordpress-45

I think that would be the best one to follow, as it was active just a couple of hours ago.
