### ISSUE TITLE
Revolution slider Not working after plugin install and fix

### ISSUE THREAD

**Issue by GeoffreyEmery** [ProjectNami/projectnami#81]
# Buddy Press
install but can not create a group
****
# bbpress
can't reply to forums
****
# Revolution Slider
Fatal error causes site to crash 
This is a super common plugin that seems to be having a a issue with a column name they use. 
I have attached the theme zipto this post which fails on the rev slide plugin:
`Fatal error: Uncaught exception 'Exception' with message 'Insert query error - [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'advanced'.
---
Query: INSERT INTO [wp_revslider_css] ([handle], [settings], [hover], [params], [advanced]) VALUES ('.tp-caption.MarkerDisplay', '{"translated":5,"type":"text","version":"5.0"}', '{"color":"#ff0000","text-decoration":"none","background-color":"transparent","background-transparency":"1","border-color":"transparent","border-style":"none","border-width":"0","border-radius":["0px","0px","0px","0px"],"skewx":"0","skewy":"0","scalex":"1","scaley":"1","opacity":"1","xrotate":" in D:\home\site\wwwroot\wp-content\plugins\revslider\includes\framework\functions.class.php on line 14
****
# THEME
contains all plugins
[themeforest-6776630-kleo-next-level-wordpress-theme-wordpress-theme.zip](https://github.com/ProjectNami/projectnami/files/253645/themeforest-6776630-kleo-next-level-wordpress-theme-wordpress-theme.zip)
`

**Comment by patrickebates** [comment]
Let's start with the RevSlider issue.  Do this instructions here help with it?

http://support.projectnami.org/viewtopic.php?f=7&t=21&start=20#p362

**Comment by patrickebates** [comment]
Also, do you have any php_error.log or translate.log data for the issues with bbpress and BuddyPress?

**Comment by GeoffreyEmery** [comment]
Here are the logs. Reading through them now.
[php_errors.log.zip](https://github.com/ProjectNami/projectnami/files/253762/php_errors.log.zip)
[translate.log.zip](https://github.com/ProjectNami/projectnami/files/253763/translate.log.zip)

**Comment by GeoffreyEmery** [comment]
the revslider is less important then getting the forums and buddy press working so ill take a look at getting this set up on my local box since it takes around 20 min to provision and get the theme working on azure

**Comment by GeoffreyEmery** [comment]
also i attached the theme its called kleo if you have a quicker way to trouble shoot this. its going to take me a few hours to get this started locally

**Comment by GeoffreyEmery** [comment]
So update from today.
just started with the generic plugins without theme.
bbpress - seems to have passed
buddy press - has multiple translation errors see attached logs. 
[php_errors.zip](https://github.com/ProjectNami/projectnami/files/254446/php_errors.zip)

**Comment by GeoffreyEmery** [comment]
rev slider sql worked 

`alter table wp_revslider_css add [advanced] nvarchar(max) NULL
alter table wp_revslider_sliders add [type] VARCHAR(191) NOT NULL DEFAULT ''
alter table wp_revslider_sliders add [settings] nvarchar(max) NULL`

**Comment by GeoffreyEmery** [comment]
closing this as solved and moving other plugin to seperate for ease of tracking 
#82

**Comment by cberio** [comment]
I had to added following columns for import 
```SQL
alter table wp_revslider_sliders add [settings] nvarchar(max) NULL
alter table wp_revslider_static_slides add [settings] nvarchar(max) NULL
```

**Comment by cryans73** [comment]
Guys, I get the same issue today. I am new to this WordPress on the server side, so, for example when I read above post. I really don't understand what I need to do. Can you provide a little instruction for dummies on this :)  
![screenshot_1](https://user-images.githubusercontent.com/32163554/30715602-f11764f8-9ee4-11e7-8d5b-f6e6ed3a3512.png)   Now I can't even do anything, cant uninstall. I get that error anytime I try to navigate
