### ISSUE TITLE
Buddy Press Does not work after Successful install

### ISSUE THREAD

**Issue by GeoffreyEmery** [ProjectNami/projectnami#82]
# Buddy Press
installs but can not create or use features.
This is a fresh install with just adding buddy press as a plugin
Please See attached errors
****
[php_errors.zip](https://github.com/ProjectNami/projectnami/files/255338/php_errors.zip)

@patrickebates Can you please assist on next steps?

**Comment by GeoffreyEmery** [comment]
Seperated from this ticket
https://github.com/ProjectNami/projectnami/issues/81#issuecomment-217683764
#81

**Comment by GeoffreyEmery** [comment]
new users can't register is the first issue. I am not sure how i can help with this is there some tutorial to do the translations
[Archive.zip](https://github.com/ProjectNami/projectnami/files/258258/Archive.zip)

**Comment by GeoffreyEmery** [comment]
the above zip is a fresh install with just buddy press

**Comment by GeoffreyEmery** [comment]
Link to plugin..
https://wordpress.org/plugins/buddypress/

**Comment by patrickebates** [comment]
After reviewing the plugin files for BuddyPress, I'm not certain we will ever get it working.  Our translation support efforts are focused on plugins which make their own database calls outside the WP API, but supporting plugins which create tables can be troublesome at best.  Hence the manual update you had to apply to RevSlider in #81

**Comment by GeoffreyEmery** [comment]
its been my experience that most new feature plugins like buddy press will create their own tables they have to by definition. A true translation of the plugin installation would take the create/update to DB tables and translate those MYSQL calls in most cases literally to MSSQL calls and move forward. So if your not doing this then i think for the most cases this project will not be good for anything more then generic wordpress install sites. A simple use case.  You must **update your home your home to read we support some plugiins ** with a emphasis that you don't require plugins that create new tables.  Good luck.  I feel like if you would have been straight up on that I would have saved quite a bit of wasted time.

**Comment by patrickebates** [comment]
Now that's not to say that table creation will never work.  There are indeed translations present to handle table creation; they were designed for the syntax used by WP Core.  But there are many ways to write CREATE TABLE statements, especially in regards to how and where indexes are declared.  It's simply not feasible for us to accommodate each and every possibility.  You encountered part of this with RevSlider where the initial table creation succeeded, but the commands to modify and extend the schema failed.

If you're up to helping with the translation support as others have done recently, we would be happy to accept a pull request for BuddyPress.  At this point, we focus our internal efforts on plugins which do not create tables, but do perform direct queries against the database rather than using the APIs.  Prime examples are Yoast, Akismet, and Jetpack.

**Comment by GeoffreyEmery** [comment]
as previously stated is there some kind of documentation on where those translations exist? i asked to help but there needs to be a primer to get me up and running.

**Comment by patrickebates** [comment]
https://github.com/ProjectNami/projectnami/blob/master/wp-includes/translations.php

This is the file with all MySQL translation systems.  The core of this was borrowed from the DB Abstraction Plugin, but it's only invoked if a query generates one of a specific list errors from SQL Server.  Translations specific to Project Nami are contained in the function pre_translate_query at line 375.  

Function translate_create_queries at line 1397 dissects and reconstructs those types of queries.  The key constraint handling starting at like 1559 is where things start to go off the rails for create statements that don't follow the standards of WP Core.

**Comment by patrickebates** [comment]
I should clarify, for the moment pre_translate_query contains the translations for specific plugins. (See https://github.com/ProjectNami/projectnami/pull/79 for some insight)  There are additional updates throughout the file to correct general issues, including a few tweaks within translate_create_queries.

**Comment by GeoffreyEmery** [comment]
i am closing this as wont fix or out of scope.

**Comment by jdmdigital** [comment]
For the record, plugins which create tables are NOT a violation of the WordPress coding standards.  In fact, there's a whole article in the Codex on how plugins SHOULD create and update their own tables.   See: https://codex.wordpress.org/Creating_Tables_with_Plugins

Maybe back in 2016 things were different, but it's a pretty big issue with Nami if it won't, at least, support feature-rich plugins like BuddyPress and bbPress creating tables "The WordPress Way."  I should mention, BOTH of those plugins were founded by the original authors of the WordPress core and STILL actively supported by Automattic. 

https://bbpress.org/about/the-story/ 
https://buddypress.org/about/

I vote to add this to the scope.
