### ISSUE TITLE
Development / Release workflow with Project Nami

### ISSUE THREAD

**Issue by PirateBread** [ProjectNami/projectnami#83]
Hi chaps,

I've been asked to setup a ci/stage/prod environments for Wordpress in Azure and I came across Project Nami. So this is a general question around how to best setup a development/release workflow with Project Nami.

Is there anything specific to Project Nami that I need to consider? I've seen WP Migrate DB Pro recommended as a plugin for moving data between environments. Does anyone know if that works with Project Nami?

Otherwise I would love to hear how you setup you dev/release workflows.

**Comment by patrickebates** [comment]
Spencer should be available in a couple of days to give you some detailed information.  In the meantime, I can give you a few basic options.

1) Backup and restore of the SQL database
2) Export and import using the default methods in WordPress.  I've done this myself when setting up a dev env within a multisite.

**Comment by PirateBread** [comment]
Hi Patrick thanks for the response.

One of the points I have to consider is that the sites are being developed in standard LAMP stack somewhere. So when I get sent a mysql dump of the database I'm kind of stuck.

So I take it from your comment that I should instead be getting Wordpress compatible exports and using those in my workflow rather than for example doing direct database comparisons as you might normally do.

**Comment by GrimaceOfDespair** [comment]
Just wanted to add for reference purposes that I'm using ProjectNami for my local development, while my staging and production sites are stock WP. I can confirm that ProjectNami is not compatible with WP Migrate DB Pro, so you're stuck with WP import/export - which breaks the auto media-download for this kind of setup.
