### ISSUE TITLE
Cloner Plugins

### ISSUE THREAD

**Issue by kinandd** [ProjectNami/projectnami#85]
I have been trying to get multiple cloner plugins to work on my multisite installation of wordpress. All attempts for all plugins (I'm using the cloner plugin by WPMU currently) result in a new wordpress site being created but with none of the content being migrated over .

**Comment by kinandd** [comment]
I was wondering if anyone has had a chance to look at this issue or has experienced the same issue.

**Comment by patrickebates** [comment]
I haven't yet looked into this specific plugin, but I would bet that it uses MySQL-specific syntax to copy the data over.  Probably easier to create a new cloner plugin using SQL Server syntax than to adapt this one.
