### ISSUE TITLE
Any plans to turn this into a docker container

### ISSUE THREAD

**Issue by Amblomeke** [ProjectNami/projectnami#86]
I have a heavily customized instance of WordPress that I've been tasked with migrating to Azure, AzureSQL, and running in Docker via Terraform/Deis.  Seems like nami would be the perfect means of achieving this, but for the docker piece.

Thanks,
Adam

**Comment by patrickebates** [comment]
To clarify, are you talking about Windows Server Containers?  I ask because Project Nami currently only runs on Windows.  Currently...

**Comment by Amblomeke** [comment]
That would have to be the way it would be done, given that limitation.

**Comment by patrickebates** [comment]
I was planning to look into that option, but I believe that system is still in Preview for use with Windows Server 2016.  Am I wrong on any of that?

**Comment by Amblomeke** [comment]
https://www.docker.com/microsoft

That appears to be the case

**Comment by guidooliveira** [comment]
well, there's azure container service generally available, couldn't it work with it as well, since they're basically containers?

**Comment by patrickebates** [comment]
AFAIK, we're still dealing with Linux containers when talking Azure Container Service.  At least for the moment.

As we announced last week, support for Linux as the PN front end should simply be a bit of a waiting game at this point.
http://projectnami.org/three-years-of-project-nami/

**Comment by Cyberboss** [comment]
https://github.com/Cyberboss/ProjectNamiDocker
