### ISSUE TITLE
Error on translations.php since last update

### ISSUE THREAD

**Issue by Angelixion** [ProjectNami/projectnami#87]
I updated yesterday to 1.3.3 (WP 4.5.2) and today i go to check the log files and i find this errors repeating every 20-30 seconds or so.
`PHP Warning:  preg_replace(): Compilation failed: missing ) at offset 125 in D:\home\site\wwwroot\wp-includes\translations.php on line 1376`
`PHP Warning:  preg_replace(): Compilation failed: missing ) at offset 126 in D:\home\site\wwwroot\wp-includes\translations.php on line 1376
`
the corresponding part of translations.php

```
function translate_incompat_data_type($query)
    {
        if ( !$this->select_query && !$this->delete_query ) {
            return $query;
        }

        $operators = array(
            '='  => 'LIKE',
            '!=' => 'NOT LIKE',
            '<>' => 'NOT LIKE'
        );

        $field_types = array('ntext', 'nvarchar', 'text', 'varchar');

        foreach($this->fields_map->read() as $table => $table_fields) {
            if (!is_array($table_fields)) {
                continue;
            }
            foreach ($table_fields as $field => $field_meta) {
                if ( !in_array($field_meta['type'], $field_types) ) {
                    continue;
                }
                foreach($operators as $oper => $val) {
                    $query = preg_replace('/\s+'.$table . '.' . $field.'\s*'.$oper.'/i', ' '.$table . '.' . $field . ' ' . $val, $query);
                    $query = preg_replace('/\s+'.$field.'\s*'.$oper.'/i', ' ' . $field . ' ' . $val, $query);
                    // check for integers to cast.
                    $query = preg_replace('/\s+LIKE\s*(-?\d+)/i', " {$val} cast($1 as nvarchar(max))", $query);
                }
            }

        }

        return $query;
    }
```

**Comment by pippercameron** [comment]
Thanks for the report! We'll take a look.

**Comment by Angelixion** [comment]
I found out the problem, yoast premium(not the free version) calls it, i deactivated it on the meantime.

**Comment by patrickebates** [comment]
Could you please provide us with the SQL it is attempting to execute?  Yoast is something we have written specific translations for before, so I would want to look at doing the same here.  Thanks.

**Comment by WSI40** [comment]
Hi, i got also the Problems on translations.php, on the same line. I deactivated yoast, but the Problem is still there, are there an other why more, to solve the problems?

**Comment by Vidocq24601** [comment]
Hi Patrick,

The most recent Yoast translation update (isolated the issue to Yoast) has recreated a similar error. 

Warning: preg_replace(): Compilation failed: missing ) at offset 250 in D:\home\site\wwwroot\wp-includes\translations.php on line 1483

$query = preg_replace('/\s+'.$table . '.' . $field.'\s*'.$oper.'/i', ' '.$table . '.' . $field . ' ' . $val, $query);
