### ISSUE TITLE
Deployment process takes so long

### ISSUE THREAD

**Issue by Rabbit96** [ProjectNami/projectnami#89]
I am using DreamSpark for students, and I am from Vietnam. I went to the Project Nami download site, and clicked Deploy to Azure. I filled in some basic information (Location Southeast Asea, Free, DreamSpark), clicked Next and clicked Deploy. Deployment was fast until Adding SQL Server Database. I waited for about one hour but it could not finish. Please help me.

**Comment by pippercameron** [comment]
We haven't seen this reported before. We don't actually control the deployment process, so there's not much we can do on our end. Have you tried again since?

**Comment by patrickebates** [comment]
Might not be related, but we once heard of an issue if you attempt to deploy into anything other than your Default Directory.
http://support.projectnami.org/viewtopic.php?f=4&t=80#p453

**Comment by Rabbit96** [comment]
I tried and waited for about 3 hours maybe. It stopped and said "Microsoft.Sql takes so long to response" or something.

**Comment by patrickebates** [comment]
No need for that.  The longest the entire process should take is about five minutes.  I would suggest trying again, and double check the option you set for Directory.

**Comment by Rabbit96** [comment]
I always use the Default Directory.
