### ISSUE TITLE
Looking for a Backup Plugin That Supports ProjectNami

### ISSUE THREAD

**Issue by TylerK93** [ProjectNami/projectnami#90]
Hi all,

I don't know if this is the right place to post this, but it's the best I can think of since Googling hasn't been much help. I'm looking for a backup plugin that supports ProjectNami so that I can employ a 3-2-1 backup strategy for my sites hosted in Azure. I've been driven to do this due to an infrastructure failure on the bridge server that connects the Azure Stack that I use to the public cloud, which resulted in the loss of one of my customers' sites. I was able to restore it from a five-month-old WordPress XML backup, but I'd really like to find a solution that would allow me to backup the entire site (files, database, etc) off-site and easily restore it in the event of another catastrophic failure, which I hope never happens again. I've tried VaultPress, but that system doesn't support MS SQL, and nor does BackWpUp or BackupBuddy (as best I can tell from its system requirements).

Any help would be greatly appreciated.

Thanks!

**Comment by patrickebates** [comment]
This is something I've been debating myself for some time now, so let me ask a few questions that have come to mind.

1. You mention you are using Azure Stack; does this mean SQL is on-prem and if so how would a backup plugin benefit you over using a DB Maintenance Plan?
2. If you might have been using Azure SQL DB instead, how would a backup plugin benefit you over the built-in DB backups provided automatically?
3. If a plugin existed, what format should the backup take?  A SQL Server backup file?  BCP files?  Something else?
4. Where should such a plugin store the backup?  Azure Blob Storage?  Other options? (I can't imagine using local file system, especially if running in Azure Web App)

These are a few of the questions I need to answer before committing to writing such a plugin.  As a SQL DB guy, I'm having a hard time getting past these and arriving at a solution that makes sense.

**Comment by TylerK93** [comment]
@patrickebates, this is using Azure SQL DB. I want to have a backup solution that is able to backup the entire SQL database, perhaps as a single SQL Server backup file or one file per table, as VaultPress does. Then I would want the backup plugin to be able to connect to off-site cloud storage, like Dropbox. Just my thoughts.

**Comment by patrickebates** [comment]
Let me start with the site you mentioned you lost.  Even at the Basic level, Azure SQL DB maintains full DB backups for 7 days.  Was that not sufficient to recover the site?

**Comment by TylerK93** [comment]
No, it wasn't. I lost access to the data due to a bridge server failure 
that made it so I couldn't access any of my subscriptions.
