### ISSUE TITLE
Support for Azure Application Insights?

### ISSUE THREAD

**Issue by rcarmo** [ProjectNami/projectnami#92]
It would be nice to have this out-of-the-box, as it were.

**Comment by patrickebates** [comment]
There's a plugin for at least part of that.
https://wordpress.org/plugins/application-insights/

Is there additional support we should consider?

**Comment by nromyn** [comment]
I was just looking at this and pondering whether I should take the time and attempt to put it together. The wordpress plugin gives instrumentation as far as the page views, unique users - but there's additional support for instrumenting at a lower level i.e. server errors and sql query analysis, but it needs to be built into the application. https://github.com/Microsoft/ApplicationInsights-PHP

**Comment by rcarmo** [comment]
The reason I asked is that I’m interested in the SQL layer metrics, largely because of the impact of plugins. I can always check out the SQL DB metrics on the Azure portal, but it helps a lot when you have everything synced together in App Insights…
