### ISSUE TITLE
Installation from Portal Azure Issue (Bad format on server template)

### ISSUE THREAD

**Issue by wratte** [ProjectNami/projectnami#93]
I want to install the project from Portal on existing database server and existing database. I keep receiving this following error. Also I tried to install from "Deploy to Azure"  inhttp://projectnami.org/download/ but it creates new db server, new database and new service plan. It works fine but this is not what we want. Is there any other way to install project Nami?

Thanks in advance! 

Error submitting the deployment request. Additional details from the underlying API that might be helpful: Deployment template validation failed: 'The resource 'Microsoft.Sql/servers/MyServerName' is not defined in the template. Please see http://aka.ms/arm-template for usage details.'. (Code: InvalidTemplate)

{
    "id": "******************************",
    "name": "MyServerName",
    "type": "Microsoft.Sql/servers",
    "location": "East US",
    "kind": "v12.0",
    "properties": {
        "fullyQualifiedDomainName": "databaseName.database.windows.net",
        "administratorLogin": "xxxxxxxxxxxxx",
        "administratorLoginPassword": null,
        "externalAdministratorLogin": null,
        "externalAdministratorSid": null,
        "version": "12.0",
        "state": "Ready"
    }
}

**Comment by patrickebates** [comment]
Unfortunately, we have no control over the template used by the Gallery deployment option.

As for alternatives, one option would be to create the SQL DB and Web App manually (so you can select the server and App Plan of your choice) and then deploy PN into the Web App.  You could do that via FTP, but if the Web App will be dedicated to PN there is an easier way.  You can configure the Continuous Deployment settings of the Web App as follows...

Source -- External Repository 
URL -- https://github.com/ProjectNami/projectnami 
Branch -- latest
