### ISSUE TITLE
Revolution Slider Issues [was "Invalid column name 'advanced'"]

### ISSUE THREAD

**Issue by debjac** [ProjectNami/projectnami#95]
Hi there. I'm getting a fatal SQL error when a plugin is trying to create tables. 
I'm getting the following error:
"Fatal error: Uncaught exception 'Exception' with message 'Insert query error - [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'advanced'."

I found "advanced" in the plugin code but changing it to advanced1 didn't solve it. Here's their code:
$sql = "CREATE TABLE " .self::$table_prefix.$tableName ." (
                          id int(9) NOT NULL AUTO_INCREMENT,
                          handle TEXT NOT NULL,
                          settings LONGTEXT,
                          hover LONGTEXT,
                          advanced MEDIUMTEXT,
                          params TEXT NOT NULL,
                          UNIQUE KEY id (id)
                        );";
            dbDelta($sql);

Should this be solved by the plugin creator or can it be fixed by project nami?

The plugin is revolution slider by https://revolution.themepunch.com/

Thx,
Jacques

**Comment by patrickebates** [comment]
Plugins which create tables are a violation of WP coding standards.  We fully support plugins which use the WP APIs, but it's simply not feasible to accommodate every possible syntax form for creating tables.  We do have syntax translation for CREATE TABLE statements which match those originally in WordPress, which is why you got this far with RevSlider.  The problem is with adding columns to the table.

For workaround, see
http://support.projectnami.org/viewtopic.php?f=7&t=21&start=20#p362
and
https://github.com/ProjectNami/projectnami/issues/81

**Comment by debjac** [comment]
Great! Sorry I missed that on the forum. I will try that this evening.
Thx,
-J

**Comment by debjac** [comment]
Running the query solved the activation issue. The Revslider is now partially working.
I'm now running into 2 issues: 
- slides with settings related to video are not saved
- importing slider templates generate DB errors:
"importing template slider settings and data...
dynamic styles imported!
Warning: vsprintf(): Too few arguments in D:\home\site\wwwroot\wp-includes\translations.php on line 324 
Error: Insert query error - [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'settings'.
---
 Query: INSERT INTO [wpsoonr2_revslider_static_slides] ([slider_id], [layers], [params], [settings]) VALUES ('6', '[]', '{"background_type":"trans"}', '[""]')
Go Back"

Maybe we're hitting the limits of translating all the DB statements?
Or maybe not?

Thx,
-J

**Comment by patrickebates** [comment]
Looks like another table which failed to add a column.  Try this.
`alter table wpsoonr2_revslider_static_slides add [settings] nvarchar(max) NULL`

**Comment by GrimaceOfDespair** [comment]
Since I ran into this too, and given the fact that RevolutionSlider is pretty widely used (which makes it even more sad that it doesn't follow WP guidelines), I'd like to suggest to keep this ticket open, and collect the ALTER TABLE statements in here.

**Comment by PoeNedge** [comment]
How did you guys fix this, is there a guide for running queries (I know nothing about this). I'm trying to give Project Nami a chance here but I really need rev slider to work and I'm getting the same error. Thanks

**Comment by patrickebates** [comment]
If you don't have, or don't want to install, SQL Server Management Studio (which is now a free download) it appears there is a new option in the Azure portal currently in Preview.

From the Azure portal, locate your SQL DB and after selecting it click the Tools option in the header bar.  You may need to opt-in to the Preview.  Then click Login and enter your credentials.  You should now be able to paste in the queries one at a time and execute them.
