### ISSUE TITLE
Deploying to a sub-directory of an existing Azure web app

### ISSUE THREAD

**Issue by rsuliteanu** [ProjectNami/projectnami#96]
I have an existing Azure web app running SQL Server. I want to add a WordPress blog as a sub-directory. I downloaded the Project Nami files into a "blog" sub-directory on my local machine and published my app. In Azure portal, I turned on PHP to 5.6, made sure index.php is in default files and I added a virtual directory of "blog" pointing to "site\wwwroot\blog" (Application checkbox left unchecked). When I navigate to myapp/blog, it redirects to /blog/wp-admin/setup-config.php and then I get this error: The myapp.azurewebsites.net page isn’t working

myapp.azurewebsites.net is currently unable to handle this request. HTTP ERROR 500

Is my approach invalid or any ideas on what I'm doing (not doing) wrong?

Thanks in advance!

**Comment by patrickebates** [comment]
Did you test before adding the virtual directory?  I know of a site doing exactly this same thing (ASP.Net app in the root, Project Nami in blog subfolder) and nothing special was needed, not even in web.config.

https://peakwellnessnutrition.com/blog/

**Comment by rsuliteanu** [comment]
Okay. I removed the virtual directory. Same error. Then I switched the PHP
version to 7.0 and I got this more helpful error on hitting the page:

Your PHP installation appears to be missing the SQLSrv extension which is
required by Project Nami.

Do you know how/where I would install that? I assumed it would come as part
of the Project Nami files.

Do I need to do any configuration changes before running setup-config.php?

Thanks! I'm completely new to WordPress. I'm an ASP.NET developer being
asked to add a WP blog to the site.

Ron

**Comment by patrickebates** [comment]
The error with 7.0 is not related to the issue with 5.6.  Microsoft has yet to release a production build of SqlSrv for PHP 7, so it's not present.

Could you check the LogFiles folder of your Web App and see if anything stands out in either the .Net error log or php_errors.log?

**Comment by rsuliteanu** [comment]
Okay, that makes sense. Back to 5.6. It seems like PHP is running, since
it's getting to the setup-config.php file from the index.php file. There
are no PHP error log files. Nothing in the event log.

Anything else you can think of? Does the PHP code have the permissions to
write to the subdirectory?

I REALLY appreciate your help! I'd love to get this working without having
to pull out what little hair I have left :-)

FYI, other settings from the Portal:

.NET Framework version: v4.6
PHP Version: 5.6
Java version: Off
Python version: Off
Platform: 32-bit
Web sockets: Off
Always On: Off
Managed Pipeline Version: Integrated

**Comment by patrickebates** [comment]
What files did you download?  Was it Version 1.3.3 from the Releases or was it a copy of Master?

**Comment by patrickebates** [comment]
For the sake of argument, have you attempted to create an additional empty Web App within your hosting plan and tested the installation in the /blog folder?  If that succeeds, you might have some settings in the web.config of your root application that need to be looked at.  With the Integrated pipeline, PHP has some reliance on the ASP.Net environment.  In fact, this is how our Blob Cache system operates.

**Comment by rsuliteanu** [comment]
Patrick,

Thank you so much for your help. I have it working now. It turned out to be
an issue with Azure as well as something I was doing incorrectly - I
contacted their tech support and they provided a fix.

Best regards,
Ron
