### ISSUE TITLE
Business Directory plugin fatal error

### ISSUE THREAD

**Issue by cyberjohn** [ProjectNami/projectnami#97]
After installing Business Directory plugin site is down with following Error , please advise if fixable 

Fatal error: Uncaught exception 'Exception' with message 'Invalid property name: label' in D:\home\site\wwwroot\wp-content\plugins\business-directory-plugin\core\class-db-entity.php:73 Stack trace: #0 D:\home\site\wwwroot\wp-content\plugins\business-directory-plugin\core\class-fee-plan.php(17): WPBDP_DB_Entity->__get('label') #1 D:\home\site\wwwroot\wp-content\plugins\business-directory-plugin\core\class-fee-plan.php(13): WPBDP_Fee_Plan->sanitize() #2 D:\home\site\wwwroot\wp-content\plugins\business-directory-plugin\core\installer.php(54): WPBDP_Fee_Plan->__construct(Array) #3 D:\home\site\wwwroot\wp-content\plugins\business-directory-plugin\business-directory-plugin.php(638): WPBDP_Installer->install() #4 D:\home\site\wwwroot\wp-content\plugins\business-directory-plugin\business-directory-plugin.php(140): WPBDP_Plugin->install_or_update_plugin() #5 [internal function]: WPBDP_Plugin->init('') #6 D:\home\site\wwwroot\wp-includes\plugin.php(525): call_user_func_array(Array, Array) #7 D:\home\site\wwwroot\wp-settings.php(393 in D:\home\site\wwwroot\wp-content\plugins\business-directory-plugin\core\class-db-entity.php on line 73

**Comment by patrickebates** [comment]
Recommend that you remove the plugin folder from the site, which should forcibly uninstall it.  You can then get the site operating again.  Then we can look at the class-db-entity.php and see what the issue is.

**Comment by cyberjohn** [comment]
Thanks Patrick I had deleted plugin but just seeking advise if plugin can be compatible, please advise where to locate class-db-entity.php 
Thanks in advance 
John

**Comment by cyberjohn** [comment]
Hi Patrick , Please find Attached the class-db-entity and files shown in error

Thanks for all your kind help
John



[pnerror.zip](https://github.com/ProjectNami/projectnami/files/296224/pnerror.zip)

**Comment by patrickebates** [comment]
Looks to me like this plugin won't operate without a significant amount of work.  In addition to creating new DB tables (technically a violation of WP coding standards, and subject to significant syntax errors with SQL Server) it also uses its own constructors for queries against those tables.

**Comment by cyberjohn** [comment]
Thanks for update Patrick sounds like to much of headache which would require alot of ongoing work. I will use different plugin.
Thanks 
John
